// Code generated by oagen. DO NOT EDIT.

package main

import (
	"archive/tar"
	"archive/zip"
	"bytes"
	"compress/gzip"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"runtime/debug"
	"strings"
	"testing"
)

func TestReleaseRegistrationRequiresProductionOrigin(t *testing.T) {
	t.Setenv("SELLAPP_CLI_PUBLIC_CLIENT_ID", "")
	t.Setenv("SELLAPP_CLI_OAUTH_ORIGIN", "")
	if _, err := releaseRegistration(false); err != nil {
		t.Fatal(err)
	}
	if _, err := releaseRegistration(true); err == nil {
		t.Fatal("accepted unconfigured production login")
	}
	for _, origin := range []string{"https://staging.example.invalid", "http://sell.app", "https://sell.app/", "https://sell.app.evil.invalid"} {
		t.Setenv("SELLAPP_CLI_OAUTH_ORIGIN", origin)
		if _, err := releaseRegistration(false); err == nil {
			t.Fatal("accepted nonproduction release origin", origin)
		}
	}
	t.Setenv("SELLAPP_CLI_OAUTH_ORIGIN", productionOrigin)
	t.Setenv("SELLAPP_CLI_PUBLIC_CLIENT_ID", "public-production-id")
	if id, err := releaseRegistration(true); err != nil || id != "public-production-id" {
		t.Fatal("rejected production registration", id, err)
	}
	t.Setenv("SELLAPP_CLI_PUBLIC_CLIENT_ID", "invalid client id")
	if _, err := releaseRegistration(true); err == nil {
		t.Fatal("accepted invalid client id")
	}
}
func TestDeterministicArchives(t *testing.T) {
	for _, windows := range []bool{false, true} {
		one, err := archiveBytes([]entry{{"README.md", []byte("documentation"), 0644}, {"sellapp", []byte("binary"), 0755}}, windows)
		if err != nil {
			t.Fatal(err)
		}
		two, err := archiveBytes([]entry{{"sellapp", []byte("binary"), 0755}, {"README.md", []byte("documentation"), 0644}}, windows)
		if err != nil || !bytes.Equal(one, two) {
			t.Fatal("archive is not reproducible", err)
		}
		modes := map[string]uint32{}
		data := map[string]string{}
		if windows {
			reader, err := zip.NewReader(bytes.NewReader(one), int64(len(one)))
			if err != nil {
				t.Fatal(err)
			}
			for _, file := range reader.File {
				modes[file.Name] = uint32(file.Mode().Perm())
				item, err := file.Open()
				if err != nil {
					t.Fatal(err)
				}
				content, err := io.ReadAll(item)
				item.Close()
				if err != nil {
					t.Fatal(err)
				}
				data[file.Name] = string(content)
			}
		} else {
			compressed, err := gzip.NewReader(bytes.NewReader(one))
			if err != nil {
				t.Fatal(err)
			}
			defer compressed.Close()
			reader := tar.NewReader(compressed)
			for {
				file, err := reader.Next()
				if err == io.EOF {
					break
				}
				if err != nil {
					t.Fatal(err)
				}
				modes[file.Name] = uint32(file.Mode)
				content, err := io.ReadAll(reader)
				if err != nil {
					t.Fatal(err)
				}
				data[file.Name] = string(content)
			}
		}
		if modes["sellapp"] != 0755 || modes["README.md"] != 0644 || data["sellapp"] != "binary" || data["README.md"] != "documentation" {
			t.Fatal("archive roundtrip failed", modes, data)
		}
	}
}
func TestVerifierRejectsCorruptionAndMissingArtifacts(t *testing.T) {
	originalInspector := inspectBinary
	t.Cleanup(func() { inspectBinary = originalInspector })
	inspectBinary = func(reader io.ReaderAt) (*debug.BuildInfo, error) {
		data := make([]byte, 64)
		n, _ := reader.ReadAt(data, 0)
		parts := strings.Split(string(data[:n]), "/")
		return &debug.BuildInfo{Settings: []debug.BuildSetting{{Key: "GOOS", Value: parts[0]}, {Key: "GOARCH", Value: parts[1]}}}, nil
	}
	directory := t.TempDir()
	lines := []string{}
	artifacts := map[string]string{}
	optional := map[string]string{}
	put := func(name string, data []byte) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(directory, name), data, 0644); err != nil {
			t.Fatal(err)
		}
		lines = append(lines, sum(data)+"  "+name)
		artifacts[name] = sum(data)
	}
	encode := func(value any) []byte {
		t.Helper()
		data, err := jsonBytes(value)
		if err != nil {
			t.Fatal(err)
		}
		return data
	}
	guide := []entry{}
	for _, name := range []string{"README.md", "LICENSE.txt", "docs/usage.md", "docs/contributing.md", "skills/sellapp/SKILL.md", "skills/sellapp/references/connect-store.md", "skills/sellapp/references/product-variant.md", "skills/sellapp/references/checkout.md", "skills/sellapp/references/orders-fulfillment-refunds.md", "skills/sellapp/references/subscriptions.md", "skills/sellapp/references/customer-support.md", "skills/sellapp/references/webhooks.md", "skills/sellapp/references/exports.md"} {
		guide = append(guide, entry{name, []byte("guidance"), 0644})
	}
	guide = append(guide, entry{"licenses/a/LICENSE", []byte("license"), 0644})
	pack := func(name string, files []entry) {
		t.Helper()
		for i := range files {
			files[i].name = "package/" + files[i].name
		}
		data, err := archiveBytes(files, false)
		if err != nil {
			t.Fatal(err)
		}
		put(name, data)
	}
	for _, target := range targets {
		windows := target[0] == "windows"
		binaryName := "sellapp"
		extension := ".tar.gz"
		if windows {
			binaryName += ".exe"
			extension = ".zip"
		}
		binary := []byte(target[0] + "/" + target[1])
		info, _ := inspectBinary(bytes.NewReader(binary))
		metadata := encode(map[string]any{"version": version, "target": target[0] + "/" + target[1], "sourceTreeSha256": "source", "oauthOrigin": productionOrigin, "publicOAuthClientID": "release-test-client", "browserOnboardingConfigured": true, "binarySha256": sum(binary), "buildInfo": info, "unsigned": true, "dependencies": []map[string]string{{"path": "fixture"}}, "materials": map[string]string{"fixture": "digest"}, "licenseNotices": map[string]string{"licenses/a/LICENSE": sum([]byte("license"))}})
		contents := append(append([]entry{}, guide...), entry{binaryName, binary, 0755}, entry{"build-info.json", metadata, 0644}, entry{"internal/catalog/embedding.json", []byte("{}"), 0644})
		archive, err := archiveBytes(contents, windows)
		if err != nil {
			t.Fatal(err)
		}
		put("sellapp_"+version+"_"+target[0]+"_"+target[1]+extension, archive)
		platform, cpu := npmTarget(target)
		name := "@sellapp/cli-" + platform + "-" + cpu
		optional[name] = version
		pack("sellapp-cli-"+platform+"-"+cpu+"-"+version+".tgz", []entry{{"package.json", encode(map[string]any{"name": name, "version": version, "os": []string{platform}, "cpu": []string{cpu}}), 0644}, {"bin/" + binaryName, binary, 0755}, {"build-info.json", metadata, 0644}, {"licenses/a/LICENSE", []byte("license"), 0644}})
	}
	pack("sellapp-cli-"+version+".tgz", append(append([]entry{}, guide...), entry{"package.json", encode(map[string]any{"name": "@sellapp/cli", "version": version, "engines": map[string]string{"node": ">=22"}, "bin": map[string]string{"sellapp": "bin/sellapp.cjs"}, "optionalDependencies": optional}), 0644}, entry{"bin/sellapp.cjs", []byte("launcher"), 0755}))
	put("install.sh", []byte("installer"))
	put("release-manifest.json", encode(map[string]any{"version": version, "repository": repository, "releaseTag": "v" + version, "releaseURL": "https://github.com/" + repository + "/releases/tag/v" + version, "sourceTreeSha256": "source", "oauthOrigin": productionOrigin, "publicOAuthClientID": "release-test-client", "browserOnboardingConfigured": true, "unsigned": true, "artifacts": artifacts}))
	writeSums := func(value string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(directory, "SHA256SUMS"), []byte(value), 0644); err != nil {
			t.Fatal(err)
		}
	}
	complete := strings.Join(lines, "\n") + "\n"
	writeSums(complete)
	if err := verifyDirectory(directory, true); err != nil {
		t.Fatal(err)
	}
	manifestPath := filepath.Join(directory, "release-manifest.json")
	originalManifest, err := os.ReadFile(manifestPath)
	if err != nil {
		t.Fatal(err)
	}
	for _, field := range []string{"version", "repository", "releaseTag", "releaseURL", "oauthOrigin", "publicOAuthClientID"} {
		var changed map[string]any
		if err := json.Unmarshal(originalManifest, &changed); err != nil {
			t.Fatal(err)
		}
		changed[field] = "incorrect"
		data := encode(changed)
		if err := os.WriteFile(manifestPath, data, 0644); err != nil {
			t.Fatal(err)
		}
		writeSums(strings.ReplaceAll(complete, sum(originalManifest)+"  release-manifest.json", sum(data)+"  release-manifest.json"))
		if err := verifyDirectory(directory, false); err == nil {
			t.Fatal("accepted incorrect manifest identity", field)
		}
	}
	if err := os.WriteFile(manifestPath, originalManifest, 0644); err != nil {
		t.Fatal(err)
	}
	writeSums(complete)
	savedInspector := inspectBinary
	inspectBinary = func(reader io.ReaderAt) (*debug.BuildInfo, error) {
		return &debug.BuildInfo{GoVersion: "changed", Settings: []debug.BuildSetting{{Key: "GOOS", Value: "linux"}, {Key: "GOARCH", Value: "amd64"}}}, nil
	}
	if err := verifyDirectory(directory, false); err == nil {
		t.Fatal("accepted build metadata that differs from binary")
	}
	inspectBinary = savedInspector
	writeSums(strings.Join(lines[:len(lines)-1], "\n"))
	if err := verifyDirectory(directory, false); err == nil {
		t.Fatal("accepted missing artifact")
	}
	writeSums(complete + lines[0] + "\n")
	if err := verifyDirectory(directory, false); err == nil {
		t.Fatal("accepted duplicate entry")
	}
	writeSums(complete)
	if err := os.WriteFile(filepath.Join(directory, "sellapp_"+version+"_linux_amd64.tar.gz"), []byte("corruption"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := verifyDirectory(directory, false); err == nil {
		t.Fatal("accepted corrupted archive")
	}
}
func TestArchiveBytesDoesNotMutateInput(t *testing.T) {
	files := []entry{{"z", []byte("z"), 0644}, {"a", []byte("a"), 0644}}
	if _, err := archiveBytes(files, true); err != nil {
		t.Fatal(err)
	}
	if files[0].name != "z" || files[1].name != "a" {
		t.Fatalf("archiveBytes mutated caller input: %v", files)
	}
}
func TestArchiveReaderRefusesUnsafeAndDuplicatePaths(t *testing.T) {
	for _, windows := range []bool{false, true} {
		for _, name := range []string{"../escape", "/absolute", "a\\b", "line\nbreak", "same"} {
			t.Run(name, func(t *testing.T) {
				files := []entry{{name, []byte("bad"), 0644}}
				if name == "same" {
					files = append(files, files[0])
				}
				data, err := archiveBytes(files, windows)
				if err != nil {
					t.Fatal(err)
				}
				if _, err := readArchive(data, windows); err == nil {
					t.Fatal("accepted unsafe archive")
				}
			})
		}
	}
}
func TestNpmTargetMatrix(t *testing.T) {
	expected := map[[2]string][2]string{{"linux", "amd64"}: {"linux", "x64"}, {"linux", "arm64"}: {"linux", "arm64"}, {"darwin", "amd64"}: {"darwin", "x64"}, {"darwin", "arm64"}: {"darwin", "arm64"}, {"windows", "amd64"}: {"win32", "x64"}, {"windows", "arm64"}: {"win32", "arm64"}}
	for _, target := range targets {
		platform, cpu := npmTarget(target)
		if expected[target] != [2]string{platform, cpu} {
			t.Fatal("incorrect npm target", target, platform, cpu)
		}
	}
}
func TestNpmArchivesPreserveExecutableModes(t *testing.T) {
	directory := t.TempDir()
	artifacts := map[string]string{}
	manifest, _ := json.Marshal(map[string]string{"name": "fixture"})
	if err := writeNpm(directory, "fixture.tgz", []entry{{"package.json", manifest, 0644}, {"bin/sellapp", []byte("binary"), 0755}}, artifacts); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(directory, "fixture.tgz"))
	if err != nil {
		t.Fatal(err)
	}
	compressed, err := gzip.NewReader(bytes.NewReader(data))
	if err != nil {
		t.Fatal(err)
	}
	defer compressed.Close()
	reader := tar.NewReader(compressed)
	for {
		header, err := reader.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatal(err)
		}
		if header.Name == "package/bin/sellapp" && header.Mode != 0755 {
			t.Fatal("npm binary is not executable")
		}
	}
}
