// Code generated by oagen. DO NOT EDIT.

package main

import (
	"archive/tar"
	"archive/zip"
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"debug/buildinfo"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime/debug"
	"sort"
	"strings"
	"time"
)

var targets = [][2]string{{"linux", "amd64"}, {"linux", "arm64"}, {"darwin", "amd64"}, {"darwin", "arm64"}, {"windows", "amd64"}, {"windows", "arm64"}}

const version = "0.1.0"
const repository = "sellapp/sellapp-cli"
const productionOrigin = "https://sell.app"

var inspectBinary = buildinfo.Read
var epoch = time.Unix(315532800, 0).UTC() // ZIP's earliest portable date: 1980-01-01.
type entry struct {
	name string
	data []byte
	mode fs.FileMode
}
type module struct {
	Path, Version, Sum, GoModSum, Dir string
	Main                              bool
	Replace                           *module
}

func main() {
	output := flag.String("output", "dist", "new or empty local output directory")
	verify := flag.Bool("verify", false, "verify a previously built output directory without rebuilding")
	production := flag.Bool("production", false, "require configured production browser login before building or verifying publication artifacts")
	flag.Parse()
	if flag.NArg() != 0 {
		fail(fmt.Errorf("unexpected arguments"))
	}
	if *verify {
		if err := verifyDirectory(*output, *production); err != nil {
			fail(err)
		}
		fmt.Println("Release checksums and archive contents verified (unsigned).")
		return
	}
	if err := release(*output, *production); err != nil {
		fail(err)
	}
}
func fail(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
func command(env []string, args ...string) ([]byte, error) {
	cmd := exec.Command("go", args...)
	// Fix build-affecting user environment to make the declared settings truthful.
	cmd.Env = append(os.Environ(), "CGO_ENABLED=0", "GOFLAGS=", "GOWORK=off", "GOEXPERIMENT=", "GOAMD64=v1", "GOARM64=v8.0")
	cmd.Env = append(cmd.Env, env...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("go %s: %w\n%s", strings.Join(args, " "), err, out)
	}
	return out, nil
}
func sum(data []byte) string { digest := sha256.Sum256(data); return hex.EncodeToString(digest[:]) }
func jsonBytes(value any) ([]byte, error) {
	data, err := json.MarshalIndent(value, "", "  ")
	return append(data, '\n'), err
}
func sourceFiles() ([]entry, error) {
	files := []entry{}
	for _, root := range []string{"cmd", "internal", "tools", "docs", "examples", "skills", "npm", "install.sh", "go.mod", "go.sum", "README.md", "LICENSE.txt"} {
		err := filepath.WalkDir(root, func(path string, item fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if item.Type()&os.ModeSymlink != 0 {
				return fmt.Errorf("source symlink not allowed: %s", path)
			}
			if item.IsDir() {
				return nil
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			files = append(files, entry{filepath.ToSlash(path), data, 0644})
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	// Generation metadata is optional for standalone emitters; never manufacture it.
	for _, name := range []string{"generation-manifest.json", ".oagen-manifest.json"} {
		data, err := os.ReadFile(name)
		if err == nil {
			files = append(files, entry{name, data, 0644})
		} else if !os.IsNotExist(err) {
			return nil, err
		}
	}
	sort.Slice(files, func(i, j int) bool { return files[i].name < files[j].name })
	return files, nil
}
func releaseRegistration(production bool) (string, error) {
	origin := os.Getenv("SELLAPP_CLI_OAUTH_ORIGIN")
	if origin != "" && origin != productionOrigin {
		return "", fmt.Errorf("release artifacts must use %s; unset SELLAPP_CLI_OAUTH_ORIGIN or set it to that exact origin", productionOrigin)
	}
	clientID := os.Getenv("SELLAPP_CLI_PUBLIC_CLIENT_ID")
	if clientID == "" {
		clientID = ""
	}
	for _, character := range clientID {
		if !((character >= 'a' && character <= 'z') || (character >= 'A' && character <= 'Z') || (character >= '0' && character <= '9') || character == '-' || character == '_') {
			return "", fmt.Errorf("SELLAPP_CLI_PUBLIC_CLIENT_ID must contain only letters, digits, hyphens and underscores")
		}
	}
	if production && clientID == "" {
		return "", fmt.Errorf("production publication requires SELLAPP_CLI_PUBLIC_CLIENT_ID for the verified official sell.app registration")
	}
	return clientID, nil
}
func release(output string, production bool) error {
	clientID, err := releaseRegistration(production)
	if err != nil {
		return err
	}
	origin := productionOrigin
	ldflags := "-buildid= -X github.com/sellapp/sellapp-cli/internal/cli.firstPartyOrigin=" + origin + " -X github.com/sellapp/sellapp-cli/internal/cli.defaultBaseURL=" + origin + "/api"
	if clientID != "" {
		ldflags += " -X github.com/sellapp/sellapp-cli/internal/cli.firstPartyClientID=" + clientID
	}
	files, err := sourceFiles()
	if err != nil {
		return err
	}
	h := sha256.New()
	materials := map[string]string{}
	for _, file := range files {
		h.Write([]byte(file.name))
		h.Write([]byte{0})
		h.Write(file.data)
		h.Write([]byte{0})
		materials[file.name] = sum(file.data)
	}
	sourceDigest := hex.EncodeToString(h.Sum(nil))
	if _, err = command(nil, "mod", "verify"); err != nil {
		return err
	}
	raw, err := command(nil, "list", "-mod=readonly", "-m", "-json", "all")
	if err != nil {
		return err
	}
	decoder := json.NewDecoder(bytes.NewReader(raw))
	modules := []map[string]string{}
	notices := []entry{}
	noticeDigests := map[string]string{}
	for {
		var mod module
		err := decoder.Decode(&mod)
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		if mod.Main {
			continue
		}
		if mod.Replace != nil {
			return fmt.Errorf("replaced dependencies are not permitted in release packages: %s", mod.Path)
		}
		modules = append(modules, map[string]string{"path": mod.Path, "version": mod.Version, "sum": mod.Sum, "goModSum": mod.GoModSum})
		// Only dependencies actually linked into binaries need notices; all modules
		// still appear in the inspectable graph, including build/test dependencies.
		if mod.Dir == "" {
			continue
		}
		children, err := os.ReadDir(mod.Dir)
		if err != nil {
			return err
		}
		for _, child := range children {
			upper := strings.ToUpper(child.Name())
			if child.IsDir() || !(strings.HasPrefix(upper, "LICENSE") || strings.HasPrefix(upper, "COPYING") || strings.HasPrefix(upper, "NOTICE")) {
				continue
			}
			data, err := os.ReadFile(filepath.Join(mod.Dir, child.Name()))
			if err != nil {
				return err
			}
			name := "licenses/" + mod.Path + "@" + mod.Version + "/" + child.Name()
			if _, exists := noticeDigests[name]; exists {
				return fmt.Errorf("duplicate dependency license notice %s", name)
			}
			notices = append(notices, entry{name, data, 0644})
			noticeDigests[name] = sum(data)
		}
	}
	if len(noticeDigests) == 0 {
		return fmt.Errorf("no dependency license notices found")
	}
	if err := os.MkdirAll(output, 0755); err != nil {
		return err
	}
	existing, err := os.ReadDir(output)
	if err != nil {
		return err
	}
	if len(existing) > 0 {
		return fmt.Errorf("output must be empty; refusing to overwrite %s", output)
	}
	temporary, err := os.MkdirTemp("", "sellapp-cli-release-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(temporary)
	artifacts := map[string]string{}
	checksums := []string{}
	for _, target := range targets {
		binaryName := "sellapp"
		extension := ".tar.gz"
		if target[0] == "windows" {
			binaryName += ".exe"
			extension = ".zip"
		}
		binary := filepath.Join(temporary, binaryName)
		if _, err := command([]string{"GOOS=" + target[0], "GOARCH=" + target[1]}, "build", "-mod=readonly", "-trimpath", "-buildvcs=false", "-ldflags="+ldflags, "-o", binary, "./cmd/sellapp"); err != nil {
			return err
		}
		binaryData, err := os.ReadFile(binary)
		if err != nil {
			return err
		}
		info, err := buildinfo.ReadFile(binary)
		if err != nil {
			return err
		}
		metadata, err := jsonBytes(map[string]any{"schemaVersion": 1, "version": version, "repository": repository, "target": target[0] + "/" + target[1], "binarySha256": sum(binaryData), "sourceTreeSha256": sourceDigest, "publicOAuthClientID": clientID, "oauthOrigin": origin, "browserOnboardingConfigured": clientID != "", "buildInfo": info, "dependencies": modules, "materials": materials, "licenseNotices": noticeDigests, "unsigned": true, "claim": "Local reproducible build record; not a signed attestation or SLSA provenance."})
		if err != nil {
			return err
		}
		contents := []entry{{binaryName, binaryData, 0755}, {"build-info.json", metadata, 0644}}
		for _, file := range files {
			if distributable(file.name) || file.name == "internal/catalog/embedding.json" || file.name == "generation-manifest.json" {
				contents = append(contents, file)
			}
		}
		contents = append(contents, notices...)
		archive, err := archiveBytes(contents, target[0] == "windows")
		if err != nil {
			return err
		}
		name := "sellapp_" + version + "_" + target[0] + "_" + target[1] + extension
		if err := os.WriteFile(filepath.Join(output, name), archive, 0644); err != nil {
			return err
		}
		artifacts[name] = sum(archive)
		platformOS, platformCPU := npmTarget(target)
		manifest, err := jsonBytes(map[string]any{"name": "@sell.app/cli-" + platformOS + "-" + platformCPU, "version": version, "description": "SellApp CLI executable for " + platformOS + "/" + platformCPU, "license": "MIT", "repository": map[string]string{"type": "git", "url": "git+https://github.com/" + repository + ".git"}, "os": []string{platformOS}, "cpu": []string{platformCPU}, "files": []string{"bin", "licenses", "LICENSE.txt", "build-info.json"}})
		if err != nil {
			return err
		}
		npmFiles := []entry{{"package.json", manifest, 0644}, {"bin/" + binaryName, binaryData, 0755}, {"build-info.json", metadata, 0644}}
		for _, file := range files {
			if file.name == "LICENSE.txt" {
				npmFiles = append(npmFiles, file)
			}
		}
		npmFiles = append(npmFiles, notices...)
		if err := writeNpm(output, "sellapp-cli-"+platformOS+"-"+platformCPU+"-"+version+".tgz", npmFiles, artifacts); err != nil {
			return err
		}
	}
	npmFiles := []entry{}
	for _, file := range files {
		switch {
		case file.name == "npm/package.json":
			file.name = "package.json"
			npmFiles = append(npmFiles, file)
		case file.name == "npm/launcher.cjs":
			file.name = "bin/sellapp.cjs"
			file.mode = 0755
			npmFiles = append(npmFiles, file)
		case distributable(file.name):
			npmFiles = append(npmFiles, file)
		}
	}
	npmFiles = append(npmFiles, notices...)
	if err := writeNpm(output, "sellapp-cli-"+version+".tgz", npmFiles, artifacts); err != nil {
		return err
	}
	installer, err := os.ReadFile("install.sh")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(output, "install.sh"), installer, 0755); err != nil {
		return err
	}
	artifacts["install.sh"] = sum(installer)
	manifest, err := jsonBytes(map[string]any{"schemaVersion": 2, "version": version, "repository": repository, "releaseTag": "v" + version, "releaseURL": "https://github.com/" + repository + "/releases/tag/v" + version, "sourceTreeSha256": sourceDigest, "publicOAuthClientID": clientID, "oauthOrigin": origin, "browserOnboardingConfigured": clientID != "", "artifacts": artifacts, "unsigned": true, "reproducibility": "Requires identical source, dependency content, and Go toolchain; archive timestamps and build flags are fixed."})
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(output, "release-manifest.json"), manifest, 0644); err != nil {
		return err
	}
	artifacts["release-manifest.json"] = sum(manifest)
	for name, digest := range artifacts {
		checksums = append(checksums, digest+"  "+name)
	}
	sort.Strings(checksums)
	if err := os.WriteFile(filepath.Join(output, "SHA256SUMS"), []byte(strings.Join(checksums, "\n")+"\n"), 0644); err != nil {
		return err
	}
	if err := verifyDirectory(output, production); err != nil {
		return fmt.Errorf("verify newly built release: %w", err)
	}
	fmt.Printf("Built and verified %d unsigned release archives, 7 npm tarballs, and install.sh in %s (source %s)\n", len(targets), output, sourceDigest)
	return nil
}
func distributable(name string) bool {
	return name == "README.md" || name == "LICENSE.txt" || strings.HasPrefix(name, "docs/") || strings.HasPrefix(name, "examples/") || strings.HasPrefix(name, "skills/")
}
func npmTarget(target [2]string) (string, string) {
	platform, architecture := target[0], target[1]
	if platform == "windows" {
		platform = "win32"
	}
	if architecture == "amd64" {
		architecture = "x64"
	}
	return platform, architecture
}
func writeNpm(output, name string, files []entry, artifacts map[string]string) error {
	prefixed := make([]entry, 0, len(files))
	for _, file := range files {
		file.name = "package/" + file.name
		prefixed = append(prefixed, file)
	}
	data, err := archiveBytes(prefixed, false)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(output, name), data, 0644); err != nil {
		return err
	}
	artifacts[name] = sum(data)
	return nil
}
func archiveBytes(files []entry, windows bool) ([]byte, error) {
	files = append([]entry(nil), files...) // Sorting must never mutate a caller-owned or reused slice.
	sort.Slice(files, func(i, j int) bool { return files[i].name < files[j].name })
	var output bytes.Buffer
	if windows {
		writer := zip.NewWriter(&output)
		for _, file := range files {
			header := &zip.FileHeader{Name: file.name, Method: zip.Deflate}
			header.SetMode(file.mode)
			header.SetModTime(epoch)
			item, err := writer.CreateHeader(header)
			if err != nil {
				return nil, err
			}
			if _, err := item.Write(file.data); err != nil {
				return nil, err
			}
		}
		if err := writer.Close(); err != nil {
			return nil, err
		}
	} else {
		compressed := gzip.NewWriter(&output)
		compressed.Header.ModTime = epoch
		compressed.Header.OS = 255
		writer := tar.NewWriter(compressed)
		for _, file := range files {
			if err := writer.WriteHeader(&tar.Header{Name: file.name, Mode: int64(file.mode), Size: int64(len(file.data)), ModTime: epoch, Format: tar.FormatPAX}); err != nil {
				return nil, err
			}
			if _, err := writer.Write(file.data); err != nil {
				return nil, err
			}
		}
		if err := writer.Close(); err != nil {
			return nil, err
		}
		if err := compressed.Close(); err != nil {
			return nil, err
		}
	}
	return output.Bytes(), nil
}
func readArchive(data []byte, windows bool) (map[string][]byte, error) {
	contents := map[string][]byte{}
	add := func(name string, reader io.Reader) error {
		if _, exists := contents[name]; exists || name == "" || strings.HasPrefix(name, "/") || strings.Contains(name, "..") || strings.Contains(name, "\\") || strings.ContainsAny(name, "\r\n\t") {
			return fmt.Errorf("unsafe or repeated archive path %q", name)
		}
		data, err := io.ReadAll(io.LimitReader(reader, (128<<20)+1))
		if err != nil {
			return err
		}
		if len(data) > 128<<20 {
			return fmt.Errorf("oversized archive entry %s", name)
		}
		contents[name] = data
		return nil
	}
	if windows {
		reader, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
		if err != nil {
			return nil, err
		}
		for _, file := range reader.File {
			if !file.Mode().IsRegular() {
				return nil, fmt.Errorf("non-regular archive entry %s", file.Name)
			}
			item, err := file.Open()
			if err != nil {
				return nil, err
			}
			err = add(file.Name, item)
			item.Close()
			if err != nil {
				return nil, err
			}
		}
	} else {
		compressed, err := gzip.NewReader(bytes.NewReader(data))
		if err != nil {
			return nil, err
		}
		defer compressed.Close()
		reader := tar.NewReader(compressed)
		for {
			file, err := reader.Next()
			if err == io.EOF {
				break
			}
			if err != nil {
				return nil, err
			}
			if file.Typeflag != tar.TypeReg {
				return nil, fmt.Errorf("non-regular archive entry %s", file.Name)
			}
			if err = add(file.Name, reader); err != nil {
				return nil, err
			}
		}
	}
	return contents, nil
}
func verifyDirectory(output string, production bool) error {
	sums, err := os.ReadFile(filepath.Join(output, "SHA256SUMS"))
	if err != nil {
		return err
	}
	expected := map[string]bool{"release-manifest.json": true, "install.sh": true, "sellapp-cli-" + version + ".tgz": true}
	for _, target := range targets {
		extension := ".tar.gz"
		if target[0] == "windows" {
			extension = ".zip"
		}
		expected["sellapp_"+version+"_"+target[0]+"_"+target[1]+extension] = true
		platform, cpu := npmTarget(target)
		expected["sellapp-cli-"+platform+"-"+cpu+"-"+version+".tgz"] = true
	}
	seen := map[string]string{}
	artifacts := map[string][]byte{}
	for _, line := range strings.Split(strings.TrimSpace(string(sums)), "\n") {
		digest, name, ok := strings.Cut(line, "  ")
		if !ok || !expected[name] || seen[name] != "" || len(digest) != 64 {
			return fmt.Errorf("invalid checksum entry %q", line)
		}
		data, err := os.ReadFile(filepath.Join(output, name))
		if err != nil {
			return err
		}
		if sum(data) != digest {
			return fmt.Errorf("checksum mismatch: %s", name)
		}
		seen[name] = digest
		artifacts[name] = data
	}
	if len(seen) != len(expected) {
		return fmt.Errorf("incomplete checksum manifest")
	}
	var manifest struct {
		Version, Repository, ReleaseTag, ReleaseURL, SourceTreeSha256, OAuthOrigin, PublicOAuthClientID string
		Artifacts                                                                                       map[string]string
		Unsigned, BrowserOnboardingConfigured                                                           bool
	}
	if err := json.Unmarshal(artifacts["release-manifest.json"], &manifest); err != nil {
		return err
	}
	if manifest.Version != version || manifest.Repository != repository || manifest.ReleaseTag != "v"+version || manifest.ReleaseURL != "https://github.com/"+repository+"/releases/tag/v"+version || !manifest.Unsigned || len(manifest.Artifacts) != len(expected)-1 {
		return fmt.Errorf("invalid release manifest")
	}
	if manifest.OAuthOrigin != productionOrigin || manifest.BrowserOnboardingConfigured != (manifest.PublicOAuthClientID != "") {
		return fmt.Errorf("release manifest must describe production OAuth configuration")
	}
	if production && manifest.PublicOAuthClientID == "" {
		return fmt.Errorf("production publication requires configured official sell.app browser login")
	}
	for name, digest := range manifest.Artifacts {
		if name == "release-manifest.json" || seen[name] != digest {
			return fmt.Errorf("release manifest checksum mismatch: %s", name)
		}
	}
	main, err := readArchive(artifacts["sellapp-cli-"+version+".tgz"], false)
	if err != nil {
		return err
	}
	var mainPackage struct {
		Name, Version        string
		Bin                  map[string]string
		Engines              map[string]string
		OptionalDependencies map[string]string
		Scripts              map[string]string
	}
	if err := json.Unmarshal(main["package/package.json"], &mainPackage); err != nil {
		return err
	}
	if mainPackage.Name != "@sell.app/cli" || mainPackage.Version != version || mainPackage.Engines["node"] != ">=22" || mainPackage.Bin["sellapp"] != "bin/sellapp.cjs" || len(mainPackage.OptionalDependencies) != len(targets) || len(mainPackage.Scripts) != 0 {
		return fmt.Errorf("invalid main npm package manifest")
	}
	requiredGuidance := []string{"README.md", "LICENSE.txt", "docs/usage.md", "docs/contributing.md", "skills/sellapp/SKILL.md", "skills/sellapp/references/connect-store.md", "skills/sellapp/references/product-variant.md", "skills/sellapp/references/checkout.md", "skills/sellapp/references/orders-fulfillment-refunds.md", "skills/sellapp/references/subscriptions.md", "skills/sellapp/references/customer-support.md", "skills/sellapp/references/webhooks.md", "skills/sellapp/references/exports.md"}
	for _, name := range append(append([]string{}, requiredGuidance...), "bin/sellapp.cjs") {
		if len(main["package/"+name]) == 0 {
			return fmt.Errorf("missing %s in main npm package", name)
		}
	}
	for _, target := range targets {
		windows := target[0] == "windows"
		extension := ".tar.gz"
		binaryName := "sellapp"
		if windows {
			extension = ".zip"
			binaryName += ".exe"
		}
		name := "sellapp_" + version + "_" + target[0] + "_" + target[1] + extension
		contents, err := readArchive(artifacts[name], windows)
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		for _, required := range append(append([]string{}, requiredGuidance...), binaryName, "build-info.json", "internal/catalog/embedding.json") {
			if len(contents[required]) == 0 {
				return fmt.Errorf("missing %s in %s", required, name)
			}
		}
		var metadata struct {
			Version, Target, BinarySha256, SourceTreeSha256, OAuthOrigin, PublicOAuthClientID string
			BrowserOnboardingConfigured                                                       bool
			BuildInfo                                                                         *debug.BuildInfo
			Unsigned                                                                          bool
			Dependencies                                                                      []map[string]string
			Materials                                                                         map[string]string
			LicenseNotices                                                                    map[string]string
		}
		if err = json.Unmarshal(contents["build-info.json"], &metadata); err != nil {
			return err
		}
		if metadata.Version != version || metadata.Target != target[0]+"/"+target[1] || metadata.SourceTreeSha256 != manifest.SourceTreeSha256 || !metadata.Unsigned || metadata.BinarySha256 != sum(contents[binaryName]) || len(metadata.Dependencies) == 0 || len(metadata.Materials) == 0 {
			return fmt.Errorf("invalid build metadata in %s", name)
		}
		if metadata.OAuthOrigin != manifest.OAuthOrigin || metadata.PublicOAuthClientID != manifest.PublicOAuthClientID || metadata.BrowserOnboardingConfigured != manifest.BrowserOnboardingConfigured {
			return fmt.Errorf("OAuth metadata differs from release manifest in %s", name)
		}
		actualInfo, err := inspectBinary(bytes.NewReader(contents[binaryName]))
		if err != nil {
			return fmt.Errorf("invalid executable in %s: %w", name, err)
		}
		actualJSON, err := jsonBytes(actualInfo)
		if err != nil {
			return err
		}
		recordedJSON, err := jsonBytes(metadata.BuildInfo)
		if err != nil {
			return err
		}
		if !bytes.Equal(actualJSON, recordedJSON) {
			return fmt.Errorf("recorded build information differs from executable in %s", name)
		}
		settings := map[string]string{}
		for _, setting := range actualInfo.Settings {
			settings[setting.Key] = setting.Value
		}
		if settings["GOOS"] != target[0] || settings["GOARCH"] != target[1] {
			return fmt.Errorf("executable target differs from archive in %s", name)
		}
		// Go omits linker flags from build information with -trimpath. The builder
		// enforces the origin; metadata consistency is not proof of runtime behavior.
		if len(metadata.LicenseNotices) == 0 {
			return fmt.Errorf("missing dependency license manifest in %s", name)
		}
		seenNotices := 0
		for path, data := range contents {
			if !strings.HasPrefix(path, "licenses/") {
				continue
			}
			seenNotices++
			digest, ok := metadata.LicenseNotices[path]
			if !ok || digest != sum(data) {
				return fmt.Errorf("dependency license notice checksum mismatch for %s in %s", path, name)
			}
		}
		if seenNotices != len(metadata.LicenseNotices) {
			return fmt.Errorf("dependency license notice count mismatch in %s", name)
		}
		platform, cpu := npmTarget(target)
		packageName := "@sell.app/cli-" + platform + "-" + cpu
		if mainPackage.OptionalDependencies[packageName] != version {
			return fmt.Errorf("missing exact optional dependency %s", packageName)
		}
		npm, err := readArchive(artifacts["sellapp-cli-"+platform+"-"+cpu+"-"+version+".tgz"], false)
		if err != nil {
			return err
		}
		var pkg struct {
			Name, Version string
			OS, CPU       []string
			Scripts       map[string]string
		}
		if err := json.Unmarshal(npm["package/package.json"], &pkg); err != nil {
			return err
		}
		if pkg.Name != packageName || pkg.Version != version || len(pkg.OS) != 1 || pkg.OS[0] != platform || len(pkg.CPU) != 1 || pkg.CPU[0] != cpu || len(pkg.Scripts) != 0 {
			return fmt.Errorf("invalid npm platform manifest %s", packageName)
		}
		if !bytes.Equal(npm["package/bin/"+binaryName], contents[binaryName]) || !bytes.Equal(npm["package/build-info.json"], contents["build-info.json"]) {
			return fmt.Errorf("npm binary or build metadata differs from archive for %s", packageName)
		}
		for _, required := range requiredGuidance {
			if !bytes.Equal(main["package/"+required], contents[required]) {
				return fmt.Errorf("npm guidance differs from archive: %s", required)
			}
		}
		for path, digest := range metadata.LicenseNotices {
			if sum(npm["package/"+path]) != digest || sum(main["package/"+path]) != digest {
				return fmt.Errorf("missing or altered npm license %s", path)
			}
		}
	}
	return nil
}
