// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"
	"time"

	sdk "github.com/sellapp/sellapp-cli/internal/sdk"
	"github.com/spf13/cobra"
)

func bodyFieldChoices(schema map[string]any) []string {
	choices := []string{}
	if values, ok := schema["enum"].([]any); ok {
		for _, value := range values {
			if value != nil {
				choices = append(choices, fmt.Sprint(value))
			}
		}
	}
	for _, key := range []string{"oneOf", "anyOf"} {
		if variants, ok := schema[key].([]any); ok {
			for _, variant := range variants {
				if child, ok := variant.(map[string]any); ok {
					choices = append(choices, bodyFieldChoices(child)...)
				}
			}
		}
	}
	return choices
}

func configureAdapter(cmd *cobra.Command, cfg *Config, entry CatalogEntry) {
	var schema, useStore bool
	cmd.Flags().BoolVar(&schema, "schema", false, "print this command schema without authentication or execution")
	if entry.OperationID == "createStore" {
		cmd.Flags().BoolVar(&useStore, "use", false, "select the created store in the current profile")
	}
	parameterValues := map[string]*string{}
	bodyValues := map[string]*string{}
	for _, parameter := range entry.Parameters {
		value := ""
		parameterValues[parameter.Name] = &value
		description := parameter.Description
		if description == "" {
			description = fmt.Sprintf("%s %s parameter", parameter.Location, parameter.Name)
		}
		if parameter.Required {
			description = "Required. " + description
		}
		cmd.Flags().StringVar(&value, parameter.Flag, "", description)
		if parameter.Positional {
			_ = cmd.Flags().MarkHidden(parameter.Flag)
		}
		if parameter.ValueKind == "boolean" {
			cmd.Flags().Lookup(parameter.Flag).NoOptDefVal = "true"
		}
		// Required inputs are validated in RunE so interactive terminals may prompt.
	}

	body := ""
	assignments := []string{}
	uploads := []string{}
	if entry.Body != nil {
		cmd.Flags().StringVar(&body, "body", "", "JSON object, @file, or - for stdin")
		cmd.Flags().StringArrayVar(&assignments, "set", nil, "set a request field as FIELD=JSON (repeatable)")
		for _, field := range entry.Body.Fields {
			if !field.Binary && !field.BinaryArray {
				value := ""
				bodyValues[field.Name] = &value
				description := field.Description
				if field.Required {
					description = "Required. " + description
				}
				choices := bodyFieldChoices(field.Schema)
				if len(choices) > 0 {
					description += " Choices: " + strings.Join(choices, ", ")
				}
				cmd.Flags().StringVar(&value, field.Flag, "", description)
				if len(choices) > 0 {
					_ = cmd.RegisterFlagCompletionFunc(field.Flag, func(_ *cobra.Command, _ []string, _ string) ([]string, cobra.ShellCompDirective) {
						return choices, cobra.ShellCompDirectiveNoFileComp
					})
				}
				if nonNullFlagSchema(field.Schema)["type"] == "boolean" {
					cmd.Flags().Lookup(field.Flag).NoOptDefVal = "true"
				}
			}
		}
		for _, field := range entry.Body.Fields {
			if field.Binary || field.BinaryArray {
				cmd.Flags().StringArrayVar(&uploads, "upload", nil, "attach a binary field as FIELD=PATH (repeatable; PATH may be -)")
				break
			}
		}
	}

	idempotencyKey := ""
	if entry.IdempotencyKey {
		cmd.Flags().StringVar(&idempotencyKey, "idempotency-key", "", "idempotency key")
	}
	autoPage := false
	maxItems := 0
	maxPages := 0
	if entry.Paginated {
		cmd.Flags().BoolVar(&autoPage, "all", false, "automatically retrieve every page")
		cmd.Flags().IntVar(&maxItems, "max-items", 0, "maximum returned items; zero means unlimited")
		cmd.Flags().IntVar(&maxPages, "max-pages", 0, "maximum fetched pages; zero means unlimited")
	}

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if schema {
			return writeMetadataResult(cfg, entry)
		}
		for _, parameter := range entry.Parameters {
			if parameter.Positional && len(args) > 0 {
				if cmd.Flags().Changed(parameter.Flag) {
					return &UsageError{Message: "provide ID either positionally or with --" + parameter.Flag}
				}
				if err := cmd.Flags().Set(parameter.Flag, args[0]); err != nil {
					return err
				}
			}
		}
		if entry.Body != nil {
			for _, field := range entry.Body.Fields {
				if value := bodyValues[field.Name]; value != nil && cmd.Flags().Changed(field.Flag) {
					raw, err := bodyFlagJSON(field, *value)
					if err != nil {
						return err
					}
					assignments = append(assignments, field.Name+"="+raw)
				}
			}
		}
		if body == "-" {
			cfg.NoInteractive = true
		}
		for _, upload := range uploads {
			if strings.HasSuffix(upload, "=-") {
				if body == "-" {
					return &UsageError{Message: "stdin cannot supply both body and upload"}
				}
				cfg.NoInteractive = true
			}
		}
		if maxItems < 0 || maxPages < 0 {
			return &UsageError{Message: "--max-items and --max-pages cannot be negative"}
		}
		if err := prepareInvocation(cmd, cfg, entry, parameterValues, &body, &assignments, uploads); err != nil {
			return err
		}
		if err := resolveProfileConfig(cfg); err != nil {
			return err
		}
		if err := confirmWrite(cmd, cfg, entry); err != nil {
			return err
		}
		if entry.IdempotencyKey && idempotencyKey == "" {
			var err error
			idempotencyKey, err = invocationIdempotencyKey(entry)
			if err != nil {
				return err
			}
		}
		started := time.Now()
		invocation := sdk.CLIInvocation{
			Path: map[string]string{}, Query: map[string]string{}, Headers: map[string]string{}, Cookies: map[string]string{},
			All: autoPage, MaxItems: maxItems, MaxPages: maxPages,
		}
		for _, parameter := range entry.Parameters {
			if !cmd.Flags().Changed(parameter.Flag) {
				continue
			}
			value := *parameterValues[parameter.Name]
			switch parameter.Location {
			case "path":
				invocation.Path[parameter.Name] = value
			case "query":
				invocation.Query[parameter.Name] = value
			case "header":
				invocation.Headers[parameter.Name] = value
			case "cookie":
				invocation.Cookies[parameter.Name] = value
			default:
				return &UsageError{Message: "unsupported parameter location " + parameter.Location}
			}
		}
		if entry.Body != nil {
			if entry.Body.Required && body == "" && len(assignments) == 0 && len(uploads) == 0 {
				return &UsageError{Message: "request body is required; use --body, --set, or --upload"}
			}
			parsed, err := readJSONObject(body, assignments, cmd.InOrStdin())
			if err != nil {
				return err
			}
			invocation.Body = parsed
			if body == "" && len(assignments) == 0 && len(uploads) == 0 {
				invocation.Body = nil
			}
			invocation.Files, err = readUploads(uploads, cmd.InOrStdin())
			if err != nil {
				return err
			}
		}
		cfg.dryRunResponse = entry.ResponseFixture
		cfg.dryRunAPIKey = entry.APIKeyOnly
		result, err := sdk.ExecuteCLI(cmd.Context(), cfg.client(), entry.OperationKey, invocation, requestOptions(idempotencyKey)...)
		writeAudit(cfg, entry.OperationID, started, err)
		if err != nil {
			return err
		}
		if entry.OperationID == "createStore" {
			return finishStoreCreation(cfg, result, useStore)
		}
		return cfg.writeResult(result)
	}
}
