// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"github.com/spf13/cobra"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func agentTestChdir(t *testing.T, path string) {
	t.Helper()
	previous, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err = os.Chdir(path); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := os.Chdir(previous); err != nil {
			t.Fatal(err)
		}
	})
}
func TestSkillInstallUpdateConflictAndForce(t *testing.T) {
	target := filepath.Join(t.TempDir(), "skill with spaces")
	files := map[string]string{"SKILL.md": "one", "references/guide.md": "guide"}
	if err := installSkillTree(target, files, false); err != nil {
		t.Fatal(err)
	}
	if err := installSkillTree(target, files, false); err != nil {
		t.Fatal(err)
	}
	files["SKILL.md"] = "two"
	if err := installSkillTree(target, files, false); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(target, "references", "guide.md")
	if err := os.WriteFile(path, []byte("my edits"), 0600); err != nil {
		t.Fatal(err)
	}
	files["SKILL.md"] = "three"
	if err := installSkillTree(target, files, false); err == nil {
		t.Fatal("modified file overwritten")
	}
	data, _ := os.ReadFile(filepath.Join(target, "SKILL.md"))
	if string(data) != "two" {
		t.Fatal("conflict preflight changed another file")
	}
	if err := installSkillTree(target, files, true); err != nil {
		t.Fatal(err)
	}
	data, _ = os.ReadFile(path)
	if string(data) != "guide" {
		t.Fatal("force did not replace generated file")
	}
	if err := os.WriteFile(filepath.Join(target, "notes.txt"), []byte("mine"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := installSkillTree(target, files, true); err != nil {
		t.Fatal(err)
	}
	data, _ = os.ReadFile(filepath.Join(target, "notes.txt"))
	if string(data) != "mine" {
		t.Fatal("unmanaged file changed")
	}
}
func TestSkillRejectsUnknownOwnedFileAndLinks(t *testing.T) {
	target := t.TempDir()
	path := filepath.Join(target, "SKILL.md")
	if err := os.WriteFile(path, []byte("mine"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := installSkillTree(target, map[string]string{"SKILL.md": "generated"}, false); err == nil {
		t.Fatal("unowned file overwritten")
	}
	if err := installSkillTree(target, map[string]string{"../outside": "bad"}, true); err == nil {
		t.Fatal("traversal accepted")
	}
	if runtime.GOOS == "windows" {
		t.Skip("symlink creation needs Windows developer mode")
	}
	linked := filepath.Join(t.TempDir(), "linked")
	if err := os.Symlink(target, linked); err != nil {
		t.Fatal(err)
	}
	if err := installSkillTree(linked, map[string]string{"SKILL.md": "bad"}, true); err == nil {
		t.Fatal("symlink accepted")
	}
}
func TestSkillsRequireScopeAndSupportDryRun(t *testing.T) {
	var out bytes.Buffer
	cfg := &Config{Output: "json", NoInteractive: true, Stdout: &out, Stderr: &out}
	cmd := skillsCommand(cfg)
	cmd.SetArgs([]string{"add"})
	if err := cmd.Execute(); err == nil {
		t.Fatal("implicit noninteractive scope")
	}
	cfg.DryRun = true
	cmd = skillsCommand(cfg)
	cmd.SetArgs([]string{"add", "--project"})
	if err := cmd.Execute(); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "\"saved\": false") {
		t.Fatal(out.String())
	}
	cmd = skillsCommand(cfg)
	cmd.SetArgs([]string{"add", "--project", "--global"})
	if err := cmd.Execute(); err == nil {
		t.Fatal("ambiguous scope")
	}
}
func TestSkillInstallTargetsClientAndScope(t *testing.T) {
	isolatedHome := credentialTestHome(t)
	t.Setenv("USERPROFILE", isolatedHome)
	project := t.TempDir()
	agentTestChdir(t, project)
	t.Setenv("CLAUDE_CONFIG_DIR", "")
	home, err := os.UserHomeDir()
	if err != nil {
		t.Fatal(err)
	}
	for _, fixture := range []struct{ client, directory string }{{"codex", ".agents"}, {"claude-code", ".claude"}, {"cursor", ".cursor"}} {
		for _, scope := range []string{"project", "global"} {
			base := project
			if scope == "global" {
				base = home
			}
			target := filepath.Join(base, fixture.directory, "skills", "sellapp")
			for _, dryRun := range []bool{true, false, false} {
				var out bytes.Buffer
				cfg := &Config{Output: "json", NoInteractive: true, DryRun: dryRun, Stdout: &out, Stderr: &out}
				cmd := skillsCommand(cfg)
				cmd.SetArgs([]string{"add", "--client", fixture.client, "--" + scope})
				if err = cmd.Execute(); err != nil {
					t.Fatal(err)
				}
				var result map[string]any
				if err = json.Unmarshal(out.Bytes(), &result); err != nil {
					t.Fatal(err)
				}
				if result["directory"] != target || result["client"] != fixture.client {
					t.Fatal("wrong client destination", out.String())
				}
				if dryRun {
					if _, err = os.Stat(target); !os.IsNotExist(err) {
						t.Fatal("dry run wrote the skill", err)
					}
					continue
				}
				for name, want := range embeddedSkillFiles {
					got, err := os.ReadFile(filepath.Join(target, filepath.FromSlash(name)))
					if err != nil || string(got) != want {
						t.Fatalf("missing or changed skill file %s: %v", name, err)
					}
				}
			}
		}
	}
	custom := filepath.Join(t.TempDir(), "custom claude")
	t.Setenv("CLAUDE_CONFIG_DIR", custom)
	target, err := skillDirectory("claude-code", "user")
	if err != nil || target != filepath.Join(custom, "skills", "sellapp") {
		t.Fatal("ignored Claude directory", target, err)
	}
	target, err = skillDirectory("claude-code", "project")
	if err != nil || target != filepath.Join(project, ".claude", "skills", "sellapp") {
		t.Fatal("user override changed project scope", target, err)
	}
	if _, err = skillDirectory("unknown", "project"); err == nil {
		t.Fatal("unknown client accepted")
	}
}
func TestEmbeddedSkillsMatchDistribution(t *testing.T) {
	for name, content := range embeddedSkillFiles {
		data, err := os.ReadFile(filepath.Join("..", "..", "skills", "sellapp", filepath.FromSlash(name)))
		if err != nil {
			t.Fatal(err)
		}
		if string(data) != content {
			t.Fatalf("embedded drift: %s", name)
		}
	}
	guide, err := os.ReadFile(filepath.Join("..", "..", "docs", "agent-skill.md"))
	if err != nil || string(guide) != embeddedAgentGuide {
		t.Fatal("guide drift", err)
	}
}
func TestCursorMCPRegistrationPreservesUnrelatedContent(t *testing.T) {
	agentTestChdir(t, t.TempDir())
	path := filepath.Join(".cursor", "mcp.json")
	if err := os.Mkdir(".cursor", 0700); err != nil {
		t.Fatal(err)
	}
	original := `{"unrelated":{"setting":true},"mcpServers":{"other":{"command":"keep","args":["value"]}}}`
	if err := os.WriteFile(path, []byte(original), 0600); err != nil {
		t.Fatal(err)
	}
	executable := filepath.Join(t.TempDir(), "sellapp with spaces")
	changed, err := registerLocalMCP(context.Background(), "cursor", "project", executable)
	if err != nil || !changed {
		t.Fatal(changed, err)
	}
	changed, err = registerLocalMCP(context.Background(), "cursor", "project", executable)
	if err != nil || changed {
		t.Fatal(changed, err)
	}
	doc, servers, err := readJSONMCP(path)
	if err != nil || string(doc["unrelated"]) != "{\n    \"setting\": true\n  }" {
		var value map[string]bool
		_ = json.Unmarshal(doc["unrelated"], &value)
		if err != nil || !value["setting"] {
			t.Fatal("lost setting", err)
		}
	}
	if !strings.Contains(string(servers["other"]), "keep") {
		t.Fatal("lost another server")
	}
	if strings.Contains(string(servers["sellapp"]), "allow-writes") {
		t.Fatal("unexpected local write flag")
	}
	before, _ := os.ReadFile(path)
	if _, err = registerLocalMCP(context.Background(), "cursor", "project", executable+"different"); err == nil {
		t.Fatal("conflicting entry overwritten")
	}
	after, _ := os.ReadFile(path)
	if !bytes.Equal(before, after) {
		t.Fatal("conflict changed configuration")
	}
}
func TestMCPSetupReportsHostedAuthorization(t *testing.T) {
	agentTestChdir(t, t.TempDir())
	for _, dryRun := range []bool{true, false} {
		var out bytes.Buffer
		cfg := &Config{Output: "json", NoInteractive: true, DryRun: dryRun, Stdout: &out, Stderr: &out}
		cmd := mcpSetupCommand(cfg)
		cmd.SetArgs([]string{"--client", "cursor", "--project"})
		if err := cmd.Execute(); err != nil {
			t.Fatal(err)
		}
		var result map[string]any
		if err := json.Unmarshal(out.Bytes(), &result); err != nil {
			t.Fatal(err)
		}
		if result["permission_source"] != "hosted" || result["write_policy"] != "current permissions and consequential confirmation" {
			t.Fatal("missing hosted authorization policy", out.String())
		}
		if _, ok := result["writes_enabled"]; ok {
			t.Fatal("registration must not claim writes are disabled")
		}
	}
}
func TestMCPRegistrationRejectsInvalidConfiguration(t *testing.T) {
	agentTestChdir(t, t.TempDir())
	if err := os.Mkdir(".cursor", 0700); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(".cursor", "mcp.json")
	for _, value := range []string{"not-json", "null", `{"mcpServers":null}`, `{"mcpServers":[]}`, `{"mcpServers":{},"mcpServers":{"lost":{}}}`, `{"unrelated":{"same":1,"same":2}}`} {
		if err := os.WriteFile(path, []byte(value), 0600); err != nil {
			t.Fatal(err)
		}
		if _, err := registerLocalMCP(context.Background(), "cursor", "project", "sellapp"); err == nil {
			t.Fatal("accepted invalid config", value)
		}
		after, _ := os.ReadFile(path)
		if string(after) != value {
			t.Fatal("invalid config changed")
		}
	}
}
func TestAgentSetupRejectsHardlinks(t *testing.T) {
	target := t.TempDir()
	source := filepath.Join(target, "original.json")
	linked := filepath.Join(target, "linked.json")
	if err := os.WriteFile(source, []byte("{}"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.Link(source, linked); err != nil {
		t.Skipf("filesystem does not support fixture hardlinks: %v", err)
	}
	if err := safeLocalPath(linked); err == nil {
		t.Fatal("hardlink accepted")
	}
	if err := atomicAgentWrite(linked, []byte("changed")); err == nil {
		t.Fatal("hardlink replaced")
	}
	data, _ := os.ReadFile(source)
	if string(data) != "{}" {
		t.Fatal("source changed")
	}
}
func TestMCPMatchingRejectsUnexpectedArgumentsAndCredentials(t *testing.T) {
	wanted := localMCPEntry{"/local/sellapp", []string{"mcp", "--no-interactive"}}
	for _, value := range []string{`{"command":"/local/sellapp","args":["mcp","--allow-writes","--yes"]}`, `{"command":"/local/sellapp","args":["mcp","--no-interactive"],"env":{"SELLAPP_API_KEY":"secret"}}`, `{"command":"/local/sellapp","args":["mcp","--no-interactive"],"url":"https://other.invalid"}`} {
		if matchingMCPEntry(json.RawMessage(value), wanted) {
			t.Fatal("unsafe registration accepted")
		}
	}
}
func TestMCPInitializeRequiresValidProfileWithoutSecretOutput(t *testing.T) {
	credentialTestHome(t)
	path, _ := profilePath()
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("corrupt-secret-token"), 0600); err != nil {
		t.Fatal(err)
	}
	var output, diagnostics bytes.Buffer
	cfg := &Config{Output: "json", Stdout: &output, Stderr: &diagnostics}
	err := serveMCP(context.Background(), cfg, "compact")
	if err == nil {
		t.Fatal("corrupt profile accepted")
	}
	if output.Len() != 0 || strings.Contains(err.Error(), "corrupt-secret-token") || strings.Contains(diagnostics.String(), "corrupt-secret-token") {
		t.Fatal("protocol/diagnostic output exposed profile content")
	}
}
func TestPresentationSilentWithoutInteractiveStreams(t *testing.T) {
	var out, stderr bytes.Buffer
	for _, format := range []string{"json", "jsonl", "yaml", "table"} {
		cfg := &Config{Output: format, Stdout: &out, Stderr: &stderr}
		presentStage(&cobra.Command{}, cfg, "saving access")
		if interactivePresentation(&cobra.Command{}, cfg) {
			t.Fatal("interactive without terminal")
		}
	}
	if out.Len() != 0 || stderr.Len() != 0 {
		t.Fatal("contaminated output")
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := promptLineContext(ctx, "value"); err == nil {
		t.Fatal("cancellation ignored")
	}
}
