// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/spf13/cobra"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"time"
)

type skillManifest struct {
	Version int               `json:"version"`
	Files   map[string]string `json:"files"`
}

func contentHash(data []byte) string { sum := sha256.Sum256(data); return hex.EncodeToString(sum[:]) }
func safeLocalPath(path string) error {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return err
	}
	for current := absolute; ; current = filepath.Dir(current) {
		info, err := os.Lstat(current)
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err == nil {
			if info.Mode()&os.ModeSymlink != 0 {
				return fmt.Errorf("refusing linked path %s", current)
			}
			if !info.IsDir() && !info.Mode().IsRegular() {
				return fmt.Errorf("refusing nonregular path %s", current)
			}
			if info.Mode().IsRegular() {
				linked, linkErr := agentFileHasLinks(current, info)
				if linkErr != nil {
					return linkErr
				}
				if linked {
					return fmt.Errorf("refusing hard-linked file %s", current)
				}
			}
		}
		parent := filepath.Dir(current)
		if parent == current {
			break
		}
	}
	return nil
}
func atomicAgentWrite(path string, data []byte) error {
	if err := safeLocalPath(path); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	file, err := os.CreateTemp(filepath.Dir(path), ".sellapp-*")
	if err != nil {
		return err
	}
	name := file.Name()
	defer os.Remove(name)
	if err = file.Chmod(0600); err == nil {
		_, err = file.Write(data)
	}
	if err == nil {
		err = file.Sync()
	}
	closeErr := file.Close()
	if err != nil {
		return err
	}
	if closeErr != nil {
		return closeErr
	}
	return os.Rename(name, path)
}
func withAgentLock(path string, fn func() error) error {
	if err := safeLocalPath(path); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	lock, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		return fmt.Errorf("setup is already running or its lock remains at %s; check for another process before removing the lock: %w", path, err)
	}
	defer os.Remove(path)
	if err = lock.Close(); err != nil {
		return err
	}
	return fn()
}
func installSkillTree(target string, files map[string]string, force bool) error {
	if err := safeLocalPath(target); err != nil {
		return err
	}
	return withAgentLock(filepath.Join(target, ".sellapp-install.lock"), func() error {
		manifestPath := filepath.Join(target, ".sellapp-generated.json")
		if err := safeLocalPath(manifestPath); err != nil {
			return err
		}
		manifest := skillManifest{Version: 1, Files: map[string]string{}}
		data, err := os.ReadFile(manifestPath)
		if err == nil {
			if err = uniqueJSON(data); err != nil {
				return errors.New("invalid skill ownership manifest; restore it before updating")
			}
			if err = json.Unmarshal(data, &manifest); err != nil || manifest.Version != 1 || manifest.Files == nil {
				return errors.New("invalid skill ownership manifest; restore it before updating")
			}
		} else if !errors.Is(err, os.ErrNotExist) {
			return err
		}
		names := make([]string, 0, len(files))
		for name := range files {
			if name == "" || filepath.IsAbs(name) || filepath.Clean(filepath.FromSlash(name)) != filepath.FromSlash(name) || strings.HasPrefix(name, ".") || strings.Contains(name, "\\") {
				return errors.New("invalid generated skill path")
			}
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			path := filepath.Join(target, filepath.FromSlash(name))
			if err := safeLocalPath(path); err != nil {
				return err
			}
			existing, err := os.ReadFile(path)
			if errors.Is(err, os.ErrNotExist) {
				continue
			}
			if err != nil {
				return err
			}
			hash := contentHash(existing)
			if hash != contentHash([]byte(files[name])) && hash != manifest.Files[name] && !force {
				return fmt.Errorf("skill file %s has local changes; keep them or rerun with --force", path)
			}
		}
		next := skillManifest{Version: 1, Files: map[string]string{}}
		for _, name := range names {
			content := []byte(files[name])
			path := filepath.Join(target, filepath.FromSlash(name))
			next.Files[name] = contentHash(content)
			existing, err := os.ReadFile(path)
			if err == nil && bytes.Equal(existing, content) {
				continue
			}
			if err = atomicAgentWrite(path, content); err != nil {
				return err
			}
		}
		data, err = json.MarshalIndent(next, "", "  ")
		if err != nil {
			return err
		}
		return atomicAgentWrite(manifestPath, append(data, '\n'))
	})
}
func setupScope(cmd *cobra.Command, cfg *Config, global, project bool) (string, error) {
	if global && project {
		return "", &UsageError{Message: "choose only one of --global or --project"}
	}
	if global {
		return "user", nil
	}
	if project {
		return "project", nil
	}
	if !interactivePresentation(cmd, cfg) {
		return "", &UsageError{Message: "choose --global for your user or --project for the current directory"}
	}
	return promptChoice(cmd, cfg, "Install scope", []string{"user", "project"}, "")
}
func scopeDirectory(scope string) (string, error) {
	if scope == "user" {
		return os.UserHomeDir()
	}
	if scope == "project" {
		return os.Getwd()
	}
	return "", &UsageError{Message: "scope must be user or project"}
}
func skillDirectory(client, scope string) (string, error) {
	base, err := scopeDirectory(scope)
	if err != nil {
		return "", err
	}
	directory := ".agents"
	switch client {
	case "codex":
	case "claude-code":
		directory = ".claude"
		if scope == "user" {
			if custom := os.Getenv("CLAUDE_CONFIG_DIR"); custom != "" {
				return filepath.Join(custom, "skills", "sellapp"), nil
			}
		}
	case "cursor":
		directory = ".cursor"
	default:
		return "", &UsageError{Message: "--client must be codex, claude-code, or cursor"}
	}
	return filepath.Join(base, directory, "skills", "sellapp"), nil
}
func skillsCommand(cfg *Config) *cobra.Command {
	root := &cobra.Command{Use: "skills", Short: "Install the bundled SellApp agent skill"}
	var global, project, force bool
	var client string
	add := &cobra.Command{Use: "add", Args: cobra.NoArgs, Short: "Install the skill in your agent client's skill directory", RunE: func(cmd *cobra.Command, _ []string) error {
		scope, err := setupScope(cmd, cfg, global, project)
		if err != nil {
			return err
		}
		target, err := skillDirectory(client, scope)
		if err != nil {
			return err
		}
		if cfg.DryRun {
			return writeFormattedResult(cfg, map[string]any{"client": client, "directory": target, "scope": scope, "saved": false, "contacted_network": false})
		}
		if err = installSkillTree(target, embeddedSkillFiles, force); err != nil {
			return err
		}
		return writeFormattedResult(cfg, map[string]any{"client": client, "directory": target, "scope": scope, "saved": true, "files": len(embeddedSkillFiles), "next": "Start a new agent session and select the sellapp skill. If it is missing, check that the client uses the reported directory and trusts the project."})
	}}
	add.Flags().StringVar(&client, "client", "codex", "codex (.agents), claude-code (.claude), or cursor (.cursor)")
	add.Flags().BoolVar(&global, "global", false, "install for your user")
	add.Flags().BoolVar(&project, "project", false, "install in the current directory")
	add.Flags().BoolVar(&force, "force", false, "replace modified generated skill files")
	root.AddCommand(add)
	return root
}

type localMCPEntry struct {
	Command string   `json:"command"`
	Args    []string `json:"args"`
}

func mcpSetupCommand(cfg *Config) *cobra.Command {
	var client string
	var global, project bool
	cmd := &cobra.Command{Use: "add", Args: cobra.NoArgs, Short: "Register the hosted MCP bridge in an agent client", RunE: func(cmd *cobra.Command, _ []string) error {
		scope, err := setupScope(cmd, cfg, global, project)
		if err != nil {
			return err
		}
		if err = validMCPClient(client); err != nil {
			return err
		}
		executable, err := localSellAppExecutable()
		if err != nil {
			return err
		}
		if cfg.DryRun {
			return writeFormattedResult(cfg, map[string]any{"client": client, "scope": scope, "command": executable, "args": []string{"mcp", "--no-interactive"}, "saved": false, "permission_source": "hosted", "write_policy": "current permissions and consequential confirmation"})
		}
		changed, err := registerLocalMCP(cmd.Context(), client, scope, executable)
		if err != nil {
			return err
		}
		return writeFormattedResult(cfg, map[string]any{"client": client, "scope": scope, "registered": true, "changed": changed, "permission_source": "hosted", "write_policy": "current permissions and consequential confirmation", "next": "Restart the client, then run sellapp mcp doctor with the same --client and scope flags. Project settings may require the client's trust approval."})
	}}
	cmd.Flags().StringVar(&client, "client", "", "codex, claude-code, or cursor")
	cmd.Flags().BoolVar(&global, "global", false, "register for your user")
	cmd.Flags().BoolVar(&project, "project", false, "register for the current directory")
	return cmd
}
func validMCPClient(client string) error {
	switch client {
	case "codex", "claude-code", "cursor":
		return nil
	}
	return &UsageError{Message: "--client must be codex, claude-code, or cursor", Suggestions: []string{"For another client, register the local sellapp executable with arguments mcp --no-interactive using stdio. The bridge uses the selected OAuth profile."}}
}
func localSellAppExecutable() (string, error) {
	path, err := os.Executable()
	if err != nil {
		return "", err
	}
	return filepath.EvalSymlinks(path)
}
func mcpConfigurationPath(client, scope string) (string, error) {
	base, err := scopeDirectory(scope)
	if err != nil {
		return "", err
	}
	switch client {
	case "cursor":
		return filepath.Join(base, ".cursor", "mcp.json"), nil
	case "claude-code":
		if scope == "project" {
			return filepath.Join(base, ".mcp.json"), nil
		}
		if root := os.Getenv("CLAUDE_CONFIG_DIR"); root != "" {
			return filepath.Join(root, ".claude.json"), nil
		}
		return filepath.Join(base, ".claude.json"), nil
	case "codex":
		if scope == "user" {
			if root := os.Getenv("CODEX_HOME"); root != "" {
				return filepath.Join(root, "config.toml"), nil
			}
		}
		return filepath.Join(base, ".codex", "config.toml"), nil
	}
	return "", validMCPClient(client)
}
func clientEnvironment(client, scope, path string) []string {
	env := os.Environ()
	if client == "codex" {
		next := []string{}
		for _, value := range env {
			if !strings.HasPrefix(value, "CODEX_HOME=") {
				next = append(next, value)
			}
		}
		env = append(next, "CODEX_HOME="+filepath.Dir(path))
	}
	return env
}
func runMCPClient(ctx context.Context, client, scope, path string, args ...string) ([]byte, error) {
	name := client
	if name == "claude-code" {
		name = "claude"
	}
	binary, err := exec.LookPath(name)
	if err != nil {
		return nil, fmt.Errorf("%s executable unavailable; install that client or configure sellapp mcp --no-interactive manually", name)
	}
	timeout, cancel := context.WithTimeout(ctx, 15*time.Second)
	defer cancel()
	cmd := exec.CommandContext(timeout, binary, args...)
	cmd.Env = clientEnvironment(client, scope, path)
	stderr := agentLimitedBuffer{limit: 1 << 20}
	stdout := agentLimitedBuffer{limit: 1 << 20}
	cmd.Stderr = &stderr
	cmd.Stdout = &stdout
	err = cmd.Run()
	output := stdout.Bytes()
	if err != nil {
		return nil, fmt.Errorf("%s MCP configuration command failed; run %s mcp --help and inspect that client's configuration: %w", name, name, err)
	}
	return output, nil
}
func uniqueJSON(data []byte) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	var visit func() error
	visit = func() error {
		token, err := decoder.Token()
		if err != nil {
			return err
		}
		delimiter, ok := token.(json.Delim)
		if !ok {
			return nil
		}
		switch delimiter {
		case '{':
			keys := map[string]bool{}
			for decoder.More() {
				key, err := decoder.Token()
				if err != nil {
					return err
				}
				name, ok := key.(string)
				if !ok || keys[name] {
					return errors.New("duplicate or invalid JSON key")
				}
				keys[name] = true
				if err = visit(); err != nil {
					return err
				}
			}
		case '[':
			for decoder.More() {
				if err = visit(); err != nil {
					return err
				}
			}
		default:
			return errors.New("invalid JSON delimiter")
		}
		_, err = decoder.Token()
		return err
	}
	if err := visit(); err != nil {
		return err
	}
	if _, err := decoder.Token(); err != io.EOF {
		return errors.New("trailing JSON data")
	}
	return nil
}
func readJSONMCP(path string) (map[string]json.RawMessage, map[string]json.RawMessage, error) {
	doc := map[string]json.RawMessage{}
	servers := map[string]json.RawMessage{}
	if err := safeLocalPath(path); err != nil {
		return nil, nil, err
	}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return doc, servers, nil
	}
	if err != nil {
		return nil, nil, err
	}
	if err = uniqueJSON(data); err != nil {
		return nil, nil, fmt.Errorf("invalid or duplicate-key MCP JSON at %s; repair it before setup", path)
	}
	if err = json.Unmarshal(data, &doc); err != nil || doc == nil {
		return nil, nil, fmt.Errorf("invalid MCP JSON configuration at %s; repair it before setup", path)
	}
	if raw, ok := doc["mcpServers"]; ok {
		if err = json.Unmarshal(raw, &servers); err != nil || servers == nil {
			return nil, nil, fmt.Errorf("invalid mcpServers object at %s", path)
		}
	}
	return doc, servers, nil
}
func matchingMCPEntry(raw json.RawMessage, wanted localMCPEntry) bool {
	var entry map[string]json.RawMessage
	if json.Unmarshal(raw, &entry) != nil {
		return false
	}
	var command string
	var args []string
	if json.Unmarshal(entry["command"], &command) != nil || json.Unmarshal(entry["args"], &args) != nil {
		return false
	}
	if command != wanted.Command || !reflect.DeepEqual(args, wanted.Args) {
		return false
	}
	for key, value := range entry {
		switch key {
		case "command", "args":
		case "type":
			if string(value) != "\"stdio\"" {
				return false
			}
		case "env":
			var env map[string]string
			if json.Unmarshal(value, &env) != nil || len(env) != 0 {
				return false
			}
		default:
			return false
		}
	}
	return true
}
func codexEntry(ctx context.Context, scope, path string) (json.RawMessage, bool, error) {
	if err := safeLocalPath(path); err != nil {
		return nil, false, err
	}
	if _, err := os.Stat(path); errors.Is(err, os.ErrNotExist) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	output, err := runMCPClient(ctx, "codex", scope, path, "mcp", "list", "--json")
	if err != nil {
		return nil, false, err
	}
	var entries []struct {
		Name      string          `json:"name"`
		Transport json.RawMessage `json:"transport"`
		Enabled   bool            `json:"enabled"`
	}
	if err = json.Unmarshal(output, &entries); err != nil {
		return nil, false, errors.New("unrecognized Codex MCP list response; update the client or configure it manually")
	}
	for _, entry := range entries {
		if entry.Name == "sellapp" {
			if !entry.Enabled {
				return json.RawMessage(`{"disabled":true}`), true, nil
			}
			var transport map[string]json.RawMessage
			if err = json.Unmarshal(entry.Transport, &transport); err != nil {
				return nil, false, err
			}
			for _, key := range []string{"env", "env_vars", "cwd"} {
				if string(transport[key]) == "null" || (key == "env_vars" && string(transport[key]) == "[]") {
					delete(transport, key)
				}
			}
			raw, _ := json.Marshal(transport)
			return raw, true, nil
		}
	}
	return nil, false, nil
}
func registrationEntry(ctx context.Context, client, scope, path string) (json.RawMessage, bool, error) {
	if client == "codex" {
		return codexEntry(ctx, scope, path)
	}
	_, servers, err := readJSONMCP(path)
	if err != nil {
		return nil, false, err
	}
	raw, ok := servers["sellapp"]
	return raw, ok, nil
}
func registerLocalMCP(ctx context.Context, client, scope, executable string) (bool, error) {
	path, err := mcpConfigurationPath(client, scope)
	if err != nil {
		return false, err
	}
	wanted := localMCPEntry{Command: executable, Args: []string{"mcp", "--no-interactive"}}
	changed := false
	err = withAgentLock(path+".sellapp.lock", func() error {
		raw, exists, err := registrationEntry(ctx, client, scope, path)
		if err != nil {
			return err
		}
		if exists {
			if !matchingMCPEntry(raw, wanted) {
				return fmt.Errorf("conflicting sellapp MCP entry in %s; inspect and remove or rename it in the client before registering", path)
			}
			return nil
		}
		switch client {
		case "codex":
			_, err = runMCPClient(ctx, client, scope, path, "mcp", "add", "sellapp", "--", executable, "mcp", "--no-interactive")
		case "claude-code":
			_, err = runMCPClient(ctx, client, scope, path, "mcp", "add", "--transport", "stdio", "--scope", scope, "sellapp", "--", executable, "mcp", "--no-interactive")
		case "cursor":
			doc, servers, readErr := readJSONMCP(path)
			if readErr != nil {
				return readErr
			}
			servers["sellapp"], err = json.Marshal(wanted)
			if err != nil {
				return err
			}
			doc["mcpServers"], err = json.Marshal(servers)
			if err != nil {
				return err
			}
			data, marshalErr := json.MarshalIndent(doc, "", "  ")
			if marshalErr != nil {
				return marshalErr
			}
			err = atomicAgentWrite(path, append(data, '\n'))
		}
		if err != nil {
			return err
		}
		raw, exists, err = registrationEntry(ctx, client, scope, path)
		if err != nil {
			return err
		}
		if !exists || !matchingMCPEntry(raw, wanted) {
			return errors.New("client did not retain the expected SellApp bridge registration; inspect its configuration")
		}
		changed = true
		return nil
	})
	return changed, err
}

type agentLimitedBuffer struct {
	bytes.Buffer
	limit int
}

func (buffer *agentLimitedBuffer) Write(data []byte) (int, error) {
	if len(data) > buffer.limit-buffer.Len() {
		return 0, errors.New("local setup output exceeded its limit")
	}
	return buffer.Buffer.Write(data)
}

type mcpDiagnostic struct {
	Name   string `json:"name"`
	OK     bool   `json:"ok"`
	Detail string `json:"detail"`
}

func checkMCPStartup(ctx context.Context, cfg *Config) (map[string]any, error) {
	timeout, cancel := context.WithTimeout(ctx, 15*time.Second)
	defer cancel()
	auth, err := newBridgeAuthorization(cfg)
	if err != nil {
		return nil, err
	}
	client := mcp.NewClient(&mcp.Implementation{Name: "sellapp-doctor", Version: cliVersion}, nil)
	session, err := client.Connect(timeout, &mcp.StreamableClientTransport{Endpoint: auth.origin + "/mcp?tool_mode=compact", HTTPClient: &http.Client{Transport: auth, CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}, MaxRetries: -1}, nil)
	if err != nil {
		return nil, bridgeInitializationFailure(&http.Client{Transport: auth})
	}
	defer session.Close()
	connection, err := session.CallTool(timeout, &mcp.CallToolParams{Name: "sellapp_get_connection", Arguments: map[string]any{}})
	if err != nil || connection.IsError {
		return nil, errors.New("hosted connection diagnostics failed; inspect the connection in MCP access or CLI access")
	}
	return map[string]any{"server": session.InitializeResult().ServerInfo, "connection": connection.StructuredContent}, nil
}

func mcpDoctorCommand(cfg *Config) *cobra.Command {
	var client string
	var global, project bool
	cmd := &cobra.Command{Use: "doctor", Args: cobra.NoArgs, Short: "Check local registration, hosted authentication and connection state", RunE: func(cmd *cobra.Command, _ []string) error {
		checks := []mcpDiagnostic{}
		executable, err := localSellAppExecutable()
		checks = append(checks, mcpDiagnostic{"executable", err == nil, "current SellApp executable"})
		connection, connectionErr := checkMCPStartup(cmd.Context(), cfg)
		detail := "hosted MCP initialized and returned connection diagnostics"
		if connectionErr != nil {
			detail = connectionErr.Error()
		}
		checks = append(checks, mcpDiagnostic{"hosted_connection", connectionErr == nil, detail})
		if global && project {
			return &UsageError{Message: "choose only one of --global or --project"}
		}
		clients := []string{"codex", "claude-code", "cursor"}
		if client != "" {
			if err = validMCPClient(client); err != nil {
				return err
			}
			clients = []string{client}
		}
		scopes := []string{"user", "project"}
		if global {
			scopes = []string{"user"}
		}
		if project {
			scopes = []string{"project"}
		}
		for _, selectedClient := range clients {
			for _, scope := range scopes {
				path, pathErr := mcpConfigurationPath(selectedClient, scope)
				ok := false
				detail := "not registered; use sellapp mcp add --client " + selectedClient + " with the desired scope"
				if pathErr != nil {
					detail = pathErr.Error()
				} else if raw, exists, readErr := registrationEntry(cmd.Context(), selectedClient, scope, path); readErr != nil {
					detail = readErr.Error()
				} else if exists {
					ok = matchingMCPEntry(raw, localMCPEntry{executable, []string{"mcp", "--no-interactive"}})
					detail = "registered hosted MCP bridge"
					if !ok {
						detail = "registration differs from this executable or enables additional options; inspect the client entry"
					}
				}
				checks = append(checks, mcpDiagnostic{"registration_" + selectedClient + "_" + scope, ok, detail})
			}
		}
		return writeFormattedResult(cfg, map[string]any{"checks": checks, "connection": connection, "contacted_business_api": false, "credential_source": "selected OAuth profile", "grant_model": "account", "write_policy": "hosted confirmation policy"})
	}}
	cmd.Flags().StringVar(&client, "client", "", "inspect codex, claude-code, or cursor registration")
	cmd.Flags().BoolVar(&global, "global", false, "inspect user registration only")
	cmd.Flags().BoolVar(&project, "project", false, "inspect current-directory registration only")
	return cmd
}
