// Code generated by oagen. DO NOT EDIT.

//go:build !windows

package cli

import (
	"os"
	"syscall"
)

func agentFileHasLinks(_ string, info os.FileInfo) (bool, error) {
	stat, ok := info.Sys().(*syscall.Stat_t)
	return ok && stat.Nlink > 1, nil
}
