// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

func TestCommerceAmountExact(t *testing.T) {
	for _, tc := range []struct {
		value, currency string
		want            int64
	}{{"25.00", "USD", 2500}, {"0.01", "USD", 1}, {"25", "JPY", 25}, {"25.50", "HUF", 2550}, {"25.50", "TWD", 2550}, {"90071992547409.93", "USD", 9007199254740993}} {
		got, err := commerceAmount(tc.value, tc.currency)
		if err != nil || got != tc.want {
			t.Fatalf("%+v: %d %v", tc, got, err)
		}
	}
	for _, tc := range [][2]string{{"1.001", "USD"}, {"1.0", "JPY"}, {"1e3", "USD"}, {"-1", "USD"}, {"+1", "USD"}, {"1,000", "USD"}, {"1.", "USD"}, {".5", "USD"}, {"0", "USD"}, {"1", "usd"}, {"1", "BTC"}, {"9999999999999999999", "USD"}} {
		if _, err := commerceAmount(tc[0], tc[1]); err == nil {
			t.Fatal("accepted invalid amount", tc)
		}
	}
}
func TestCommerceWritesUseGeneratedOperations(t *testing.T) {
	cases := []struct {
		args         []string
		method, path string
		body         map[string]any
	}{
		{[]string{"charges", "create", "25.00", "USD", "--email", "maya.chen@example.com", "--return-url", "https://example.com/return", "--payment-methods", "[\"STRIPE\",\"PAYPAL\"]"}, "POST", "/v2/charges", map[string]any{"total": float64(2500), "currency": "USD", "payment_methods": []any{"STRIPE", "PAYPAL"}}},
		{[]string{"charge", "create", "25.50", "HUF", "--email", "maya.chen@example.com", "--return-url", "https://example.com/return", "--use-all-payment-methods"}, "POST", "/v2/charges", map[string]any{"total": float64(2550), "currency": "HUF", "use_all_payment_methods": true}},
		{[]string{"wallet", "topups", "create", "42", "25.00", "--payment-method", "STRIPE", "--idempotency-key", "top-up-42-001"}, "POST", "/v2/wallets/42/top-ups", map[string]any{"amount_cents": float64(2500), "payment_method": "STRIPE"}},
		{[]string{"wallet", "credit", "42", "25.00", "--note", "Account credit", "--idempotency-key", "credit-42-001"}, "POST", "/v2/wallets/42/adjustments", map[string]any{"amount_cents": float64(2500), "idempotency_key": "credit-42-001", "note": "Account credit"}},
		{[]string{"wallet", "debit", "42", "1.25", "--note", "Correction", "--idempotency-key", "debit-42-001"}, "POST", "/v2/wallets/42/adjustments", map[string]any{"amount_cents": float64(-125), "idempotency_key": "debit-42-001"}},
		{[]string{"tickets", "close", "42", "--idempotency-key", "ticket-42-close"}, "PATCH", "/v2/tickets/42", map[string]any{"status": "CLOSED"}},
		{[]string{"tickets", "reopen", "42"}, "PATCH", "/v2/tickets/42", map[string]any{"status": "OPEN"}},
		{[]string{"tickets", "archive", "42"}, "PATCH", "/v2/tickets/42", map[string]any{"archived": true}},
	}
	for _, tc := range cases {
		t.Run(strings.Join(tc.args[:2], " "), func(t *testing.T) {
			calls := 0
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				calls++
				if r.Method != tc.method || r.URL.Path != tc.path {
					t.Errorf("request %s %s", r.Method, r.URL.Path)
				}
				if r.Header.Get("X-STORE") != "test-store" || r.Header.Get("Authorization") != "Bearer test-key" {
					t.Error("missing credentials or store")
				}
				var body map[string]any
				if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
					t.Error(err)
				}
				for key, want := range tc.body {
					a, _ := json.Marshal(body[key])
					b, _ := json.Marshal(want)
					if string(a) != string(b) {
						t.Errorf("%s=%s want=%s", key, a, b)
					}
				}
				if strings.Contains(tc.path, "top-ups") && r.Header.Get("Idempotency-Key") != "top-up-42-001" {
					t.Error("key lost")
				}
				if tc.args[0] == "tickets" && len(body) != 1 {
					t.Error("shortcut changed unrelated ticket fields")
				}
				key := tc.method + " " + tc.path
				key = strings.ReplaceAll(key, "/42", "/{customer}")
				if tc.args[0] == "tickets" {
					key = "PATCH /v2/tickets/{ticket}"
				}
				w.Header().Set("Content-Type", "application/json")
				io.WriteString(w, responseFixture(key))
			}))
			defer server.Close()
			if _, err := execute(t, append(baseArgs(server), tc.args...)...); err != nil {
				t.Fatal(err)
			}
			if calls != 1 {
				t.Fatal("calls", calls)
			}
		})
	}
}
func TestCommerceRejectsAmbiguousInputsBeforeNetwork(t *testing.T) {
	for _, args := range [][]string{
		{"charges", "create", "25", "USD", "--total", "1"},
		{"charges", "create", "25", "USD", "--body", "-"},
		{"charges", "create", "25", "USD", "--set", "currency=\"EUR\""},
		{"charges", "create", "25"},
		{"wallet", "topups", "create", "42", "25", "--amount-cents", "1"},
		{"wallet", "credit", "42", "25", "--note", "Credit"},
		{"wallet", "debit", "42", "25", "--idempotency-key", "debit-42"},
		{"wallet", "credit", "42", "-25", "--note", "Credit", "--idempotency-key", "credit-42"},
		{"tickets", "close", "42", "--status", "OPEN"},
		{"tickets", "archive", "42", "--body", "-"},
	} {
		root := NewRootCommand(io.Discard, io.Discard)
		root.SetArgs(append([]string{"--dry-run", "--no-interactive", "--no-audit"}, args...))
		root.SetIn(&failOnRead{t: t})
		if err := root.Execute(); err == nil {
			t.Fatal("accepted", args)
		}
	}
}

type failOnRead struct{ t *testing.T }

func (r *failOnRead) Read([]byte) (int, error) {
	r.t.Error("read stdin before rejecting ambiguous input")
	return 0, io.EOF
}

func TestCommerceWaitStatesAndBounds(t *testing.T) {
	for _, tc := range []struct {
		statuses  []string
		max       int
		wantError bool
		reason    string
	}{
		{[]string{"PENDING", "REVIEW", "COMPLETED"}, 3, false, ""},
		{[]string{"VOIDED"}, 3, true, "voided"},
		{[]string{"FAILED"}, 3, true, "failed"},
		{[]string{"PAID", "PENDING"}, 2, true, "poll_limit"},
		{[]string{"REVIEW"}, 1, true, "poll_limit"},
	} {
		calls := 0
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "GET" || r.URL.Path != "/v2/charges/42" {
				t.Error(r.Method, r.URL.Path)
			}
			status := tc.statuses[calls]
			calls++
			var fixture map[string]any
			json.Unmarshal([]byte(responseFixture("GET /v2/charges/{charge}")), &fixture)
			fixture["data"].(map[string]any)["status"] = status
			json.NewEncoder(w).Encode(fixture)
		}))
		args := append(baseArgs(server), "charges", "wait", "42", "--interval", "100ms", "--max-polls", fmtInt(tc.max))
		out, err := execute(t, args...)
		server.Close()
		if (err != nil) != tc.wantError || calls != len(tc.statuses) || !strings.Contains(out, tc.reason) {
			t.Fatalf("calls=%d out=%s err=%v", calls, out, err)
		}
	}
}
func fmtInt(n int) string {
	if n == 1 {
		return "1"
	}
	if n == 2 {
		return "2"
	}
	return "3"
}
func TestCommerceWaitCancellation(t *testing.T) {
	calls := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { calls++; <-r.Context().Done() }))
	defer server.Close()
	var out bytes.Buffer
	root := NewRootCommand(&out, io.Discard)
	root.SetArgs(append(baseArgs(server), "charges", "wait", "42", "--timeout", "100ms"))
	started := time.Now()
	err := root.ExecuteContext(context.Background())
	if err == nil || time.Since(started) > 2*time.Second || calls != 1 || !strings.Contains(out.String(), "timeout_or_cancelled") {
		t.Fatal(err, out.String(), calls)
	}
}
func TestCommerceOpenUsesReturnedURLAndDryRunDoesNotOpen(t *testing.T) {
	old := openChargeBrowser
	defer func() { openChargeBrowser = old }()
	opened := ""
	openChargeBrowser = func(address string) error { opened = address; return nil }
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var fixture map[string]any
		json.Unmarshal([]byte(responseFixture("GET /v2/charges/{charge}")), &fixture)
		fixture["data"].(map[string]any)["url"] = "https://example.com/pay/returned-token"
		json.NewEncoder(w).Encode(fixture)
	}))
	defer server.Close()
	if _, err := execute(t, append(baseArgs(server), "charges", "open", "42")...); err != nil || opened != "https://example.com/pay/returned-token" {
		t.Fatal(err, opened)
	}
	opened = ""
	if _, err := execute(t, "--dry-run", "--no-audit", "charges", "open", "42"); err != nil || opened != "" {
		t.Fatal(err, opened)
	}
}
func TestCommerceConfirmationAndDryRun(t *testing.T) {
	for _, args := range [][]string{
		{"wallet", "credit", "42", "25", "--note", "Credit", "--idempotency-key", "credit-42"},
		{"wallet", "topups", "create", "42", "25", "--payment-method", "STRIPE"},
		{"tickets", "close", "42"},
	} {
		if out, err := execute(t, append([]string{"--dry-run", "--no-audit"}, args...)...); err != nil || !strings.Contains(out, "false") {
			t.Fatal(out, err)
		}
		if _, err := execute(t, append([]string{"--api-key", "test-key", "--store", "test-store", "--no-interactive", "--no-audit"}, args...)...); err == nil || !strings.Contains(err.Error(), "--yes") {
			t.Fatal(err)
		}
	}
}

func TestCommerceTopUpRetryPreservesKeyAndBody(t *testing.T) {
	calls := 0
	firstBody := ""
	firstKey := ""
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls++
		body, _ := io.ReadAll(r.Body)
		key := r.Header.Get("Idempotency-Key")
		if calls == 1 {
			firstBody = string(body)
			firstKey = key
			w.Header().Set("Retry-After", "0")
			w.WriteHeader(429)
			io.WriteString(w, "{}")
			return
		}
		if string(body) != firstBody || key != firstKey || key != "topup-retry-001" {
			t.Error("retry changed key or body")
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(201)
		io.WriteString(w, responseFixture("POST /v2/wallets/{customer}/top-ups"))
	}))
	defer server.Close()
	out, err := execute(t, append(baseArgs(server), "--max-retries", "1", "wallet", "topups", "create", "42", "25", "--payment-method", "STRIPE", "--idempotency-key", "topup-retry-001")...)
	if err != nil || calls != 2 || !strings.Contains(out, "checkout_url") || !strings.Contains(out, "charge_id") {
		t.Fatal(out, err, calls)
	}
}
func TestCommerceOpenRejectsUnsafeReturnedURLs(t *testing.T) {
	old := openChargeBrowser
	defer func() { openChargeBrowser = old }()
	openChargeBrowser = func(string) error { t.Error("opened unsafe URL"); return nil }
	for _, address := range []string{"javascript:alert(1)", "http://example.com/pay", "https://user:pass@example.com/pay", ""} {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			var fixture map[string]any
			json.Unmarshal([]byte(responseFixture("GET /v2/charges/{charge}")), &fixture)
			fixture["data"].(map[string]any)["url"] = address
			json.NewEncoder(w).Encode(fixture)
		}))
		_, err := execute(t, append(baseArgs(server), "charges", "open", "42")...)
		server.Close()
		if err == nil {
			t.Fatal("accepted", address)
		}
	}
}
