// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"context"
	"errors"
	"fmt"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

// API charge amounts follow ISO currency minor units, including two places for HUF and TWD.
func commerceAmount(value, currency string) (int64, error) {
	places := 2
	switch currency {
	case "JPY":
		places = 0
	case "AUD", "BRL", "CAD", "CNY", "CZK", "DKK", "EUR", "GHS", "HKD", "HUF", "ILS", "INR", "MYR", "MXN", "NGN", "TWD", "NZD", "NOK", "PHP", "PLN", "GBP", "RUB", "SGD", "SEK", "CHF", "THB", "USD", "ZAR":
	default:
		return 0, &UsageError{Message: "unsupported currency " + currency + "; use an uppercase currency code supported by charges"}
	}
	parts := strings.Split(value, ".")
	if len(parts) > 2 || parts[0] == "" || (len(parts) == 2 && (parts[1] == "" || len(parts[1]) > places)) {
		return 0, &UsageError{Message: fmt.Sprintf("amount must be a positive decimal with at most %d decimal places for %s", places, currency)}
	}
	digits := parts[0]
	fraction := ""
	if len(parts) == 2 {
		fraction = parts[1]
	}
	digits += fraction + strings.Repeat("0", places-len(fraction))
	for _, digit := range digits {
		if digit < '0' || digit > '9' {
			return 0, &UsageError{Message: "amount must contain decimal digits only, without signs, commas, or exponents"}
		}
	}
	amount, err := strconv.ParseInt(digits, 10, 64)
	if err != nil || amount <= 0 {
		return 0, &UsageError{Message: "amount must be positive and fit in a signed 64-bit integer"}
	}
	return amount, nil
}

func rejectShortcutFlags(cmd *cobra.Command, names ...string) error {
	for _, name := range names {
		if cmd.Flags().Changed(name) {
			return &UsageError{Message: "positional shorthand cannot be combined with --" + name + "; use either shorthand with named option flags, or the generated JSON/flag form"}
		}
	}
	return nil
}

func configureCommerceShorthand(cmd *cobra.Command, cfg *Config, entry CatalogEntry) {
	run := cmd.RunE
	switch entry.OperationID {
	case "createCharge":
		cmd.Use = "create [AMOUNT CURRENCY]"
		cmd.Args = func(_ *cobra.Command, args []string) error {
			if len(args) != 0 && len(args) != 2 {
				return &UsageError{Message: "use charges create AMOUNT CURRENCY, or supply --total in minor units and --currency"}
			}
			return nil
		}
		cmd.Long += "\n\nShorthand: charges create 25.00 USD --email EMAIL --return-url URL --use-all-payment-methods. Positional amounts use major units; --total retains integer minor units. This creates a charge; it does not prove payment. Check existing charges before retrying an uncertain creation."
		cmd.RunE = func(cmd *cobra.Command, args []string) error {
			if len(args) == 2 {
				if err := rejectShortcutFlags(cmd, "total", "currency", "body", "set"); err != nil {
					return err
				}
				amount, err := commerceAmount(args[0], args[1])
				if err != nil {
					return err
				}
				if err = cmd.Flags().Set("total", strconv.FormatInt(amount, 10)); err != nil {
					return err
				}
				if err = cmd.Flags().Set("currency", args[1]); err != nil {
					return err
				}
			}
			return run(cmd, nil)
		}
	case "createWalletTopUp":
		cmd.Use = "create [CUSTOMER_ID [AMOUNT]]"
		cmd.Args = cobra.MaximumNArgs(2)
		cmd.Long += "\n\nShorthand: wallet topups create CUSTOMER_ID 25.00 --payment-method STRIPE --idempotency-key KEY. Amounts use USD major units. data.checkout_url is the customer payment link; data.charge_id lets you check its status with charges get or charges wait. No funds are credited until payment completes. Custom methods also need --custom-payment-method-id."
		cmd.RunE = func(cmd *cobra.Command, args []string) error {
			if len(args) == 2 {
				if err := rejectShortcutFlags(cmd, "amount-cents", "customer", "body", "set"); err != nil {
					return err
				}
				amount, err := commerceAmount(args[1], "USD")
				if err != nil {
					return err
				}
				if err = cmd.Flags().Set("amount-cents", strconv.FormatInt(amount, 10)); err != nil {
					return err
				}
				args = args[:1]
			}
			return run(cmd, args)
		}
	}
}

func commerceGroup(root *cobra.Command, name string) *cobra.Command {
	for _, cmd := range root.Commands() {
		if cmd.Name() == name {
			return cmd
		}
	}
	return nil
}

func addCommerceCommands(root *cobra.Command, cfg *Config) {
	if charges := commerceGroup(root, "charges"); charges != nil {
		charges.Aliases = append(charges.Aliases, "charge")
		charges.AddCommand(chargeWaitCommand(cfg), chargeOpenCommand(cfg))
	}
	if wallet := commerceGroup(root, "wallet"); wallet != nil {
		for _, action := range []string{"credit", "debit"} {
			entry, err := catalogOperation("adjustCustomerWallet")
			if err != nil {
				continue
			}
			cmd := &cobra.Command{Use: action + " CUSTOMER_ID AMOUNT", Short: "Manually " + action + " USD wallet funds without collecting payment", Args: cobra.ExactArgs(2)}
			configureAdapter(cmd, cfg, entry)
			run := cmd.RunE
			debit := action == "debit"
			var key string
			cmd.Flags().StringVar(&key, "idempotency-key", "", "Required. Stable key for this intended wallet adjustment; reuse with identical inputs")
			cmd.Long = cmd.Short + ". Requires --note and --idempotency-key. Amount is positive USD major units; the command applies the direction. This changes spendable money immediately. Debits cannot exceed available funds. Creating a customer payment link instead uses wallet topups create. Use --dry-run to inspect or --yes to confirm in automation."
			cmd.RunE = func(cmd *cobra.Command, args []string) error {
				schema, _ := cmd.Flags().GetBool("schema")
				if schema {
					return run(cmd, nil)
				}
				if err := rejectShortcutFlags(cmd, "amount-cents", "customer", "body-idempotency-key", "body", "set"); err != nil {
					return err
				}
				if strings.TrimSpace(key) == "" {
					return &UsageError{Message: "--idempotency-key is required; choose one stable key for this intended adjustment and retain it for retries"}
				}
				note, _ := cmd.Flags().GetString("note")
				if strings.TrimSpace(note) == "" {
					return &UsageError{Message: "--note is required; explain why you are changing the wallet balance"}
				}
				amount, err := commerceAmount(args[1], "USD")
				if err != nil {
					return err
				}
				if debit {
					amount = -amount
				}
				if err = cmd.Flags().Set("amount-cents", strconv.FormatInt(amount, 10)); err != nil {
					return err
				}
				if err = cmd.Flags().Set("body-idempotency-key", key); err != nil {
					return err
				}
				return run(cmd, args[:1])
			}
			wallet.AddCommand(cmd)
		}
	}
	if tickets := commerceGroup(root, "tickets"); tickets != nil {
		for _, action := range []string{"close", "reopen", "archive"} {
			entry, err := catalogOperation("updateTicket")
			if err != nil {
				continue
			}
			cmd := &cobra.Command{Use: action + " ID", Short: action + " a support ticket", Args: cobra.ExactArgs(1)}
			configureAdapter(cmd, cfg, entry)
			run := cmd.RunE
			cmd.Long = "Update this ticket using the existing ticket operation. Closing a previously open ticket notifies the customer. Reopen changes only status; archive changes only archived. Requires current ticket permission and confirmation. Use --idempotency-key KEY for response replay, --dry-run to inspect, or --yes for automation."
			cmd.RunE = func(cmd *cobra.Command, args []string) error {
				schema, _ := cmd.Flags().GetBool("schema")
				if schema {
					return run(cmd, nil)
				}
				if err := rejectShortcutFlags(cmd, "status", "archived", "body", "set"); err != nil {
					return err
				}
				field, value := "status", "CLOSED"
				if action == "reopen" {
					value = "OPEN"
				}
				if action == "archive" {
					field, value = "archived", "true"
				}
				if err := cmd.Flags().Set(field, value); err != nil {
					return err
				}
				return run(cmd, args)
			}
			tickets.AddCommand(cmd)
		}
	}
}

var openChargeBrowser = openOAuthBrowser

func chargeOpenCommand(cfg *Config) *cobra.Command {
	return &cobra.Command{Use: "open ID", Short: "Open a charge's returned checkout URL in your browser", Long: "Retrieve the charge in your selected store and open data.url. Opening the checkout does not approve or verify payment. Use --dry-run to inspect the read without opening a browser.", Args: cobra.ExactArgs(1), RunE: func(cmd *cobra.Command, args []string) error {
		inv := workflowInvocation()
		inv.Path["charge"] = args[0]
		result, err := runWorkflowOperation(cmd, cfg, "getCharge", inv, false)
		if err != nil {
			return err
		}
		if cfg.DryRun {
			return cfg.writeResult(result)
		}
		data, err := workflowData(result)
		if err != nil {
			return err
		}
		address, _ := data["url"].(string)
		parsed, err := url.Parse(address)
		if err != nil || parsed.Scheme != "https" || parsed.Hostname() == "" || parsed.User != nil {
			return errors.New("charge response omitted a valid HTTPS checkout URL; retrieve the charge and inspect data.url")
		}
		if err = openChargeBrowser(address); err != nil {
			if outputErr := cfg.writeResult(map[string]any{"charge": data, "url": address, "opened": false}); outputErr != nil {
				return outputErr
			}
			return errors.New("could not open the browser; copy the returned url into your browser")
		}
		return cfg.writeResult(map[string]any{"charge": data, "url": address, "opened": true})
	}}
}

func chargeWaitCommand(cfg *Config) *cobra.Command {
	var interval time.Duration
	var maxPolls int
	cmd := &cobra.Command{Use: "wait ID", Short: "Wait for charge completion with a bounded read-only poll", Long: "Poll this charge until COMPLETED, a failed or reversed state, or the timeout. REVIEW keeps waiting for merchant review; this command never approves payment. --timeout bounds the entire wait (default 1m); --max-polls also bounds requests. A timeout leaves the charge unchanged. Use charges get ID to inspect it before another action.", Args: cobra.ExactArgs(1), RunE: func(cmd *cobra.Command, args []string) error {
		if interval < 100*time.Millisecond || interval > time.Minute {
			return &UsageError{Message: "--interval must be between 100ms and 1m"}
		}
		if maxPolls < 1 || maxPolls > 1000 {
			return &UsageError{Message: "--max-polls must be between 1 and 1000"}
		}
		if cfg.Timeout > time.Hour {
			return &UsageError{Message: "--timeout for charges wait cannot exceed 1h"}
		}
		ctx, cancel := context.WithTimeout(cmd.Context(), cfg.Timeout)
		defer cancel()
		original := cmd.Context()
		originalConfigContext := cfg.Context
		cmd.SetContext(ctx)
		cfg.Context = ctx
		defer func() { cmd.SetContext(original); cfg.Context = originalConfigContext }()
		inv := workflowInvocation()
		inv.Path["charge"] = args[0]
		var last any
		finish := func(reason string) error {
			if err := cfg.writeResult(map[string]any{"completed": false, "reason": reason, "charge": last}); err != nil {
				return err
			}
			return fmt.Errorf("charge was not completed (%s); inspect it with charges get %s", reason, args[0])
		}
		for poll := 0; poll < maxPolls; poll++ {
			if ctx.Err() != nil {
				return finish("timeout_or_cancelled")
			}
			result, err := runWorkflowOperation(cmd, cfg, "getCharge", inv, false)
			if err != nil {
				if ctx.Err() != nil {
					return finish("timeout_or_cancelled")
				}
				return err
			}
			if cfg.DryRun {
				return cfg.writeResult(result)
			}
			data, err := workflowData(result)
			if err != nil {
				return err
			}
			last = data
			status, _ := data["status"].(string)
			switch status {
			case "COMPLETED":
				return cfg.writeResult(map[string]any{"completed": true, "charge": data})
			case "VOIDED", "FAILED", "REVERSED", "REFUNDED", "DISPUTING":
				return finish(strings.ToLower(status))
			case "PENDING", "REVIEW", "PAID", "PARTIAL":
			default:
				return finish("unknown_status")
			}
			if poll+1 < maxPolls {
				if err = waitWorkflow(ctx, interval); err != nil {
					return finish("timeout_or_cancelled")
				}
			}
		}
		return finish("poll_limit")
	}}
	cmd.Flags().DurationVar(&interval, "interval", 2*time.Second, "time between successful reads (100ms to 1m)")
	cmd.Flags().IntVar(&maxPolls, "max-polls", 300, "maximum polls (1 to 1000), also bounded by --timeout")
	return cmd
}
