// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"sort"
	"strings"
	"text/tabwriter"
	"time"

	sdk "github.com/sellapp/sellapp-cli/internal/sdk"
)

var defaultBaseURL = "https://sell.app/api"

type Config struct {
	metadataOutput  bool
	Context         context.Context
	CustomerSession string
	BrowserSession  string
	AccessToken     string
	oauthProfile    bool
	APIKey          string
	Store           string
	BaseURL         string
	BaseURLExplicit bool
	Timeout         time.Duration
	MaxRetries      int
	Output          string
	Fields          string
	Filter          string
	Template        string
	DryRun          bool
	NoInteractive   bool
	Yes             bool
	NoAudit         bool
	Profile         string
	Stdout          io.Writer
	Stderr          io.Writer
	capture         *dryRunTransport
	dryRunResponse  string
	dryRunAPIKey    bool
	lastStatus      int
	lastRequestID   string
}

type UsageError struct {
	Message       string
	MissingFields []string
	Suggestions   []string
}

func (e *UsageError) Error() string { return e.Message }

type dryRunTransport struct {
	request      map[string]any
	responseBody string
}

func redactedRequestURL(original *url.URL) string {
	copy := *original
	values := copy.Query()
	for key := range values {
		switch strings.ToLower(key) {
		case "signature", "code", "state", "access_token", "token", "code_verifier", "client_secret":
			values.Set(key, "[REDACTED]")
		}
	}
	copy.RawQuery = values.Encode()
	return copy.String()
}

func (t *dryRunTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	headers := map[string]string{}
	for name, values := range req.Header {
		value := strings.Join(values, ",")
		if strings.EqualFold(name, "Authorization") || strings.EqualFold(name, "X-STORE") || strings.EqualFold(name, "Idempotency-Key") || strings.EqualFold(name, "Cookie") {
			value = "[REDACTED]"
		}
		headers[name] = value
	}
	bodyBytes, _ := io.ReadAll(req.Body)
	t.request = map[string]any{"method": req.Method, "url": redactedRequestURL(req.URL), "headers": headers, "body_bytes": len(bodyBytes), "content_type": req.Header.Get("Content-Type")}
	body := t.responseBody
	if body == "" {
		body = "{}"
	}
	return &http.Response{StatusCode: 200, Status: "200 OK", Header: make(http.Header), Body: io.NopCloser(strings.NewReader(body)), Request: req}, nil
}

func (c *Config) client() *sdk.Client {
	c.lastStatus = 0
	c.lastRequestID = ""
	apiKey := c.APIKey
	if apiKey == "" {
		apiKey = os.Getenv("SELLAPP_API_KEY")
	}
	store := c.Store
	if store == "" {
		store = os.Getenv("SELLAPP_STORE")
	}
	if c.DryRun && apiKey == "" {
		apiKey = "dry-run-api-key"
	}
	if c.DryRun && store == "" {
		store = "dry-run-store"
	}
	client := &http.Client{Timeout: c.Timeout, CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}
	if c.DryRun {
		c.capture = &dryRunTransport{responseBody: c.dryRunResponse}
		client.Transport = c.capture
	}
	if c.DryRun && c.dryRunAPIKey {
		return sdk.NewClient("dry-run-key", store, sdk.WithBaseURL(c.BaseURL), sdk.WithHTTPClient(client), sdk.WithMaxRetries(0))
	}
	if c.DryRun {
		return sdk.NewClient("", store, sdk.WithAccessToken("dry-run-token"), sdk.WithCustomerSession("dry-run-session"), sdk.WithBrowserSession("dry-run-cookie"), sdk.WithBaseURL(c.BaseURL), sdk.WithHTTPClient(client), sdk.WithMaxRetries(0))
	}
	if c.CustomerSession != "" {
		return sdk.NewClient("", "", sdk.WithCustomerSession(c.CustomerSession), sdk.WithBaseURL(c.BaseURL), sdk.WithHTTPClient(client), sdk.WithTimeout(c.Timeout), sdk.WithMaxRetries(0))
	}
	if c.BrowserSession != "" {
		return sdk.NewClient("", "", sdk.WithBrowserSession(c.BrowserSession), sdk.WithBaseURL(c.BaseURL), sdk.WithHTTPClient(client), sdk.WithTimeout(c.Timeout), sdk.WithMaxRetries(0))
	}
	if c.AccessToken != "" {
		return sdk.NewClient("", store, sdk.WithAccessToken(c.AccessToken), sdk.WithBaseURL(c.BaseURL), sdk.WithHTTPClient(client), sdk.WithTimeout(c.Timeout), sdk.WithMaxRetries(c.MaxRetries))
	}
	return sdk.NewClient(apiKey, store, sdk.WithBaseURL(c.BaseURL), sdk.WithHTTPClient(client), sdk.WithTimeout(c.Timeout), sdk.WithMaxRetries(c.MaxRetries), sdk.WithRequestHook(func(event sdk.RequestEvent) {
		c.lastStatus = event.Status
		if event.RequestID != "" {
			c.lastRequestID = event.RequestID
		}
	}))
}

func (c *Config) writeResult(value any) error {
	if c.DryRun {
		if c.capture == nil || c.capture.request == nil {
			return errors.New("dry-run did not build a request")
		}
		value = map[string]any{"dry_run": true, "contacted_network": false, "request": c.capture.request, "warning": "Custom schema guarantees do not apply to dry-run fixtures."}
	}
	return writeFormattedResult(c, value)
}

func writeTable(output io.Writer, value any) error {
	data, err := json.Marshal(value)
	if err != nil {
		return err
	}
	var decoded any
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	if envelope, ok := decoded.(map[string]any); ok {
		if data, exists := envelope["data"]; exists {
			decoded = data
		}
	}
	rows := make([]map[string]any, 0)
	switch item := decoded.(type) {
	case []any:
		for _, raw := range item {
			if row, ok := raw.(map[string]any); ok {
				rows = append(rows, row)
			}
		}
	case map[string]any:
		rows = append(rows, item)
	default:
		_, err := fmt.Fprintln(output, item)
		return err
	}
	if len(rows) == 0 {
		_, err := fmt.Fprintln(output, "No results.")
		return err
	}
	keys := make([]string, 0)
	seen := map[string]bool{}
	for _, row := range rows {
		for key := range row {
			if !seen[key] {
				seen[key] = true
				keys = append(keys, key)
			}
		}
	}
	sort.Strings(keys)
	writer := tabwriter.NewWriter(output, 0, 4, 2, ' ', 0)
	fmt.Fprintln(writer, strings.Join(keys, "\t"))
	for _, row := range rows {
		values := make([]string, len(keys))
		for index, key := range keys {
			encoded, _ := json.Marshal(row[key])
			values[index] = string(encoded)
		}
		fmt.Fprintln(writer, strings.Join(values, "\t"))
	}
	return writer.Flush()
}

func requestOptions(idempotencyKey string) []sdk.RequestOption {
	if idempotencyKey == "" {
		return nil
	}
	return []sdk.RequestOption{sdk.WithIdempotencyKey(idempotencyKey)}
}

func readBody(value string, stdin io.Reader) ([]byte, error) {
	if value == "-" {
		return io.ReadAll(stdin)
	}
	if strings.HasPrefix(value, "@") {
		if len(value) == 1 {
			return nil, &UsageError{Message: "--body @ requires a file path"}
		}
		return os.ReadFile(strings.TrimPrefix(value, "@"))
	}
	return []byte(value), nil
}

func readJSONObject(value string, assignments []string, stdin io.Reader) (map[string]json.RawMessage, error) {
	body := map[string]json.RawMessage{}
	if value != "" {
		data, err := readBody(value, stdin)
		if err != nil {
			return nil, err
		}
		if err := json.Unmarshal(data, &body); err != nil {
			return nil, &UsageError{Message: "invalid --body JSON object: " + err.Error()}
		}
		if body == nil {
			return nil, &UsageError{Message: "--body must be a JSON object"}
		}
	}
	for _, assignment := range assignments {
		name, raw, ok := strings.Cut(assignment, "=")
		if !ok || strings.TrimSpace(name) == "" {
			return nil, &UsageError{Message: "--set requires FIELD=JSON"}
		}
		if !json.Valid([]byte(raw)) {
			return nil, &UsageError{Message: "invalid JSON for --set " + name}
		}
		if _, exists := body[name]; exists {
			return nil, &UsageError{Message: "conflicting assignments for " + name}
		}
		body[name] = json.RawMessage(raw)
	}
	return body, nil
}

func readUploads(assignments []string, stdin io.Reader) (map[string][][]byte, error) {
	files := map[string][][]byte{}
	stdinUsed := false
	for _, assignment := range assignments {
		name, filePath, ok := strings.Cut(assignment, "=")
		if !ok || strings.TrimSpace(name) == "" || filePath == "" {
			return nil, &UsageError{Message: "--upload requires FIELD=PATH"}
		}
		var data []byte
		var err error
		if filePath == "-" {
			if stdinUsed {
				return nil, &UsageError{Message: "stdin can only supply one upload"}
			}
			stdinUsed = true
			data, err = io.ReadAll(stdin)
		} else {
			data, err = os.ReadFile(filePath)
		}
		if err != nil {
			return nil, &UsageError{Message: fmt.Sprintf("read --upload %s: %v", name, err)}
		}
		files[name] = append(files[name], data)
	}
	return files, nil
}

func ExitCode(err error) int {
	if err == nil {
		return 0
	}
	if errors.Is(err, context.Canceled) {
		return 130
	}
	if errors.Is(err, context.DeadlineExceeded) {
		return 5
	}
	var oauth *oauthFailure
	if errors.As(err, &oauth) {
		return oauth.Exit
	}
	var usage *UsageError
	if errors.As(err, &usage) {
		return 2
	}
	var cliInput *sdk.CLIInputError
	if errors.As(err, &cliInput) {
		return 2
	}
	var auth *sdk.AuthenticationError
	if errors.As(err, &auth) {
		return 4
	}
	var timeout *sdk.TimeoutError
	if errors.As(err, &timeout) {
		return 5
	}
	var transport *sdk.TransportError
	if errors.As(err, &transport) {
		return 5
	}
	var serialization *sdk.SerializationError
	if errors.As(err, &serialization) {
		return 6
	}
	var api *sdk.APIError
	if errors.As(err, &api) {
		return 3
	}
	if status, _, _ := apiDetailsFromError(err); status != 0 {
		if status == 401 {
			return 4
		}
		return 3
	}
	return 7
}

func FormatError(err error) string {
	status, apiType, code := apiDetailsFromError(err)
	message := err.Error()
	if status == 403 {
		message = "Store access denied; check the selected store, your current membership and permissions, and the command's required OAuth scopes or API-key abilities. Credentials are retained for other stores."
	}
	if status == 401 {
		message = "Credentials are invalid, expired, or revoked; check authentication and authorize again if needed."
	}
	var oauth *oauthFailure
	if errors.As(err, &oauth) {
		code = oauth.Code
	}
	if code == "invalid_client" || code == "invalid_scope" || code == "invalid_grant" || code == "access_denied" {
		message = oauthProtocolFailure(code, status).Message
	}

	var transportURL *url.Error
	if errors.As(err, &transportURL) {
		message = "HTTP transport failed; request URL omitted to protect credentials"
	}
	detail := map[string]any{"message": message, "exit_code": ExitCode(err), "error_type": fmt.Sprintf("%T", err)}
	var usage *UsageError
	if errors.As(err, &usage) {
		detail["missing_fields"] = usage.MissingFields
		suggestions := usage.Suggestions
		if len(suggestions) == 0 {
			suggestions = []string{"Inspect the command with sellapp commands RESOURCE ACTION --json or COMMAND --help."}
		}
		detail["suggestions"] = suggestions
	}
	if status != 0 {
		detail["status"] = status
	}
	if apiType != "" {
		detail["type"] = apiType
	}
	if code != "" {
		detail["code"] = code
	}
	if requestID := requestIDFromError(err); requestID != "" {
		detail["request_id"] = requestID
	}
	payload := map[string]any{"error": detail}
	data, marshalErr := json.Marshal(payload)
	if marshalErr != nil {
		return fmt.Sprintf("{\"error\":{\"message\":%q,\"exit_code\":7}}", err.Error())
	}
	return string(data)
}
