// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"reflect"
	"strings"
	"testing"
)

func TestConvenienceCommandsPreserveNestedWireBodies(t *testing.T) {
	cases := []struct {
		key, body string
		status    int
	}{
		{"POST /v2/products", "{\"title\":\"Launch bundle\",\"description\":\"Two design kits in one purchase\",\"visibility\":\"PUBLIC\",\"type\":\"bundle\",\"variants\":[{\"title\":\"Standard\",\"description\":\"The complete design kit\",\"pricing\":{\"price\":{\"price\":1999,\"currency\":\"USD\"},\"humble\":false},\"deliverable\":{\"types\":[\"BUNDLE\"],\"data\":{}},\"minimum_purchase_quantity\":1,\"maximum_purchase_quantity\":10,\"payment_methods\":[\"PAYPAL\"]}],\"bundle_items\":[{\"product_variant_id\":4321,\"quantity\":2}]}", 201},
		{"POST /v2/products", "{\"title\":\"Design kit\",\"description\":\"Reusable templates for your next launch\",\"visibility\":\"PUBLIC\",\"variants\":[{\"title\":\"Standard\",\"description\":\"The complete design kit\",\"pricing\":{\"price\":{\"price\":1999,\"currency\":\"USD\"},\"humble\":false},\"deliverable\":{\"types\":[\"MANUAL\"],\"data\":{\"comment\":\"Your kit will be delivered shortly.\"}},\"minimum_purchase_quantity\":1,\"maximum_purchase_quantity\":10,\"payment_methods\":[\"PAYPAL\"]}]}", 201},
		{"POST /v2/addons", "{\"title\":\"Priority support\",\"description\":\"Personal help with your design kit\",\"visibility\":\"PUBLIC\",\"is_draft\":false,\"parent_product_ids\":[120],\"variant\":{\"title\":\"Standard\",\"description\":\"The complete design kit\",\"pricing\":{\"price\":{\"price\":1999,\"currency\":\"USD\"},\"humble\":false},\"deliverable\":{\"types\":[\"MANUAL\"],\"data\":{\"comment\":\"Your kit will be delivered shortly.\"}},\"minimum_purchase_quantity\":1,\"maximum_purchase_quantity\":10,\"payment_methods\":[\"PAYPAL\"]}}", 201},
		{"PUT /v2/groups/{group}/products", "{\"product_ids\":[121,120]}", 200},
		{"PUT /v2/groups/{group}/products", "{\"product_ids\":[]}", 200},
		{"PATCH /v2/groups/{group}", "{\"section_id\":null}", 200},
		{"PATCH /v2/tickets/{ticket}", "{\"archived\":false}", 200},
		{"PATCH /v2/tickets/{ticket}", "{\"status\":\"CLOSED\"}", 200},
		{"PUT /v2/customers/external/{externalId}", "{\"email\":\"maya.chen@example.com\",\"metadata\":{}}", 200},
		{"POST /v2/orders/wallet", "{\"customer_email\":\"maya.chen@example.com\",\"product_variants\":{\"4321\":{\"quantity\":1}},\"country\":\"US\"}", 201},
		{"POST /v2/orders/{order}/wallet-payments", "{\"expected_status\":\"PENDING\"}", 200},
		{"POST /v2/payment-methods/custom", "{\"type\":\"instructions\",\"name\":\"Manual payment\",\"instructions\":\"Contact Launch Lab before sending a payment.\",\"enabled\":false,\"modifier\":{\"percentage\":\"-2.50\",\"fixed\":\"-1.00\"}}", 201},
		{"PATCH /v2/payment-methods/custom/{customPaymentMethod}", "{\"modifier\":null}", 200},
		{"PATCH /v2/payment-methods/custom/{customPaymentMethod}", "{\"modifier\":{}}", 200},
		{"PATCH /v2/payment-methods/custom/{customPaymentMethod}", "{\"modifier\":{\"percentage\":2.5,\"fixed\":-1}}", 200},
	}
	for _, test := range cases {
		t.Run(test.key+test.body, func(t *testing.T) {
			calls := 0
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				calls++
				var got, want any
				json.NewDecoder(r.Body).Decode(&got)
				json.Unmarshal([]byte(test.body), &want)
				if !reflect.DeepEqual(got, want) {
					t.Errorf("request shape changed: got %v want %v", got, want)
				}
				if strings.Contains(test.key, "externalId") && !strings.Contains(r.URL.EscapedPath(), "external%20customer+42") {
					t.Errorf("external ID not encoded: %s", r.URL.EscapedPath())
				}
				if strings.Contains(test.key, "wallet") && r.Header.Get("Idempotency-Key") != "fixture-wallet-001" {
					t.Error("wallet key changed")
				}
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(test.status)
				io.WriteString(w, responseFixture(test.key))
			}))
			defer server.Close()
			found := false
			for _, entry := range CommandCatalog {
				if entry.OperationKey != test.key {
					continue
				}
				found = true
				args := append(baseArgs(server), entry.Path...)
				for _, param := range entry.Parameters {
					if param.Required {
						value := param.Fixture
						if param.Name == "externalId" {
							value = "external customer+42"
						}
						if param.Name == "Idempotency-Key" {
							value = "fixture-wallet-001"
						}
						args = append(args, "--"+param.Flag, value)
					}
				}
				if strings.Contains(test.key, "wallet") {
					args = append(args, "--idempotency-key", "fixture-wallet-001")
				}
				args = append(args, "--body", test.body)
				if _, err := execute(t, args...); err != nil {
					t.Fatal(err)
				}
			}
			if !found || calls != 1 {
				t.Fatalf("found=%v calls=%d", found, calls)
			}
		})
	}
}

func TestLedgerCommandsPaginateEmptyResults(t *testing.T) {
	for _, key := range []string{"GET /v2/wallets/{customer}/transactions", "GET /v2/credit-balances/{customer}/{creditProduct}/transactions"} {
		t.Run(key, func(t *testing.T) {
			calls := 0
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				calls++
				if calls == 2 && r.URL.Query().Get("page") != "2" {
					t.Error("second page missing")
				}
				var result map[string]any
				json.Unmarshal([]byte(responseFixture(key)), &result)
				result["data"] = []any{}
				result["meta"] = map[string]any{"current_page": calls, "last_page": 2}
				result["links"] = map[string]any{"next": nil}
				w.Header().Set("Content-Type", "application/json")
				json.NewEncoder(w).Encode(result)
			}))
			defer server.Close()
			for _, entry := range CommandCatalog {
				if entry.OperationKey != key {
					continue
				}
				args := append(baseArgs(server), entry.Path...)
				for _, param := range entry.Parameters {
					if param.Required {
						args = append(args, "--"+param.Flag, param.Fixture)
					}
				}
				args = append(args, "--all", "--max-pages", "3")
				if _, err := execute(t, args...); err != nil {
					t.Fatal(err)
				}
			}
			if calls != 2 {
				t.Fatalf("pages=%d", calls)
			}
		})
	}
}
