// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"strings"
)

func configureHelp(root *cobra.Command) {
	detailed := false
	root.PersistentFlags().BoolVar(&detailed, "help-all", false, "show all transport, formatting, and protocol options")
	original := root.HelpFunc()
	root.SetHelpFunc(func(cmd *cobra.Command, args []string) {
		if detailed {
			original(cmd, args)
			return
		}
		var entry *CatalogEntry
		path := strings.TrimPrefix(cmd.CommandPath(), "sellapp ")
		for i := range CommandCatalog {
			if strings.Join(CommandCatalog[i].Path, " ") == path {
				entry = &CommandCatalog[i]
				break
			}
		}
		if entry == nil {
			original(cmd, args)
			return
		}
		out := cmd.OutOrStdout()
		fmt.Fprintf(out, "%s\n\nUsage:\n  %s\n", cmd.Short, cmd.UseLine())
		if entry.OperationID == "createCharge" || entry.OperationID == "createWalletTopUp" {
			fmt.Fprintln(out, "\n"+cmd.Long)
		}
		required := map[string]bool{}
		fmt.Fprintln(out, "\nRequired inputs:")
		count := 0
		for _, parameter := range entry.Parameters {
			if !parameter.Required {
				continue
			}
			count++
			required[parameter.Flag] = true
			if parameter.Positional {
				fmt.Fprintf(out, "  ID  %s\n", parameter.Description)
			} else {
				fmt.Fprintf(out, "  --%s  %s\n", parameter.Flag, parameter.Description)
			}
		}
		if entry.Body != nil {
			for _, field := range entry.Body.Fields {
				if !field.Required {
					continue
				}
				count++
				required[field.Flag] = true
				if field.Binary || field.BinaryArray {
					fmt.Fprintf(out, "  --upload %s=PATH  %s\n", field.Name, field.Description)
				} else {
					flag := cmd.Flags().Lookup(field.Flag)
					if flag != nil {
						fmt.Fprintf(out, "  --%s  %s\n", field.Flag, flag.Usage)
					}
				}
			}
		}
		if count == 0 {
			fmt.Fprintln(out, "  None.")
		}
		if entry.Body != nil && entry.Body.Schema != nil {
			fmt.Fprintln(out, "  Body requirements depend on the selected request variant. Inspect this command with sellapp commands "+path+" --json.")
		}
		fmt.Fprintln(out, "\nOptions:")
		cmd.LocalNonPersistentFlags().VisitAll(func(flag *pflag.Flag) {
			if !required[flag.Name] && !flag.Hidden && flag.Name != "help" {
				fmt.Fprintf(out, "  --%s  %s\n", flag.Name, flag.Usage)
			}
		})
		fmt.Fprintln(out, "\nCommon options: --store SLUG, --profile NAME, --output FORMAT, --dry-run, --yes")
		fmt.Fprintf(out, "\nExample:\n  %s\n\nEffect: %s\nAPI reference: %s\n", entry.Example, entry.Effect, entry.DocumentationURL)
		fmt.Fprintf(out, "\nUse %s --help --help-all for every option.\n", cmd.CommandPath())
	})
}
