// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"math/big"
	"sort"
	"strings"
)

func bodyFlagJSON(field CatalogBodyField, value string) (string, error) {
	field.Schema = nonNullFlagSchema(field.Schema)
	kind, _ := field.Schema["type"].(string)
	if kind == "string" {
		if choices, ok := field.Schema["enum"].([]any); ok {
			valid := false
			for _, choice := range choices {
				if fmt.Sprint(choice) == value {
					valid = true
				}
			}
			if !valid {
				return "", &UsageError{Message: fmt.Sprintf("--%s must be one of %v", field.Flag, choices)}
			}
		}
		encoded, _ := json.Marshal(value)
		return string(encoded), nil
	}
	decoder := json.NewDecoder(strings.NewReader(value))
	decoder.UseNumber()
	var decoded any
	if err := decoder.Decode(&decoded); err != nil || !json.Valid([]byte(value)) {
		return "", &UsageError{Message: "--" + field.Flag + " requires valid " + kind + " JSON"}
	}
	valid := true
	switch kind {
	case "integer":
		number, ok := decoded.(json.Number)
		valid = ok
		if ok {
			_, err := number.Int64()
			valid = err == nil
		}
	case "number":
		_, valid = decoded.(json.Number)
	case "boolean":
		_, valid = decoded.(bool)
	case "array":
		_, valid = decoded.([]any)
	case "object":
		_, valid = decoded.(map[string]any)
	}
	if !valid || decoded == nil {
		return "", &UsageError{Message: "--" + field.Flag + " requires " + kind + "; use --set " + field.Name + "=null for explicit null"}
	}
	if choices, ok := field.Schema["enum"].([]any); ok {
		valid = false
		for _, choice := range choices {
			encoded, _ := json.Marshal(choice)
			if jsonScalarEqual(string(encoded), strings.TrimSpace(value)) {
				valid = true
			}
		}
		if !valid {
			return "", &UsageError{Message: fmt.Sprintf("--%s must be one of %v", field.Flag, choices)}
		}
	}
	return value, nil
}

func missingNestedInputs(schema map[string]any, value any, path string) []string {
	if value == nil {
		return nil
	}
	schema = nonNullFlagSchema(schema)
	missing := []string{}
	for _, keyword := range []string{"oneOf", "anyOf"} {
		if variants, ok := schema[keyword].([]any); ok {
			candidates := []map[string]any{}
			for _, variant := range variants {
				if candidate, ok := variant.(map[string]any); ok && matchesInputDiscriminators(candidate, value) {
					candidates = append(candidates, candidate)
				}
			}
			if len(candidates) == 1 {
				return missingNestedInputs(candidates[0], value, path)
			}
		}
	}

	if object, ok := value.(map[string]any); ok {
		if required, ok := schema["required"].([]any); ok {
			for _, field := range required {
				name, _ := field.(string)
				if _, exists := object[name]; !exists {
					missing = append(missing, strings.TrimPrefix(path+"."+name, "."))
				}
			}
		}
		if properties, ok := schema["properties"].(map[string]any); ok {
			for name, child := range properties {
				if item, exists := object[name]; exists {
					if childSchema, ok := child.(map[string]any); ok {
						missing = append(missing, missingNestedInputs(childSchema, item, strings.TrimPrefix(path+"."+name, "."))...)
					}
				}
			}
		}
	}
	if array, ok := value.([]any); ok {
		if items, ok := schema["items"].(map[string]any); ok {
			for index, item := range array {
				missing = append(missing, missingNestedInputs(items, item, fmt.Sprintf("%s[%d]", path, index))...)
			}
		}
	}
	sort.Strings(missing)
	return missing
}

func matchesInputDiscriminators(schema map[string]any, value any) bool {
	if literal, ok := schema["const"]; ok {
		left, _ := json.Marshal(literal)
		right, _ := json.Marshal(value)
		return jsonScalarEqual(string(left), string(right))
	}
	if object, ok := value.(map[string]any); ok {
		if properties, ok := schema["properties"].(map[string]any); ok {
			for name, raw := range properties {
				if item, exists := object[name]; exists {
					if child, ok := raw.(map[string]any); ok && !matchesInputDiscriminators(child, item) {
						return false
					}
				}
			}
		}
	}
	if schema["type"] == "null" {
		return value == nil
	}
	return true
}

func jsonScalarEqual(left, right string) bool {
	if left == right {
		return true
	}
	a, ok := new(big.Rat).SetString(left)
	if !ok {
		return false
	}
	b, ok := new(big.Rat).SetString(right)
	return ok && a.Cmp(b) == 0
}

func commonScalarUnionSchema(original map[string]any, variants []any) map[string]any {
	kind := ""
	choices := []any{}
	restricted := true
	for _, raw := range variants {
		schema, ok := raw.(map[string]any)
		if !ok {
			return original
		}
		schema = nonNullFlagSchema(schema)
		current, _ := schema["type"].(string)
		if current == "null" {
			continue
		}
		if current != "string" && current != "integer" && current != "number" && current != "boolean" {
			return original
		}
		if kind != "" && kind != current {
			return original
		}
		kind = current
		if values, ok := schema["enum"].([]any); ok {
			choices = append(choices, values...)
		} else {
			restricted = false
		}
	}
	if kind == "" {
		return original
	}
	result := map[string]any{"type": kind}
	if restricted {
		result["enum"] = choices
	}
	return result
}

func nonNullFlagSchema(schema map[string]any) map[string]any {
	if kinds, ok := schema["type"].([]any); ok {
		nonNull := []any{}
		for _, kind := range kinds {
			if kind != "null" {
				nonNull = append(nonNull, kind)
			}
		}
		if len(nonNull) == 1 {
			copy := map[string]any{}
			for k, v := range schema {
				copy[k] = v
			}
			copy["type"] = nonNull[0]
			return copy
		}
	}

	for _, keyword := range []string{"anyOf", "oneOf"} {
		if variants, ok := schema[keyword].([]any); ok {
			var candidate map[string]any
			for _, raw := range variants {
				variant, ok := raw.(map[string]any)
				if !ok {
					return schema
				}
				if variant["type"] == "null" {
					continue
				}
				if candidate != nil {
					return commonScalarUnionSchema(schema, variants)
				}
				candidate = variant
			}
			if candidate != nil {
				return nonNullFlagSchema(candidate)
			}
		}
	}
	return schema
}
