// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
	"os"
	"strings"
	"testing"
)

func TestScalarUnionFlagsAcceptUnquotedEnumStrings(t *testing.T) {
	field := CatalogBodyField{Name: "grant_type", Flag: "grant-type", Schema: map[string]any{"anyOf": []any{map[string]any{"type": "string", "enum": []any{"authorization_code"}}, map[string]any{"type": "string", "enum": []any{"refresh_token"}}}}}
	if value, err := bodyFlagJSON(field, "refresh_token"); err != nil || value != "\"refresh_token\"" {
		t.Fatal(value, err)
	}
	if _, err := bodyFlagJSON(field, "invalid"); err == nil {
		t.Fatal("invalid union enum accepted")
	}
}
func TestConditionalRequiredInputRecovery(t *testing.T) {
	schema := map[string]any{"oneOf": []any{
		map[string]any{"type": "object", "properties": map[string]any{"grant_type": map[string]any{"const": "authorization_code"}}, "required": []any{"grant_type", "code"}},
		map[string]any{"type": "object", "properties": map[string]any{"grant_type": map[string]any{"const": "refresh_token"}}, "required": []any{"grant_type", "refresh_token"}},
	}}
	missing := missingNestedInputs(schema, map[string]any{"grant_type": "refresh_token"}, "")
	if len(missing) != 1 || missing[0] != "refresh_token" {
		t.Fatal(missing)
	}
}
func TestNestedRequiredInputRecovery(t *testing.T) {
	schema := map[string]any{"type": "array", "items": map[string]any{"type": "object", "required": []any{"price"}}}
	missing := missingNestedInputs(schema, []any{map[string]any{}}, "variants")
	if len(missing) != 1 || missing[0] != "variants[0].price" {
		t.Fatal(missing)
	}
	if len(missingNestedInputs(schema, nil, "variants")) != 0 {
		t.Fatal("null must remain distinct from a supplied object")
	}
}
func TestUploadConflictsAreRejected(t *testing.T) {
	for _, test := range []struct {
		body    string
		uploads []string
	}{{"{}", []string{"unknown=a"}}, {"{}", []string{"file=a", "file=b"}}, {"{\"file\":\"text\"}", []string{"file=a"}}} {
		cmd := &cobra.Command{}
		cfg := &Config{NoInteractive: true}
		body := test.body
		assignments := []string{}
		entry := CatalogEntry{Body: &CatalogBody{Fields: []CatalogBodyField{{Name: "file", Binary: true}}}}
		if err := prepareInvocation(cmd, cfg, entry, nil, &body, &assignments, test.uploads); err == nil {
			t.Fatal(test)
		}
	}
}
func TestRequiredBinaryInputsAreReportedBeforeCredentials(t *testing.T) {
	cmd := &cobra.Command{}
	cfg := &Config{NoInteractive: true}
	body := ""
	assignments := []string{}
	entry := CatalogEntry{Body: &CatalogBody{Required: true, Fields: []CatalogBodyField{{Name: "file", Required: true, Binary: true}}}}
	err := prepareInvocation(cmd, cfg, entry, nil, &body, &assignments, nil)
	if err == nil || !strings.Contains(FormatError(err), "--upload file=PATH") {
		t.Fatal(err)
	}
	body = ""
	if err = prepareInvocation(cmd, cfg, entry, nil, &body, &assignments, []string{"file=-"}); err != nil {
		t.Fatal(err)
	}
}
func TestScalarEnumUsesJSONValueEquality(t *testing.T) {
	for _, value := range []string{"1.0", "1e0", " 1 "} {
		if _, err := bodyFlagJSON(CatalogBodyField{Name: "value", Flag: "value", Schema: map[string]any{"type": "number", "enum": []any{1}}}, value); err != nil {
			t.Fatal(value, err)
		}
	}
	if _, err := bodyFlagJSON(CatalogBodyField{Name: "value", Flag: "value", Schema: map[string]any{"type": "boolean", "enum": []any{false}}}, "false"); err != nil {
		t.Fatal(err)
	}
}
func TestNullDeviceIsNotATerminal(t *testing.T) {
	file, err := os.Open(os.DevNull)
	if err != nil {
		t.Fatal(err)
	}
	defer file.Close()
	if isTerminalFile(file) {
		t.Fatal("null device must not trigger prompts or human output")
	}
}

func TestMissingInputsProvideMachineReadableRecovery(t *testing.T) {
	_, err := execute(t, "products", "create", "--title", "Design kit", "--dry-run")
	if err == nil {
		t.Fatal("missing required description accepted")
	}
	output := FormatError(err)
	if !strings.Contains(output, "missing_fields") || !strings.Contains(output, "description") || !strings.Contains(output, "visibility") || !strings.Contains(output, "suggestions") {
		t.Fatal(output)
	}
}

func TestRequiredFirstHelpAndDetailedOptions(t *testing.T) {
	output, err := execute(t, "products", "create", "--help")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(output, "Required inputs:") || !strings.Contains(output, "--description") || strings.Contains(output, "retries after the initial attempt") {
		t.Fatal(output)
	}
	output, err = execute(t, "products", "create", "--help", "--help-all")
	if err != nil || !strings.Contains(output, "--max-retries") {
		t.Fatal(output, err)
	}
}
func TestNumericEnumFlagRejectsUnknownValue(t *testing.T) {
	field := CatalogBodyField{Name: "level", Flag: "level", Schema: map[string]any{"type": "integer", "enum": []any{1, 2}}}
	if _, err := bodyFlagJSON(field, "3"); err == nil {
		t.Fatal("invalid numeric enum accepted")
	}
}
func TestNullableTypeArrayPreservesStrings(t *testing.T) {
	field := CatalogBodyField{Name: "value", Flag: "value", Schema: map[string]any{"type": []any{"string", "null"}}}
	if value, err := bodyFlagJSON(field, "false"); err != nil || value != "\"false\"" {
		t.Fatal(value, err)
	}
}
func TestTypedBodyFlags(t *testing.T) {
	for _, test := range []struct {
		kind, value, want string
		invalid           bool
	}{
		{"string", "hello", "\"hello\"", false}, {"boolean", "false", "false", false},
		{"integer", "12", "12", false}, {"integer", "12.5", "", true},
		{"number", "1.5", "1.5", false}, {"array", "[]", "[]", false},
		{"object", "{}", "{}", false}, {"boolean", "no", "", true},
	} {
		t.Run(test.kind+test.value, func(t *testing.T) {
			got, err := bodyFlagJSON(CatalogBodyField{Name: "value", Flag: "value", Schema: map[string]any{"type": test.kind}}, test.value)
			if (err != nil) != test.invalid || got != test.want {
				t.Fatalf("got %q, %v", got, err)
			}
		})
	}
}
func TestDuplicateBodyAssignmentsFail(t *testing.T) {
	for _, values := range [][]string{{"title=1", "title=2"}, {"title=null"}} {
		body := ""
		if len(values) == 1 {
			body = "{\"title\":1}"
		}
		if _, err := readJSONObject(body, values, strings.NewReader("")); err == nil {
			t.Fatal("expected conflicting input error")
		}
	}
}
func TestNullableStringFlagAcceptsUnquotedText(t *testing.T) {
	field := CatalogBodyField{Name: "description", Flag: "description", Schema: map[string]any{"anyOf": []any{map[string]any{"type": "string"}, map[string]any{"type": "null"}}}}
	got, err := bodyFlagJSON(field, "A useful description")
	if err != nil || got != "\"A useful description\"" {
		t.Fatalf("got %q, %v", got, err)
	}
}
func TestPositionalAndTypedCatalogInputs(t *testing.T) {
	for _, args := range [][]string{
		{"products", "get", "120", "--dry-run"},
		{"products", "create", "--title", "Design kit", "--description", "Templates for your next project.", "--visibility", "HIDDEN", "--dry-run"},
		{"commands", "products", "create", "--json"},
		{"docs", "products", "create"},
	} {
		if _, err := execute(t, args...); err != nil {
			t.Fatalf("%v: %v", args, err)
		}
	}
	if _, err := execute(t, "products", "get", "120", "--product", "121", "--dry-run"); err == nil {
		t.Fatal("expected positional conflict")
	}
}
