// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/spf13/cobra"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

var storageTransport http.RoundTripper = http.DefaultTransport

func workflowObject(value any) (map[string]any, error) {
	raw, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	var object map[string]any
	if err = json.Unmarshal(raw, &object); err != nil {
		return nil, err
	}
	return object, nil
}
func workflowData(value any) (map[string]any, error) {
	object, err := workflowObject(value)
	if err != nil {
		return nil, err
	}
	data, ok := object["data"].(map[string]any)
	if !ok {
		return nil, errors.New("workflow response omitted its data object")
	}
	return data, nil
}
func waitWorkflow(ctx context.Context, interval time.Duration) error {
	timer := time.NewTimer(interval)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

type eventCheckpoint struct {
	Binding string `json:"binding"`
	Cursor  string `json:"cursor"`
}

func saveCheckpoint(path string, checkpoint eventCheckpoint) error {
	data, err := json.Marshal(checkpoint)
	if err != nil {
		return err
	}
	file, err := os.CreateTemp(filepath.Dir(path), ".sellapp-cursor-*")
	if err != nil {
		return err
	}
	defer os.Remove(file.Name())
	if err = file.Chmod(0600); err == nil {
		_, err = file.Write(data)
	}
	if err == nil {
		err = file.Sync()
	}
	closeErr := file.Close()
	if err != nil {
		return err
	}
	if closeErr != nil {
		return closeErr
	}
	return os.Rename(file.Name(), path)
}
func eventsPollCommand(cfg *Config) *cobra.Command {
	var checkpoint, handler, eventType, subjectType, subjectID string
	var polls, limit int
	var interval time.Duration
	cmd := &cobra.Command{Use: "events-poll", Short: "Process cursor event pages and checkpoint only after the handler succeeds", Args: cobra.NoArgs, RunE: func(cmd *cobra.Command, _ []string) error {
		if polls < 1 || polls > 100 || limit < 1 || limit > 100 || interval < 0 {
			return &UsageError{Message: "--max-polls and --limit must be 1-100; --interval cannot be negative"}
		}
		if checkpoint == "" || handler == "" {
			return &UsageError{Message: "--checkpoint and --handler are required; handler receives each event JSON on stdin and must finish durable processing before exiting zero"}
		}
		if err := resolveProfileConfig(cfg); err != nil {
			return err
		}
		bindingBytes, _ := json.Marshal([]string{cfg.BaseURL, cfg.Profile, effectiveStore(cfg), eventType, subjectType, subjectID})
		binding := fmt.Sprintf("%x", sha256.Sum256(bindingBytes))
		position := eventCheckpoint{Binding: binding}
		if !cfg.DryRun {
			data, err := os.ReadFile(checkpoint)
			if err == nil {
				if json.Unmarshal(data, &position) != nil || position.Binding != binding {
					return &UsageError{Message: "checkpoint belongs to a different store, origin, profile, or filters"}
				}
			} else if !os.IsNotExist(err) {
				return err
			}
			lock, err := os.OpenFile(checkpoint+".lock", os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
			if err != nil {
				return errors.New("event checkpoint is locked by another process")
			}
			lock.Close()
			defer os.Remove(checkpoint + ".lock")
		}
		for poll := 0; poll < polls; poll++ {
			inv := workflowInvocation()
			inv.PageEnvelope = true
			inv.Query["limit"] = fmt.Sprint(limit)
			if position.Cursor != "" {
				inv.Query["cursor"] = position.Cursor
			}
			for key, value := range map[string]string{"type": eventType, "subject_type": subjectType, "subject_id": subjectID} {
				if value != "" {
					inv.Query[key] = value
				}
			}
			value, err := runWorkflowOperation(cmd, cfg, "listIntegrationEvents", inv, false)
			if err != nil {
				return err
			}
			if cfg.DryRun {
				return writeWorkflowResult(cfg, value)
			}
			object, err := workflowObject(value)
			if err != nil {
				return err
			}
			meta, ok := object["meta"].(map[string]any)
			if !ok {
				return errors.New("event response omitted cursor metadata")
			}
			next, ok := meta["next_cursor"].(string)
			if !ok || strings.TrimSpace(next) == "" {
				return errors.New("event response omitted next_cursor")
			}
			events, ok := object["data"].([]any)
			if !ok {
				return errors.New("event response omitted data array")
			}
			for _, event := range events {
				payload, err := json.Marshal(event)
				if err != nil {
					return err
				}
				process := exec.CommandContext(cmd.Context(), handler)
				process.Stdin = strings.NewReader(string(payload))
				process.Stdout = io.Discard
				process.Stderr = io.Discard
				if err = process.Run(); err != nil {
					return errors.New("event handler failed; checkpoint unchanged, already processed events may repeat")
				}
			}
			position.Cursor = next
			if err = saveCheckpoint(checkpoint, position); err != nil {
				return err
			}
			if poll+1 < polls {
				if err = waitWorkflow(cmd.Context(), interval); err != nil {
					return err
				}
			}
		}
		_, err := fmt.Fprintln(cfg.Stdout, "Event processing completed; checkpoint saved.")
		return err
	}}
	cmd.Flags().StringVar(&checkpoint, "checkpoint", "", "cursor checkpoint file")
	cmd.Flags().StringVar(&handler, "handler", "", "executable that durably processes one event JSON from stdin (no shell)")
	cmd.Flags().StringVar(&eventType, "type", "", "event type filter")
	cmd.Flags().StringVar(&subjectType, "subject-type", "", "subject type filter")
	cmd.Flags().StringVar(&subjectID, "subject-id", "", "subject ID filter")
	cmd.Flags().IntVar(&polls, "max-polls", 5, "maximum pages/polls (1-100)")
	cmd.Flags().IntVar(&limit, "limit", 50, "page size (1-100)")
	cmd.Flags().DurationVar(&interval, "interval", 2*time.Second, "poll interval")
	return cmd
}
func webhookInspectCommand(cfg *Config) *cobra.Command {
	var delivery, key string
	var replay bool
	cmd := &cobra.Command{Use: "webhook-delivery", Short: "Inspect a delivery and optionally queue a replay", Args: cobra.NoArgs, RunE: func(cmd *cobra.Command, _ []string) error {
		if delivery == "" {
			return &UsageError{Message: "--delivery is required"}
		}
		inv := workflowInvocation()
		inv.Path["delivery"] = delivery
		value, err := runWorkflowOperation(cmd, cfg, "getWebhookDelivery", inv, false)
		if err != nil {
			return err
		}
		if replay {
			if len(key) < 8 {
				return &UsageError{Message: "--idempotency-key (at least 8 characters) is required for replay; reuse it only with this same delivery"}
			}
			inv.Headers["Idempotency-Key"] = key
			value, err = runWorkflowOperation(cmd, cfg, "replayWebhookDelivery", inv, true)
			if err != nil {
				return err
			}
		}
		return writeWorkflowResult(cfg, value)
	}}
	cmd.Flags().StringVar(&delivery, "delivery", "", "delivery identifier")
	cmd.Flags().BoolVar(&replay, "replay", false, "queue a replay to the saved destination; this can send an external request")
	cmd.Flags().StringVar(&key, "idempotency-key", "", "stable replay key")
	return cmd
}
func exportPollInterval(value any, fallback time.Duration) (time.Duration, error) {
	object, err := workflowObject(value)
	if err != nil {
		return 0, err
	}
	meta, _ := object["meta"].(map[string]any)
	raw, exists := meta["poll_after_seconds"]
	if !exists {
		return fallback, nil
	}
	seconds, ok := raw.(float64)
	if !ok || seconds < 1 || seconds != float64(int64(seconds)) {
		return 0, errors.New("invalid export poll_after_seconds")
	}
	hint, err := time.ParseDuration(fmt.Sprintf("%gs", seconds))
	if err != nil {
		return 0, errors.New("export poll_after_seconds exceeds supported duration")
	}
	if hint > fallback {
		return hint, nil
	}
	return fallback, nil
}
func exportWorkflowCommand(cfg *Config) *cobra.Command {
	var exportID, kind, format, parameters, key, destination string
	var polls int
	var interval time.Duration
	cmd := &cobra.Command{Use: "export", Short: "Create or check an export, wait within a bound, and optionally download it", Args: cobra.NoArgs, RunE: func(cmd *cobra.Command, _ []string) error {
		if polls < 1 || polls > 100 || interval < 0 {
			return &UsageError{Message: "--max-polls must be 1-100 and --interval cannot be negative"}
		}
		id := exportID
		if id == "" {
			if kind == "" || len(key) < 8 {
				return &UsageError{Message: "--type and --idempotency-key (at least 8 characters) are required to create an export"}
			}
			var filters map[string]any
			if err := json.Unmarshal([]byte(parameters), &filters); err != nil {
				return &UsageError{Message: "--parameters must be a JSON object"}
			}
			inv := workflowInvocation()
			inv.Headers["Idempotency-Key"] = key
			inv.Body, _ = workflowBody(map[string]any{"type": kind, "format": format, "parameters": filters})
			value, err := runWorkflowOperation(cmd, cfg, "createExport", inv, true)
			if err != nil {
				return err
			}
			if cfg.DryRun {
				return writeWorkflowResult(cfg, value)
			}
			data, err := workflowData(value)
			if err != nil {
				return err
			}
			id, _ = data["id"].(string)
			if id == "" {
				return errors.New("created export response omitted id")
			}
			delay, err := exportPollInterval(value, interval)
			if err != nil {
				return err
			}
			if err = waitWorkflow(cmd.Context(), delay); err != nil {
				return err
			}
		}
		for poll := 0; poll < polls; poll++ {
			inv := workflowInvocation()
			inv.Path["export"] = id
			value, err := runWorkflowOperation(cmd, cfg, "getExport", inv, false)
			if err != nil {
				return err
			}
			if cfg.DryRun {
				return writeWorkflowResult(cfg, value)
			}
			data, err := workflowData(value)
			if err != nil {
				return err
			}
			status, _ := data["status"].(string)
			switch status {
			case "completed":
				if destination == "" {
					return writeWorkflowResult(cfg, value)
				}
				downloadURL, _ := data["download_url"].(string)
				return downloadWorkflowExport(cmd, cfg, id, downloadURL, destination)
			case "failed", "expired":
				return fmt.Errorf("export %s is %s; inspect its failure details before creating another export; no download was attempted", id, status)
			case "pending", "running":
			default:
				return errors.New("export returned an unknown status")
			}
			if poll+1 < polls {
				delay, err := exportPollInterval(value, interval)
				if err != nil {
					return err
				}
				if err = waitWorkflow(cmd.Context(), delay); err != nil {
					return err
				}
			}
		}
		return fmt.Errorf("export %s is still pending; resume with --export %s", id, id)
	}}
	cmd.Flags().StringVar(&exportID, "export", "", "existing export ID; omit to create")
	cmd.Flags().StringVar(&kind, "type", "", "documented export type")
	cmd.Flags().StringVar(&format, "format", "csv", "export format")
	cmd.Flags().StringVar(&parameters, "parameters", "{}", "export parameters JSON")
	cmd.Flags().StringVar(&key, "idempotency-key", "", "stable key for creating one export")
	cmd.Flags().StringVar(&destination, "file", "", "new file for completed export; existing files are refused")
	cmd.Flags().IntVar(&polls, "max-polls", 5, "maximum status requests (1-100)")
	cmd.Flags().DurationVar(&interval, "interval", 2*time.Second, "status polling interval")
	return cmd
}
func downloadWorkflowExport(cmd *cobra.Command, cfg *Config, id, source, destination string) error {
	base, err := url.Parse(cfg.BaseURL)
	if err != nil {
		return err
	}
	signed, err := url.Parse(source)
	if err != nil || signed.User != nil || signed.Fragment != "" || signed.Scheme != base.Scheme || signed.Host != base.Host || signed.Path != strings.TrimRight(base.Path, "/")+"/v2/exports/"+url.PathEscape(id)+"/download" {
		return errors.New("export returned an invalid download URL")
	}
	query, err := url.ParseQuery(signed.RawQuery)
	if err != nil || len(query["expires"]) != 1 || len(query["signature"]) != 1 {
		return errors.New("export download URL omitted signed parameters")
	}
	inv := workflowInvocation()
	inv.Path["export"] = id
	inv.Query["expires"] = query.Get("expires")
	inv.Query["signature"] = query.Get("signature")
	value, err := runWorkflowOperation(cmd, cfg, "downloadExport", inv, false)
	if err != nil {
		return err
	}
	object, err := workflowObject(value)
	if err != nil {
		return err
	}
	location, _ := object["location"].(string)
	target, err := url.Parse(location)
	if err != nil || target.Scheme != "https" || target.Host == "" || target.User != nil || target.Fragment != "" {
		return errors.New("export returned an invalid storage redirect")
	}
	request, err := http.NewRequestWithContext(cmd.Context(), "GET", target.String(), nil)
	if err != nil {
		return errors.New("cannot prepare storage download")
	}
	client := &http.Client{Timeout: cfg.Timeout, Transport: storageTransport, CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}
	response, err := client.Do(request)
	if err != nil {
		return errors.New("storage download failed")
	}
	defer response.Body.Close()
	if response.StatusCode != 200 {
		return fmt.Errorf("storage download failed (HTTP %d)", response.StatusCode)
	}
	file, err := os.OpenFile(destination, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		return err
	}
	success := false
	defer func() {
		file.Close()
		if !success {
			_ = os.Remove(destination)
		}
	}()
	written, copyErr := io.Copy(file, io.LimitReader(response.Body, (1<<30)+1))
	if copyErr != nil {
		return errors.New("storage download was incomplete")
	}
	if written > 1<<30 {
		return errors.New("storage download exceeds the 1 GiB limit")
	}
	if err = file.Sync(); err != nil {
		return err
	}
	if err = file.Close(); err != nil {
		return err
	}
	success = true
	return writeFormattedResult(cfg, map[string]any{"status": "downloaded", "export_id": id, "file": destination, "bytes": written})
}
