// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestEventsCheckpointOnlyAfterSuccessfulProcessing(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("shell fixture executable uses Unix")
	}
	for _, success := range []bool{false, true} {
		t.Run(map[bool]string{false: "failed", true: "succeeded"}[success], func(t *testing.T) {
			directory := t.TempDir()
			checkpoint := filepath.Join(directory, "cursor.json")
			handler := filepath.Join(directory, "handler")
			script := "#!/bin/sh\ncat >/dev/null\nexit 1\n"
			if success {
				script = "#!/bin/sh\ncat >/dev/null\nexit 0\n"
			}
			if err := os.WriteFile(handler, []byte(script), 0700); err != nil {
				t.Fatal(err)
			}
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				var page map[string]any
				_ = json.Unmarshal([]byte(responseFixture("GET /v2/events")), &page)
				page["meta"] = map[string]any{"next_cursor": "next-position", "has_more": false, "retention_days": 30}
				_ = json.NewEncoder(w).Encode(page)
			}))
			defer server.Close()
			args := append(baseArgs(server), "workflow", "events-poll", "--checkpoint", checkpoint, "--handler", handler, "--max-polls", "1")
			_, err := execute(t, args...)
			_, statErr := os.Stat(checkpoint)
			if success {
				if err != nil || statErr != nil {
					t.Fatalf("err=%v stat=%v", err, statErr)
				}
				data, _ := os.ReadFile(checkpoint)
				if !strings.Contains(string(data), "next-position") {
					t.Fatal("cursor missing")
				}
			} else if err == nil || !os.IsNotExist(statErr) {
				t.Fatalf("failed processing advanced cursor: %v %v", err, statErr)
			}
		})
	}
}
func TestEventWorkflowDryRunDoesNotCreateCheckpoint(t *testing.T) {
	checkpoint := filepath.Join(t.TempDir(), "cursor.json")
	_, err := execute(t, "--dry-run", "workflow", "events-poll", "--checkpoint", checkpoint, "--handler", "nonexistent-handler", "--max-polls", "1")
	if err != nil {
		t.Fatal(err)
	}
	if _, err = os.Stat(checkpoint); !os.IsNotExist(err) {
		t.Fatal("dry-run persisted checkpoint")
	}
}
func TestWebhookReplayUsesSuppliedKey(t *testing.T) {
	seen := []string{}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		seen = append(seen, r.Method)
		w.Header().Set("Content-Type", "application/json")
		if r.Method == "POST" {
			if r.Header.Get("Idempotency-Key") != "repeat-delivery-123" {
				t.Errorf("key=%s", r.Header.Get("Idempotency-Key"))
			}
			w.WriteHeader(201)
			_, _ = io.WriteString(w, responseFixture("POST /v2/webhook-deliveries/{delivery}/replay"))
		} else {
			_, _ = io.WriteString(w, responseFixture("GET /v2/webhook-deliveries/{delivery}"))
		}
	}))
	defer server.Close()
	args := append(baseArgs(server), "workflow", "webhook-delivery", "--delivery", "delivery-1", "--replay", "--idempotency-key", "repeat-delivery-123")
	if _, err := execute(t, args...); err != nil {
		t.Fatal(err)
	}
	if strings.Join(seen, ",") != "GET,POST" {
		t.Fatal(seen)
	}
}
func TestExportWorkflowCarriesCreatedID(t *testing.T) {
	paths := []string{}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		paths = append(paths, r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		key := "GET /v2/exports/{export}"
		if r.Method == "POST" {
			key = "POST /v2/exports"
			w.WriteHeader(201)
		}
		var body map[string]any
		_ = json.Unmarshal([]byte(responseFixture(key)), &body)
		data := body["data"].(map[string]any)
		data["id"] = "01992a65-e064-71ba-b38f-902b7966a6be"
		data["status"] = "completed"
		_ = json.NewEncoder(w).Encode(body)
	}))
	defer server.Close()
	args := append(baseArgs(server), "workflow", "export", "--type", "sales", "--idempotency-key", "create-export-123", "--max-polls", "1")
	if _, err := execute(t, args...); err != nil {
		t.Fatal(err)
	}
	if len(paths) != 2 || paths[1] != "/v2/exports/01992a65-e064-71ba-b38f-902b7966a6be" {
		t.Fatal(paths)
	}
}

func TestExportDownloadNeverSendsCredentialsToStorage(t *testing.T) {
	storageCalls := 0
	storage := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		storageCalls++
		for _, header := range []string{"Authorization", "X-STORE", "Cookie", "Idempotency-Key"} {
			if r.Header.Get(header) != "" {
				t.Errorf("credential leaked in %s", header)
			}
		}
		_, _ = io.WriteString(w, "export-bytes")
	}))
	defer storage.Close()
	previous := storageTransport
	storageTransport = storage.Client().Transport
	defer func() { storageTransport = previous }()
	id := "01992a65-e064-71ba-b38f-902b7966a6be"
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header.Get("Authorization") != "Bearer test-key" {
			t.Error("API first hop lost credential")
		}
		if strings.HasSuffix(r.URL.Path, "/download") {
			http.Redirect(w, r, storage.URL+"/private?signature=storage-secret", 302)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		var body map[string]any
		_ = json.Unmarshal([]byte(responseFixture("GET /v2/exports/{export}")), &body)
		data := body["data"].(map[string]any)
		data["id"] = id
		data["status"] = "completed"
		data["download_url"] = "http://" + r.Host + "/v2/exports/" + id + "/download?expires=1999999999&signature=api-secret"
		_ = json.NewEncoder(w).Encode(body)
	}))
	defer server.Close()
	destination := filepath.Join(t.TempDir(), "export.csv")
	args := append(baseArgs(server), "workflow", "export", "--export", id, "--file", destination, "--max-polls", "1")
	out, err := execute(t, args...)
	if err != nil {
		t.Fatal(err)
	}
	if storageCalls != 1 || strings.Contains(out, "secret") {
		t.Fatalf("calls=%d out=%s", storageCalls, out)
	}
	data, err := os.ReadFile(destination)
	if err != nil || string(data) != "export-bytes" {
		t.Fatal("download mismatch")
	}
}
