// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/modelcontextprotocol/go-sdk/jsonrpc"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/spf13/cobra"
)

type bridgeToken struct {
	AccessToken string `json:"access_token"`
	TokenType   string `json:"token_type"`
	ExpiresIn   int    `json:"expires_in"`
	Resource    string `json:"resource"`
	Scope       string `json:"scope"`
}
type bridgeAuthorization struct {
	mu        sync.Mutex
	cfg       Config
	profile   string
	record    profileRecord
	origin    string
	token     string
	expires   time.Time
	transport http.RoundTripper
}

func newBridgeAuthorization(cfg *Config) (*bridgeAuthorization, error) {
	doc, err := loadProfiles()
	if err != nil {
		return nil, err
	}
	name := cfg.Profile
	if name == "" {
		name = doc.Active
	}
	record, ok := doc.Profiles[name]
	if !ok || record.Method != "oauth" {
		return nil, &UsageError{Message: "MCP requires a saved OAuth profile. Run sellapp login, then sellapp mcp.", Suggestions: []string{"API-key profiles continue to work with ordinary CLI commands."}}
	}
	origin, err := oauthOrigin(record.Origin)
	if err != nil {
		return nil, err
	}
	candidate := *cfg
	candidate.Profile = name
	candidate.APIKey = ""
	candidate.AccessToken = ""
	candidate.CustomerSession = ""
	candidate.BrowserSession = ""
	candidate.DryRun = false
	if cfg.DryRun {
		return nil, &UsageError{Message: "MCP requires a live hosted connection; use ordinary CLI commands for --dry-run."}
	}
	if candidate.BaseURL != "" && (candidate.BaseURLExplicit || candidate.BaseURL != defaultBaseURL) {
		target, err := oauthOrigin(candidate.BaseURL)
		if err != nil || target != origin {
			return nil, &UsageError{Message: "MCP origin must match the selected OAuth profile."}
		}
	}
	candidate.BaseURL = origin + "/api"
	return &bridgeAuthorization{cfg: candidate, profile: name, record: record, origin: origin, transport: http.DefaultTransport}, nil
}

func (auth *bridgeAuthorization) credential(ctx context.Context) (string, error) {
	auth.mu.Lock()
	defer auth.mu.Unlock()
	if auth.token != "" && time.Until(auth.expires) > 15*time.Second {
		return auth.token, nil
	}
	doc, err := loadProfiles()
	if err != nil {
		return "", err
	}
	record, ok := doc.Profiles[auth.profile]
	if !ok || record.Method != "oauth" || record.VaultEntry != auth.record.VaultEntry || record.Origin != auth.record.Origin || record.ClientID != auth.record.ClientID {
		return "", errors.New("MCP profile changed or was disconnected; restart the bridge with the intended OAuth profile")
	}
	candidate := auth.cfg
	candidate.Context = ctx
	if err = resolveOAuth(record, &candidate); err != nil {
		return "", err
	}
	requestCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(requestCtx, http.MethodPost, auth.origin+"/oauth/mcp-token", strings.NewReader("{}"))
	if err != nil {
		return "", errors.New("cannot prepare MCP credential request")
	}
	req.Header.Set("Authorization", "Bearer "+candidate.AccessToken)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")
	client := &http.Client{Transport: auth.transport, CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}
	response, err := client.Do(req)
	if err != nil {
		return "", errors.New("MCP credential request failed; check the hosted connection")
	}
	defer response.Body.Close()
	raw, err := io.ReadAll(io.LimitReader(response.Body, (1<<20)+1))
	if err != nil || len(raw) > 1<<20 {
		return "", errors.New("invalid MCP credential response")
	}
	if response.StatusCode != http.StatusOK {
		if response.StatusCode == 401 {
			return "", errors.New("CLI connection expired, was revoked, or does not match the official registration; check sellapp auth status")
		}
		return "", fmt.Errorf("MCP credential endpoint returned HTTP %d; check server availability and CLI/server configuration", response.StatusCode)
	}
	var token bridgeToken
	if json.Unmarshal(raw, &token) != nil || token.AccessToken == "" || !strings.EqualFold(token.TokenType, "Bearer") || token.ExpiresIn <= 0 || token.ExpiresIn > 300 || token.Resource != auth.origin+"/mcp" || token.Scope != "admin" {
		return "", errors.New("MCP credential response has an invalid resource, lifetime or grant")
	}
	auth.token = token.AccessToken
	auth.expires = time.Now().Add(time.Duration(token.ExpiresIn) * time.Second)
	return auth.token, nil
}

func (auth *bridgeAuthorization) RoundTrip(req *http.Request) (*http.Response, error) {
	if req.URL.Scheme+"://"+req.URL.Host != auth.origin || req.URL.Path != "/mcp" || req.URL.User != nil || req.URL.Fragment != "" {
		return nil, errors.New("MCP transport refused a destination outside the selected OAuth profile")
	}
	token, err := auth.credential(req.Context())
	if err != nil {
		return nil, err
	}
	copy := req.Clone(req.Context())
	copy.Header = req.Header.Clone()
	copy.Header.Set("Authorization", "Bearer "+token)
	copy.Header.Del("Cookie")
	copy.Header.Del("X-STORE")
	// A failed request is never replayed here. In particular, a write may already have run.
	response, err := auth.transport.RoundTrip(copy)
	if response != nil && response.StatusCode == http.StatusUnauthorized {
		// A different CLI process may have refreshed the parent. Renew on the next
		// request through the locked profile machinery, without replaying this call.
		auth.mu.Lock()
		if auth.token == token {
			auth.token = ""
			auth.expires = time.Time{}
		}
		auth.mu.Unlock()
	}
	return response, err
}

type bridgeWriter struct{ io.Writer }

func (bridgeWriter) Close() error { return nil }

type bridgeTransport struct{ mcp.Connection }

func (t bridgeTransport) Connect(context.Context) (mcp.Connection, error) { return t.Connection, nil }

func mcpCommand(cfg *Config) *cobra.Command {
	mode := "compact"
	cmd := &cobra.Command{Use: "mcp", Short: "Bridge local agents to hosted Sell MCP using your CLI login", Args: cobra.NoArgs, RunE: func(cmd *cobra.Command, _ []string) error { return serveMCP(cmd.Context(), cfg, mode) }}
	cmd.Flags().StringVar(&mode, "mode", "compact", "hosted tool mode: compact, catalog, full, or retrieval")
	cmd.AddCommand(mcpSetupCommand(cfg), mcpDoctorCommand(cfg))
	return cmd
}
func serveMCP(ctx context.Context, cfg *Config, mode string) error {
	auth, err := newBridgeAuthorization(cfg)
	if err != nil {
		return err
	}
	if mode != "compact" && mode != "catalog" && mode != "full" && mode != "retrieval" {
		return &UsageError{Message: "--mode must be compact, catalog, full, or retrieval"}
	}
	local, err := (&mcp.IOTransport{Reader: os.Stdin, Writer: bridgeWriter{cfg.Stdout}}).Connect(ctx)
	if err != nil {
		return err
	}
	defer local.Close()
	return runMCPBridge(ctx, local, auth.origin+"/mcp?tool_mode="+url.QueryEscape(mode), &http.Client{Transport: auth, CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}, cfg.Stderr)
}

// The hosted runtime owns discovery, schemas, permissions and mutation confirmation.
// Middleware forwards typed protocol requests without rebuilding tool schemas locally.
func runMCPBridge(ctx context.Context, local mcp.Connection, endpoint string, httpClient *http.Client, diagnostics io.Writer) error {
	var initialized atomic.Bool
	logger := slog.New(slog.NewTextHandler(diagnostics, &slog.HandlerOptions{Level: slog.LevelError}))
	client := mcp.NewClient(&mcp.Implementation{Name: "sellapp-cli-bridge", Version: cliVersion}, &mcp.ClientOptions{Capabilities: &mcp.ClientCapabilities{}, Logger: logger})
	client.AddReceivingMiddleware(func(next mcp.MethodHandler) mcp.MethodHandler {
		return func(ctx context.Context, method string, req mcp.Request) (mcp.Result, error) {
			switch method {
			case "notifications/tools/list_changed", "notifications/prompts/list_changed", "notifications/resources/list_changed", "notifications/resources/updated", "notifications/progress", "notifications/message":
				if initialized.Load() {
					params, err := json.Marshal(req.GetParams())
					if err != nil {
						return nil, err
					}
					return nil, local.Write(ctx, &jsonrpc.Request{Method: method, Params: params})
				}
				return nil, nil
			}
			return next(ctx, method, req)
		}
	})
	upstream, err := client.Connect(ctx, &mcp.StreamableClientTransport{Endpoint: endpoint, HTTPClient: httpClient, MaxRetries: -1}, nil)
	if err != nil {
		return errors.New("Hosted MCP initialization failed; check sellapp mcp doctor")
	}
	defer upstream.Close()
	info := upstream.InitializeResult()
	server := mcp.NewServer(info.ServerInfo, &mcp.ServerOptions{Capabilities: info.Capabilities, Instructions: info.Instructions, Logger: logger})
	server.AddReceivingMiddleware(func(next mcp.MethodHandler) mcp.MethodHandler {
		return func(ctx context.Context, method string, req mcp.Request) (mcp.Result, error) {
			if method != "initialize" && method != "server/discover" {
				initialized.Store(true)
			}
			// Each transport negotiates its own protocol. Preserve application metadata
			// while allowing the upstream SDK to inject its own transport identity.
			if params := req.GetParams(); params != nil {
				meta := map[string]any{}
				for key, value := range params.GetMeta() {
					if key != mcp.MetaKeyProtocolVersion && key != mcp.MetaKeyClientInfo && key != mcp.MetaKeyClientCapabilities {
						meta[key] = value
					}
				}
				params.SetMeta(meta)
			}
			switch method {
			case "tools/list":
				return upstream.ListTools(ctx, req.(*mcp.ListToolsRequest).Params)
			case "tools/call":
				p := req.(*mcp.CallToolRequest).Params
				result, err := upstream.CallTool(ctx, &mcp.CallToolParams{Name: p.Name, Arguments: p.Arguments, Meta: p.Meta})
				if err != nil {
					var protocolError *jsonrpc.Error
					if errors.As(err, &protocolError) {
						return nil, protocolError
					}
					if ctx.Err() != nil {
						return nil, ctx.Err()
					}
					return nil, errors.New("Hosted MCP call failed; its outcome may be uncertain. Inspect the result before repeating a write.")
				}
				return result, nil
			case "resources/list":
				return upstream.ListResources(ctx, req.(*mcp.ListResourcesRequest).Params)
			case "resources/templates/list":
				return upstream.ListResourceTemplates(ctx, req.(*mcp.ListResourceTemplatesRequest).Params)
			case "resources/read":
				return upstream.ReadResource(ctx, req.(*mcp.ReadResourceRequest).Params)
			case "prompts/list":
				return upstream.ListPrompts(ctx, req.(*mcp.ListPromptsRequest).Params)
			case "prompts/get":
				return upstream.GetPrompt(ctx, req.(*mcp.GetPromptRequest).Params)
			case "notifications/initialized":
				result, err := next(ctx, method, req)
				if err == nil {
					initialized.Store(true)
				}
				return result, err
			case "ping":
				if err := upstream.Ping(ctx, req.(*mcp.ServerRequest[*mcp.PingParams]).Params); err != nil {
					return nil, errors.New("Hosted MCP connection is unavailable")
				}
			}
			return next(ctx, method, req)
		}
	})
	err = server.Run(ctx, bridgeTransport{local})
	// A client can close its pipe while a cancelled request's response is in flight.
	// Treat that local disconnect like EOF; never replay the upstream operation.
	if errors.Is(err, io.EOF) || errors.Is(err, io.ErrClosedPipe) || errors.Is(err, context.Canceled) || strings.Contains(fmt.Sprint(err), "server is closing: EOF") {
		return nil
	}
	return err
}
