// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/modelcontextprotocol/go-sdk/jsonrpc"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

// Protocol versions may add transport metadata; business schemas/results must match.
func bridgeBusinessJSON(value any) []byte {
	raw, _ := json.Marshal(value)
	var object map[string]any
	json.Unmarshal(raw, &object)
	delete(object, "resultType")
	if meta, ok := object["_meta"].(map[string]any); ok {
		delete(meta, mcp.MetaKeyServerInfo)
		if len(meta) == 0 {
			delete(object, "_meta")
		}
	}
	raw, _ = json.Marshal(object)
	return raw
}
func bridgeTestSession(t *testing.T, host *mcp.Server, jsonResponse bool, opts *mcp.ClientOptions) (*mcp.ClientSession, *mcp.ClientSession, func()) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	handler := mcp.NewStreamableHTTPHandler(func(*http.Request) *mcp.Server { return host }, &mcp.StreamableHTTPOptions{JSONResponse: jsonResponse})
	httpServer := httptest.NewServer(handler)
	left, right := mcp.NewInMemoryTransports()
	local, err := left.Connect(ctx)
	if err != nil {
		t.Fatal(err)
	}
	done := make(chan error, 1)
	var diagnostics bytes.Buffer
	go func() { done <- runMCPBridge(ctx, local, httpServer.URL, httpServer.Client(), &diagnostics) }()
	client := mcp.NewClient(&mcp.Implementation{Name: "test", Version: "1"}, opts)
	session, err := client.Connect(ctx, right, nil)
	if err != nil {
		cancel()
		httpServer.Close()
		t.Fatal(err)
	}
	direct, err := mcp.NewClient(&mcp.Implementation{Name: "direct", Version: "1"}, nil).Connect(ctx, &mcp.StreamableClientTransport{Endpoint: httpServer.URL, HTTPClient: httpServer.Client(), MaxRetries: -1}, nil)
	if err != nil {
		t.Fatal(err)
	}
	return session, direct, func() {
		session.Close()
		direct.Close()
		select {
		case err := <-done:
			if err != nil {
				t.Error(err)
			}
		case <-time.After(2 * time.Second):
			t.Error("bridge did not stop on EOF")
		}
		cancel()
		httpServer.Close()
	}
}
func testBridgeDiscoveryAndCall(t *testing.T, jsonResponse bool) {
	host := mcp.NewServer(&mcp.Implementation{Name: "Sell MCP", Version: "3.0.0"}, &mcp.ServerOptions{Instructions: "hosted instructions"})
	tool := &mcp.Tool{Name: "sellapp_write", Description: "hosted contract", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"value": map[string]any{"type": "integer"}}, "required": []string{"value"}, "additionalProperties": false}}
	host.AddTool(tool, func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return &mcp.CallToolResult{Content: []mcp.Content{&mcp.TextContent{Text: "prepared"}}, StructuredContent: map[string]any{"state": "prepared", "preview": json.RawMessage(req.Params.Arguments), "mcp_confirmation_token": "fixture-confirmation"}}, nil
	})
	host.AddReceivingMiddleware(func(next mcp.MethodHandler) mcp.MethodHandler {
		return func(ctx context.Context, method string, req mcp.Request) (mcp.Result, error) {
			if method == "tools/list" {
				cursor := req.(*mcp.ListToolsRequest).Params.Cursor
				if cursor == "" {
					return &mcp.ListToolsResult{Tools: []*mcp.Tool{tool}, NextCursor: "opaque-page-2"}, nil
				}
				if cursor == "opaque-page-2" {
					return &mcp.ListToolsResult{Tools: []*mcp.Tool{tool}}, nil
				}
				return nil, &jsonrpc.Error{Code: -32602, Message: "invalid cursor"}
			}
			return next(ctx, method, req)
		}
	})
	session, direct, close := bridgeTestSession(t, host, jsonResponse, nil)
	defer close()
	if session.InitializeResult().ServerInfo.Name != "Sell MCP" || session.InitializeResult().Instructions != "hosted instructions" {
		t.Fatal("hosted identity/instructions changed")
	}
	for _, cursor := range []string{"", "opaque-page-2"} {
		bridged, err := session.ListTools(context.Background(), &mcp.ListToolsParams{Cursor: cursor})
		if err != nil {
			t.Fatal(err)
		}
		native, err := direct.ListTools(context.Background(), &mcp.ListToolsParams{Cursor: cursor})
		if err != nil {
			t.Fatal(err)
		}
		a := bridgeBusinessJSON(bridged)
		b := bridgeBusinessJSON(native)
		if !bytes.Equal(a, b) {
			t.Fatalf("schema/page changed: %s != %s", a, b)
		}
	}
	args := &mcp.CallToolParams{Name: "sellapp_write", Arguments: map[string]any{"value": 42}}
	a, err := session.CallTool(context.Background(), args)
	if err != nil {
		t.Fatal(err)
	}
	b, err := direct.CallTool(context.Background(), &mcp.CallToolParams{Name: "sellapp_write", Arguments: map[string]any{"value": 42}})
	if err != nil {
		t.Fatal(err)
	}
	left := bridgeBusinessJSON(a)
	right := bridgeBusinessJSON(b)
	if !bytes.Equal(left, right) {
		t.Fatalf("result changed: %s != %s", left, right)
	}
	if _, err = session.ListTools(context.Background(), &mcp.ListToolsParams{Cursor: "invalid"}); err == nil {
		t.Fatal("protocol error lost")
	}
}
func TestBridgeSSEResultsAndPagination(t *testing.T) { testBridgeDiscoveryAndCall(t, false) }

type bridgeFailedConnection struct{ err error }

func (c bridgeFailedConnection) Read(context.Context) (jsonrpc.Message, error) { return nil, c.err }
func (c bridgeFailedConnection) Write(context.Context, jsonrpc.Message) error  { return c.err }
func (bridgeFailedConnection) Close() error                                    { return nil }
func (bridgeFailedConnection) SessionID() string                               { return "" }
func TestBridgeLocalDisconnectAndUnexpectedTransportFailure(t *testing.T) {
	unexpected := errors.New("unexpected local transport failure")
	for _, test := range []struct {
		name      string
		failure   error
		wantError bool
	}{{"closed pipe", io.ErrClosedPipe, false}, {"wrapped closed pipe", fmt.Errorf("response write: %w", io.ErrClosedPipe), false}, {"unexpected", unexpected, true}} {
		t.Run(test.name, func(t *testing.T) {
			host := mcp.NewServer(&mcp.Implementation{Name: "Sell MCP", Version: "3.2.0"}, nil)
			server := httptest.NewServer(mcp.NewStreamableHTTPHandler(func(*http.Request) *mcp.Server { return host }, nil))
			defer server.Close()
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
			defer cancel()
			err := runMCPBridge(ctx, bridgeFailedConnection{test.failure}, server.URL, server.Client(), io.Discard)
			if test.wantError {
				if !errors.Is(err, unexpected) {
					t.Fatalf("unexpected transport error was lost: %v", err)
				}
			} else if err != nil {
				t.Fatalf("normal local disconnect failed: %v", err)
			}
		})
	}
}
func TestBridgeCancellationAndNotifications(t *testing.T) {
	host := mcp.NewServer(&mcp.Implementation{Name: "Sell MCP", Version: "3"}, nil)
	started := make(chan struct{})
	cancelled := make(chan struct{})
	host.AddTool(&mcp.Tool{Name: "wait", InputSchema: map[string]any{"type": "object"}}, func(ctx context.Context, _ *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		close(started)
		<-ctx.Done()
		close(cancelled)
		return nil, ctx.Err()
	})
	notified := make(chan struct{}, 1)
	session, _, cleanup := bridgeTestSession(t, host, false, &mcp.ClientOptions{ToolListChangedHandler: func(context.Context, *mcp.ToolListChangedRequest) {
		select {
		case notified <- struct{}{}:
		default:
		}
	}})
	defer cleanup()
	// Complete a request before changing tools so initialization has been handled.
	if _, err := session.ListTools(context.Background(), nil); err != nil {
		t.Fatal(err)
	}
	host.AddTool(&mcp.Tool{Name: "new_tool", InputSchema: map[string]any{"type": "object"}}, func(context.Context, *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return &mcp.CallToolResult{}, nil
	})
	select {
	case <-notified:
	case <-time.After(2 * time.Second):
		t.Fatal("list_changed notification lost")
	}
	ctx, cancel := context.WithCancel(context.Background())
	done := make(chan error, 1)
	go func() {
		_, err := session.CallTool(ctx, &mcp.CallToolParams{Name: "wait", Arguments: map[string]any{}})
		done <- err
	}()
	select {
	case <-started:
	case <-time.After(2 * time.Second):
		t.Fatal("call never started")
	}
	cancel()
	select {
	case <-cancelled:
	case <-time.After(2 * time.Second):
		t.Fatal("cancellation did not reach hosted server")
	}
	if err := <-done; err == nil {
		t.Fatal("cancelled call succeeded")
	}
}

type bridgeRoundTripFunc func(*http.Request) (*http.Response, error)

func (f bridgeRoundTripFunc) RoundTrip(req *http.Request) (*http.Response, error) { return f(req) }
func TestBridgePinsOriginAndNeverReplaysMutation(t *testing.T) {
	calls := 0
	auth := &bridgeAuthorization{origin: "https://sell.app", token: "secret-child", expires: time.Now().Add(time.Minute), transport: bridgeRoundTripFunc(func(req *http.Request) (*http.Response, error) {
		calls++
		if req.Header.Get("Authorization") != "Bearer secret-child" || req.Header.Get("Cookie") != "" || req.Header.Get("X-STORE") != "" {
			t.Fatal("wrong credential boundary")
		}
		return nil, errors.New("uncertain transport failure")
	})}
	req, _ := http.NewRequest("POST", "https://sell.app/mcp", strings.NewReader("mutation"))
	req.Header.Set("Cookie", "session")
	req.Header.Set("X-STORE", "wrong")
	if _, err := auth.RoundTrip(req); err == nil {
		t.Fatal("transport failure lost")
	}
	if calls != 1 {
		t.Fatal("mutation replayed")
	}
	for _, target := range []string{"https://other.example/mcp", "https://sell.app/api/v2/orders", "https://user@sell.app/mcp"} {
		req, _ = http.NewRequest("POST", target, nil)
		if _, err := auth.RoundTrip(req); err == nil {
			t.Fatal("untrusted destination accepted")
		}
	}
	if calls != 1 {
		t.Fatal("credentials reached untrusted destination")
	}
}
func TestBridgeInvalidatesRejectedChildWithoutReplayingTheRequest(t *testing.T) {
	calls := 0
	auth := &bridgeAuthorization{origin: "https://sell.app", token: "revoked-child", expires: time.Now().Add(time.Minute), transport: bridgeRoundTripFunc(func(req *http.Request) (*http.Response, error) {
		calls++
		return &http.Response{StatusCode: http.StatusUnauthorized, Body: io.NopCloser(strings.NewReader("{}")), Header: make(http.Header)}, nil
	})}
	req, _ := http.NewRequest("POST", "https://sell.app/mcp", strings.NewReader("mutation"))
	response, err := auth.RoundTrip(req)
	if err != nil {
		t.Fatal(err)
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusUnauthorized || calls != 1 {
		t.Fatal("rejected request was hidden or replayed")
	}
	if auth.token != "" || !auth.expires.IsZero() {
		t.Fatal("rejected child remained cached")
	}
}
func TestBridgeAPIKeyProfileRequiresLogin(t *testing.T) {
	credentialTestHome(t)
	doc, _ := loadProfiles()
	doc.Active = "key"
	doc.Profiles["key"] = profileRecord{Method: "api_key", Origin: "https://sell.app", VaultEntry: "key"}
	if err := saveProfiles(doc); err != nil {
		t.Fatal(err)
	}
	if _, err := newBridgeAuthorization(&Config{}); err == nil || !strings.Contains(err.Error(), "sellapp login") {
		t.Fatal(err)
	}
}
func TestBridgeChildCredentialsAreMemoryOnlyAndProfileBound(t *testing.T) {
	credentialTestHome(t)
	old := credentialVaultRead
	defer func() { credentialVaultRead = old }()
	credentialVaultRead = func(string) (string, error) {
		raw, _ := json.Marshal(oauthPair{AccessToken: "parent", RefreshToken: "refresh", ExpiresAt: time.Now().Add(time.Hour)})
		return string(raw), nil
	}
	var requests atomic.Int32
	var origin string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests.Add(1)
		if r.URL.Path != "/oauth/mcp-token" || r.Header.Get("Authorization") != "Bearer parent" {
			t.Error("wrong parent issuance request")
		}
		json.NewEncoder(w).Encode(map[string]any{"access_token": "child", "token_type": "Bearer", "scope": "admin", "resource": origin + "/mcp", "expires_in": 300})
	}))
	defer server.Close()
	origin = server.URL
	doc, _ := loadProfiles()
	doc.Active = "oauth"
	doc.Profiles["oauth"] = profileRecord{Method: "oauth", Origin: origin, VaultEntry: "parent-vault", ClientID: "official"}
	if err := saveProfiles(doc); err != nil {
		t.Fatal(err)
	}
	auth, err := newBridgeAuthorization(&Config{})
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 2; i++ {
		if token, err := auth.credential(context.Background()); err != nil || token != "child" {
			t.Fatal(err)
		}
	}
	if requests.Load() != 1 {
		t.Fatal("child cache missed")
	}
	auth.expires = time.Now()
	doc.Profiles["oauth"] = profileRecord{Method: "oauth", Origin: "https://another.example", VaultEntry: "parent-vault", ClientID: "official"}
	if err := saveProfiles(doc); err != nil {
		t.Fatal(err)
	}
	if _, err = auth.credential(context.Background()); err == nil {
		t.Fatal("profile origin change accepted")
	}
	if requests.Load() != 1 {
		t.Fatal("changed profile contacted old origin")
	}
}
func TestBridgeMalformedStdioDoesNotExecuteBusinessCalls(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	var out bytes.Buffer
	conn, err := (&mcp.IOTransport{Reader: io.NopCloser(strings.NewReader("{not-json}\n")), Writer: bridgeWriter{&out}}).Connect(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close()
	if _, err = conn.Read(ctx); err == nil {
		t.Fatal("malformed message accepted")
	}
}

func TestBridgeDocumentationSchemasResultsAndErrors(t *testing.T) {
	for _, jsonResponse := range []bool{true, false} {
		t.Run(fmt.Sprint(jsonResponse), func(t *testing.T) {
			host := mcp.NewServer(&mcp.Implementation{Name: "Sell MCP", Version: "3.1.0"}, nil)
			for _, name := range []string{"sellapp_search_docs", "sellapp_get_doc"} {
				toolName := name
				host.AddTool(&mcp.Tool{Name: toolName, Description: "Public documentation", InputSchema: map[string]any{"type": "object", "properties": map[string]any{"path": map[string]any{"type": "string"}}, "additionalProperties": false}, Annotations: &mcp.ToolAnnotations{ReadOnlyHint: true}}, func(_ context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
					var args map[string]any
					json.Unmarshal(req.Params.Arguments, &args)
					result := map[string]any{"state": "completed", "data": map[string]any{"path": "/docs/api/webhooks", "url": "https://sell.app/docs/api/webhooks", "markdown": "# Webhooks", "revision": strings.Repeat("a", 64), "next_offset": 1000}}
					failed := args["path"] == "/missing"
					if failed {
						result = map[string]any{"state": "error", "error": map[string]any{"code": "document_not_found"}}
					}
					raw, _ := json.Marshal(result)
					return &mcp.CallToolResult{IsError: failed, Content: []mcp.Content{&mcp.TextContent{Text: string(raw)}}, StructuredContent: result}, nil
				})
			}
			session, direct, close := bridgeTestSession(t, host, jsonResponse, nil)
			defer close()
			a, err := session.ListTools(context.Background(), nil)
			if err != nil {
				t.Fatal(err)
			}
			b, err := direct.ListTools(context.Background(), nil)
			if err != nil {
				t.Fatal(err)
			}
			if len(a.Tools) != 2 || !bytes.Equal(bridgeBusinessJSON(a), bridgeBusinessJSON(b)) {
				t.Fatal("documentation tool schemas changed")
			}
			for _, name := range []string{"sellapp_search_docs", "sellapp_get_doc"} {
				for _, path := range []string{"/docs/api/webhooks", "/missing"} {
					args := &mcp.CallToolParams{Name: name, Arguments: map[string]any{"path": path}}
					a, err := session.CallTool(context.Background(), args)
					if err != nil {
						t.Fatal(err)
					}
					b, err := direct.CallTool(context.Background(), &mcp.CallToolParams{Name: name, Arguments: map[string]any{"path": path}})
					if err != nil {
						t.Fatal(err)
					}
					if !bytes.Equal(bridgeBusinessJSON(a), bridgeBusinessJSON(b)) {
						t.Fatal("documentation result or error changed")
					}
				}
			}
		})
	}
}

func TestBridgeModernHeadersCatalogArgumentsAndAppResources(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	host := mcp.NewServer(&mcp.Implementation{Name: "Sell MCP", Version: "3.2.0"}, &mcp.ServerOptions{Instructions: "Inspect business state."})
	schema := map[string]any{"type": "object", "properties": map[string]any{"store": map[string]any{"type": "string", "x-mcp-header": "Store"}, "body": map[string]any{"type": "object"}}}
	host.AddTool(&mcp.Tool{Name: "sellapp_read", InputSchema: schema, Meta: mcp.Meta{"ui": map[string]any{"resourceUri": "ui://sellapp/result-v1"}}}, func(_ context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return &mcp.CallToolResult{Meta: mcp.Meta{"sellapp/result": map[string]any{"revision": "fixture"}}, StructuredContent: map[string]any{"state": "prepared", "arguments": json.RawMessage(req.Params.Arguments)}, Content: []mcp.Content{&mcp.TextContent{Text: "prepared"}}}, nil
	})
	host.AddResource(&mcp.Resource{Name: "viewer", URI: "ui://sellapp/result-v1", MIMEType: "text/html;profile=mcp-app"}, func(_ context.Context, req *mcp.ReadResourceRequest) (*mcp.ReadResourceResult, error) {
		return &mcp.ReadResourceResult{Cacheable: mcp.Cacheable{TTLMs: 300000, CacheScope: "public"}, Meta: mcp.Meta{"sellapp/resource": "fixture"}, Contents: []*mcp.ResourceContents{{URI: req.Params.URI, MIMEType: "text/html;profile=mcp-app", Text: "<h1>Sell result</h1>"}}}, nil
	})
	host.AddReceivingMiddleware(func(next mcp.MethodHandler) mcp.MethodHandler {
		return func(ctx context.Context, method string, req mcp.Request) (mcp.Result, error) {
			result, err := next(ctx, method, req)
			if listed, ok := result.(*mcp.ListToolsResult); ok {
				listed.Cacheable = mcp.Cacheable{TTLMs: 30000, CacheScope: "private"}
			}
			return result, err
		}
	})
	handler := mcp.NewStreamableHTTPHandler(func(*http.Request) *mcp.Server { return host }, &mcp.StreamableHTTPOptions{JSONResponse: true, Stateless: true})
	var discovered, called atomic.Int32
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == "POST" {
			raw, err := io.ReadAll(r.Body)
			if err != nil {
				t.Error(err)
			}
			r.Body = io.NopCloser(bytes.NewReader(raw))
			var message struct {
				Method string
				Params map[string]any
			}
			if json.Unmarshal(raw, &message) != nil {
				t.Error("invalid bridge JSON")
			}
			if message.Method == "server/discover" {
				discovered.Add(1)
			}
			if !strings.HasPrefix(message.Method, "notifications/") {
				if r.Header.Get("Mcp-Method") != message.Method || r.Header.Get("MCP-Protocol-Version") != "2026-07-28" || r.Header.Get("Mcp-Session-Id") != "" {
					t.Error("incorrect modern transport headers")
				}
			}
			if message.Method == "resources/read" && r.Header.Get("Mcp-Name") != message.Params["uri"] {
				t.Error("resource name header lost")
			}
			if message.Method == "tools/call" {
				called.Add(1)
				if r.Header.Get("Mcp-Name") != "sellapp_read" || r.Header.Get("Mcp-Param-Store") != "approved" {
					t.Error("name or store header lost")
				}
				meta := message.Params["_meta"].(map[string]any)
				info := meta[mcp.MetaKeyClientInfo].(map[string]any)
				if meta["sellapp/trace"] != "preserved" {
					t.Error("application metadata lost")
				}
				if info["name"] != "sellapp-cli-bridge" {
					t.Error("upstream transport identity was not replaced")
				}
			}
		}
		handler.ServeHTTP(w, r)
	}))
	defer server.Close()
	left, right := mcp.NewInMemoryTransports()
	local, err := left.Connect(ctx)
	if err != nil {
		t.Fatal(err)
	}
	done := make(chan error, 1)
	var diagnostics bytes.Buffer
	go func() { done <- runMCPBridge(ctx, local, server.URL, server.Client(), &diagnostics) }()
	session, err := mcp.NewClient(&mcp.Implementation{Name: "local-agent", Version: "1"}, nil).Connect(ctx, right, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		session.Close()
		select {
		case err := <-done:
			if err != nil {
				t.Error(err)
			}
		case <-time.After(2 * time.Second):
			t.Error("bridge did not stop")
		}
	}()
	if session.InitializeResult().ProtocolVersion != "2026-07-28" {
		t.Fatal("modern discovery was not negotiated")
	}
	listed, err := session.ListTools(ctx, nil)
	if err != nil {
		t.Fatal(err)
	}
	if listed.TTLMs != 30000 || listed.CacheScope != "private" {
		t.Fatal("discovery cache hints lost")
	}
	if len(listed.Tools) != 1 || listed.Tools[0].Meta["ui"] == nil {
		t.Fatal("app metadata was lost")
	}
	args := map[string]any{"store": "approved", "body": map[string]any{"empty": map[string]any{}, "array": []any{}, "null": nil, "text": "  untouched  "}}
	result, err := session.CallTool(ctx, &mcp.CallToolParams{Name: "sellapp_read", Arguments: args, Meta: mcp.Meta{"sellapp/trace": "preserved", mcp.MetaKeyClientInfo: map[string]any{"name": "wrong-upstream-identity"}}})
	if err != nil {
		t.Fatal(err)
	}
	if result.Meta["sellapp/result"] == nil {
		t.Fatal("application result metadata lost")
	}
	raw, _ := json.Marshal(result.StructuredContent)
	var structured struct {
		State     string
		Arguments map[string]any
	}
	if json.Unmarshal(raw, &structured) != nil {
		t.Fatal("invalid structured result")
	}
	want, _ := json.Marshal(args)
	got, _ := json.Marshal(structured.Arguments)
	if structured.State != "prepared" || !bytes.Equal(got, want) {
		t.Fatalf("business state or exact JSON changed: %s", raw)
	}
	resource, err := session.ReadResource(ctx, &mcp.ReadResourceParams{URI: "ui://sellapp/result-v1"})
	if err != nil {
		t.Fatal(err)
	}
	if resource.TTLMs != 300000 || resource.CacheScope != "public" || resource.Meta["sellapp/resource"] != "fixture" {
		t.Fatal("resource cache hints or metadata lost")
	}
	if len(resource.Contents) != 1 || resource.Contents[0].Text != "<h1>Sell result</h1>" {
		t.Fatal("app resource changed")
	}
	if discovered.Load() != 1 || called.Load() != 1 {
		t.Fatal("discovery or call was repeated")
	}
}
