// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"os/exec"
	"strings"
	"testing"
	"time"
)

func TestOAuthLoginSuccessDescribesOnlyReturnedScopes(t *testing.T) {
	for _, test := range []struct{ name, response, message string }{
		{"omitted", "{}", "Connected successfully."},
		{"empty", "{\"scope\":\"\"}", "Connected successfully."},
		{"whitespace", "{\"scope\":\"   \"}", "Connected successfully."},
		{"granted", "{\"scope\":\"stores:read products:read\"}", "Granted scopes: stores:read products:read."},
	} {
		t.Run(test.name, func(t *testing.T) {
			var pair oauthPair
			if err := json.Unmarshal([]byte(test.response), &pair); err != nil {
				t.Fatal(err)
			}
			var output strings.Builder
			if err := writeOAuthLoginSuccess(&output, "default", pair.Scope); err != nil {
				t.Fatal(err)
			}
			want := "Saved OAuth profile default. " + test.message + " Select a store with stores use after listing accessible stores.\n"
			if output.String() != want {
				t.Fatalf("unexpected login message: %q", output.String())
			}
		})
	}
}
func TestAuthorizationURLCanBeCopiedWithoutJSONDecoding(t *testing.T) {
	address := "https://example.com/oauth/authorize?client_id=public-client&code_challenge=challenge&code_challenge_method=S256&redirect_uri=http%3A%2F%2F127.0.0.1%3A42189%2Fcallback&response_type=code&scope=stores%3Aread+products%3Aread&state=random-state"
	var output strings.Builder
	if err := writeAuthorizationURL(&output, address); err != nil {
		t.Fatal(err)
	}
	raw := output.String()
	if strings.Count(raw, "\n") != 1 {
		t.Fatal("expected one JSONL event")
	}
	var event map[string]any
	if err := json.Unmarshal([]byte(raw), &event); err != nil {
		t.Fatal(err)
	}
	if event["type"] != "authorization_url" || event["url"] != address || event["timeout_seconds"] != float64(300) {
		t.Fatal("authorization event changed")
	}
	_, tail, ok := strings.Cut(raw, "\"url\":\"")
	if !ok {
		t.Fatal("missing URL")
	}
	copied, _, ok := strings.Cut(tail, "\"")
	if !ok || copied != address {
		t.Fatal("printed URL requires JSON decoding")
	}
	parsed, err := url.Parse(copied)
	if err != nil {
		t.Fatal(err)
	}
	for key, want := range map[string]string{"client_id": "public-client", "code_challenge": "challenge", "code_challenge_method": "S256", "state": "random-state", "scope": "stores:read products:read", "redirect_uri": "http://127.0.0.1:42189/callback"} {
		if parsed.Query().Get(key) != want {
			t.Fatalf("missing or altered %s", key)
		}
	}
}
func TestOAuthFailureExitMatrix(t *testing.T) {
	for _, test := range []struct {
		status, want int
		body         string
	}{{400, 4, "{}"}, {401, 4, "{}"}, {403, 4, "{}"}, {503, 3, "{}"}, {200, 6, "invalid"}} {
		t.Run(fmt.Sprint(test.status), func(t *testing.T) {
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.WriteHeader(test.status)
				_, _ = io.WriteString(w, test.body)
			}))
			defer server.Close()
			var pair oauthPair
			err := oauthPost(context.Background(), server.URL, "/oauth/token", url.Values{}, &pair)
			if ExitCode(err) != test.want {
				t.Fatal(ExitCode(err), err)
			}
		})
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if err := oauthPost(ctx, "http://127.0.0.1:1", "/oauth/token", url.Values{}, nil); ExitCode(err) != 130 {
		t.Fatal(err)
	}
	if err := oauthPost(context.Background(), "http://127.0.0.1:1", "/oauth/token", url.Values{}, nil); ExitCode(err) != 5 {
		t.Fatal(err)
	}
}
func TestOAuthPKCECallbackAndExchange(t *testing.T) {
	var authorization *url.URL
	requests := 0
	tokenServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests++
		if r.URL.Path != "/oauth/token" || r.Header.Get("Authorization") != "" || r.Header.Get("X-STORE") != "" {
			t.Error("unexpected token transport")
		}
		_ = r.ParseForm()
		sum := sha256.Sum256([]byte(r.Form.Get("code_verifier")))
		if base64.RawURLEncoding.EncodeToString(sum[:]) != authorization.Query().Get("code_challenge") || r.Form.Get("redirect_uri") != authorization.Query().Get("redirect_uri") || r.Form.Get("code") != "single-use" {
			t.Error("PKCE or redirect mismatch")
		}
		_ = json.NewEncoder(w).Encode(map[string]any{"access_token": "access", "refresh_token": "refresh", "token_type": "Bearer", "expires_in": 3600})
	}))
	defer tokenServer.Close()
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	pair, err := authorizeOAuth(ctx, tokenServer.URL, "registered-native", "stores:read", func(target string) error {
		authorization, _ = url.Parse(target)
		if authorization.Query().Get("code_challenge_method") != "S256" {
			t.Error("wrong challenge method")
		}
		redirect := authorization.Query().Get("redirect_uri")
		u, _ := url.Parse(redirect)
		if u.Hostname() != "127.0.0.1" || u.Port() == "" {
			t.Error("non-loopback callback")
		}
		bad, e := http.Get(redirect + "?state=wrong&code=leak")
		if e != nil {
			return e
		}
		bad.Body.Close()
		if bad.StatusCode != 400 {
			t.Error("bad state accepted")
		}
		good, e := http.Get(redirect + "?state=" + authorization.Query().Get("state") + "&code=single-use")
		if e != nil {
			return e
		}
		good.Body.Close()
		return nil
	})
	if err != nil || pair.AccessToken != "access" || requests != 1 {
		t.Fatalf("requests=%d error=%v", requests, err)
	}
}
func TestOAuthNoRetryAndNoResponseLeak(t *testing.T) {
	count := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		count++
		w.WriteHeader(503)
		_, _ = io.WriteString(w, "refresh_token=private-token")
	}))
	defer server.Close()
	err := oauthPost(context.Background(), server.URL, "/oauth/token", url.Values{}, nil)
	if err == nil || strings.Contains(err.Error(), "private-token") || count != 1 {
		t.Fatalf("count=%d err=%v", count, err)
	}
}
func TestOAuthRejectsRedirect(t *testing.T) {
	called := false
	destination := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { called = true }))
	defer destination.Close()
	origin := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { http.Redirect(w, r, destination.URL, 302) }))
	defer origin.Close()
	if oauthPost(context.Background(), origin.URL, "/oauth/token", url.Values{}, nil) == nil || called {
		t.Fatal("followed OAuth redirect")
	}
}
func TestOAuthCrossProcessLock(t *testing.T) {
	credentialTestHome(t)
	unlock, _, err := lockOAuth("shared-profile")
	if err != nil {
		t.Fatal(err)
	}
	defer unlock()
	if _, _, err = lockOAuth("shared-profile"); err == nil {
		t.Fatal("second refresh lock accepted")
	}
}
func TestSensitiveOutputRedactedBeforeSelection(t *testing.T) {
	value, err := selectAndFilter(map[string]any{"data": map[string]any{"access_token": "private", "refresh_token": "private", "client_secret": "private", "token": "private", "redemption_url": "https://private.invalid/redeem"}}, "", "")
	if err != nil {
		t.Fatal(err)
	}
	data, _ := json.Marshal(value)
	if strings.Contains(string(data), "private") {
		t.Fatal("sensitive output leaked")
	}
}
func TestOAuthProfileRejectsForeignOriginBeforeVault(t *testing.T) {
	old := credentialVaultRead
	defer func() { credentialVaultRead = old }()
	credentialVaultRead = func(string) (string, error) { t.Fatal("vault read before origin validation"); return "", nil }
	if resolveOAuth(profileRecord{Origin: "https://sell.app", VaultEntry: "test"}, &Config{BaseURL: "https://other.invalid/api"}) == nil {
		t.Fatal("foreign origin accepted")
	}
}
func TestOAuthOriginValidation(t *testing.T) {
	for _, origin := range []string{"http://evil.example", "https://user:pass@sell.app", "https://sell.app#fragment", "https://sell.app?token=secret"} {
		if _, err := oauthOrigin(origin); err == nil {
			t.Fatal("unsafe origin accepted")
		}
	}
}
func TestPermittedOAuthStoresUsesOnlyAccessToken(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/v2/stores" || r.Header.Get("Authorization") != "Bearer consent-token" {
			t.Errorf("unexpected store discovery request: %s", r.URL.Path)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, "{\"data\":[{\"id\":\"1\",\"name\":\"Launch Lab\",\"slug\":\"launch-lab\",\"permissions\":[]}]}")
	}))
	defer server.Close()
	cfg := &Config{BaseURL: server.URL, AccessToken: "consent-token", APIKey: "must-not-leak", Timeout: time.Second}
	stores, err := permittedOAuthStores(context.Background(), cfg)
	if err != nil || len(stores) != 1 || stores[0] != "launch-lab" {
		t.Fatalf("stores=%v error=%v", stores, err)
	}
}

func TestRefreshFailureCannotReuseOldToken(t *testing.T) {
	credentialTestHome(t)
	oldRead, oldWrite := credentialVaultRead, credentialVaultWrite
	defer func() { credentialVaultRead = oldRead; credentialVaultWrite = oldWrite }()
	credentialVaultRead = func(string) (string, error) {
		return "{\"access_token\":\"old-access\",\"refresh_token\":\"old-refresh\",\"expires_at\":\"2000-01-01T00:00:00Z\"}", nil
	}
	credentialVaultWrite = func(string, string) error { t.Fatal("unexpected vault write"); return nil }
	requests := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { requests++; w.WriteHeader(503) }))
	defer server.Close()
	record := profileRecord{VaultEntry: "rotation", ClientID: "registered", Origin: server.URL}
	if resolveOAuth(record, &Config{}) == nil {
		t.Fatal("failed refresh accepted")
	}
	if resolveOAuth(record, &Config{}) == nil {
		t.Fatal("uncertain token reused")
	}
	if requests != 1 {
		t.Fatalf("requests=%d", requests)
	}
}
func TestRefreshAtomicallyReplacesCompletePair(t *testing.T) {
	credentialTestHome(t)
	oldRead, oldWrite := credentialVaultRead, credentialVaultWrite
	defer func() { credentialVaultRead = oldRead; credentialVaultWrite = oldWrite }()
	credentialVaultRead = func(string) (string, error) {
		return "{\"access_token\":\"old-access\",\"refresh_token\":\"old-refresh\",\"expires_at\":\"2000-01-01T00:00:00Z\"}", nil
	}
	writes := 0
	credentialVaultWrite = func(_ string, secret string) error {
		writes++
		var pair oauthPair
		if json.Unmarshal([]byte(secret), &pair) != nil || pair.AccessToken != "new-access" || pair.RefreshToken != "new-refresh" || pair.ExpiresAt.IsZero() {
			t.Fatal("incomplete saved pair")
		}
		return nil
	}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		_ = json.NewEncoder(w).Encode(map[string]any{"access_token": "new-access", "refresh_token": "new-refresh", "token_type": "Bearer", "expires_in": 3600})
	}))
	defer server.Close()
	cfg := &Config{}
	record := profileRecord{VaultEntry: "rotation", ClientID: "registered", Origin: server.URL}
	if err := resolveOAuth(record, cfg); err != nil {
		t.Fatal(err)
	}
	if cfg.AccessToken != "new-access" || writes != 1 {
		t.Fatal("replacement not installed")
	}
}
func TestProfileTokenIsReloadedForLongRunningCommands(t *testing.T) {
	credentialTestHome(t)
	old := credentialVaultRead
	defer func() { credentialVaultRead = old }()
	reads := 0
	credentialVaultRead = func(string) (string, error) {
		reads++
		pair := oauthPair{AccessToken: strings.Repeat("a", reads), RefreshToken: "r", ExpiresAt: time.Now().Add(time.Hour)}
		data, _ := json.Marshal(pair)
		return string(data), nil
	}
	doc, err := loadProfiles()
	if err != nil {
		t.Fatal(err)
	}
	doc.Active = "test"
	doc.Profiles["test"] = profileRecord{Method: "oauth", Origin: "https://sell.app", Store: "store", VaultEntry: "entry"}
	if err = saveProfiles(doc); err != nil {
		t.Fatal(err)
	}
	cfg := &Config{BaseURL: "https://sell.app/api"}
	for i := 0; i < 2; i++ {
		if err = resolveProfileConfig(cfg); err != nil {
			t.Fatal(err)
		}
	}
	if reads != 2 || cfg.AccessToken != "aa" {
		t.Fatal("profile access token was cached across operations")
	}
	explicit := &Config{BaseURL: "https://sell.app/api", AccessToken: "explicit", Store: "store"}
	if err = resolveProfileConfig(explicit); err != nil || explicit.AccessToken != "explicit" || reads != 2 {
		t.Fatal("explicit access token was overridden")
	}
}
func TestOAuthGrantSchemaPreservesConditionalRequirements(t *testing.T) {
	for _, entry := range CommandCatalog {
		if entry.APIPath != "/oauth/token" {
			continue
		}
		if entry.Body == nil {
			t.Fatal("missing grant body")
		}
		variants, ok := entry.Body.Schema["oneOf"].([]any)
		if !ok || len(variants) != 2 {
			t.Fatal("missing grant variants")
		}
		encoded, _ := json.Marshal(entry)
		if strings.Contains(string(encoded), "Fixture") {
			t.Fatal("fixture metadata exposed")
		}
		return
	}
	t.Fatal("token command missing")
}
func TestExportPollingHonorsServerMinimum(t *testing.T) {
	value := map[string]any{"meta": map[string]any{"poll_after_seconds": 5}}
	if delay, err := exportPollInterval(value, time.Second); err != nil || delay != 5*time.Second {
		t.Fatal(delay, err)
	}
	if delay, err := exportPollInterval(value, 10*time.Second); err != nil || delay != 10*time.Second {
		t.Fatal(delay, err)
	}
	if _, err := exportPollInterval(map[string]any{"meta": map[string]any{"poll_after_seconds": -1}}, time.Second); err == nil {
		t.Fatal("invalid poll hint accepted")
	}
}
func TestOAuthLockAcrossProcesses(t *testing.T) {
	if os.Getenv("SELLAPP_TEST_LOCK_CHILD") == "1" {
		if _, _, err := lockOAuth("process-profile"); err == nil {
			t.Fatal("child acquired held refresh lock")
		}
		return
	}
	credentialTestHome(t)
	unlock, _, err := lockOAuth("process-profile")
	if err != nil {
		t.Fatal(err)
	}
	defer unlock()
	child := exec.Command(os.Args[0], "-test.run=^TestOAuthLockAcrossProcesses$")
	child.Env = append(os.Environ(), "SELLAPP_TEST_LOCK_CHILD=1")
	if output, err := child.CombinedOutput(); err != nil {
		t.Fatalf("child lock check failed: %v %s", err, output)
	}
}
func TestOAuthDeadlineHasTimeoutExitCode(t *testing.T) {
	if ExitCode(context.DeadlineExceeded) != 5 {
		t.Fatal("deadline must use timeout exit category")
	}
}
func TestRegisteredLoginIsBoundToConfiguredOrigin(t *testing.T) {
	t.Setenv("SELLAPP_CLIENT_ID", "")
	t.Setenv("SELLAPP_API_BASE_URL", "")
	if defaultBaseURL != firstPartyOrigin+"/api" {
		t.Fatal("CLI origin and registration diverged")
	}
	if firstPartyClientID != "" {
		if _, err := execute(t, "login", "--dry-run"); err != nil {
			t.Fatal(err)
		}
	} else if _, err := execute(t, "login", "--dry-run"); err == nil {
		t.Fatal("unconfigured registration accepted")
	}
	if _, err := execute(t, "login", "--base-url", "https://other.invalid/api", "--dry-run"); err == nil {
		t.Fatal("used registration at another origin")
	}
	if _, err := execute(t, "login", "--base-url", "https://other.invalid/api", "--client-id", "other-client", "--dry-run"); err != nil {
		t.Fatal(err)
	}
}
func TestStoreSelectionChecksGrantAndDryRunDoesNotPersist(t *testing.T) {
	credentialTestHome(t)
	t.Setenv("SELLAPP_API_KEY", "")
	t.Setenv("SELLAPP_STORE", "")
	old := credentialVaultRead
	defer func() { credentialVaultRead = old }()
	reads := 0
	credentialVaultRead = func(string) (string, error) {
		reads++
		data, _ := json.Marshal(oauthPair{AccessToken: "access", RefreshToken: "refresh", ExpiresAt: time.Now().Add(time.Hour)})
		return string(data), nil
	}
	requests := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests++
		if r.Header.Get("Authorization") != "Bearer access" {
			t.Error("wrong credential")
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = io.WriteString(w, "{\"data\":[{\"id\":\"1\",\"name\":\"Launch Lab\",\"slug\":\"launch-lab\",\"permissions\":[]}]}")
	}))
	defer server.Close()
	doc, _ := loadProfiles()
	doc.Active = "test"
	doc.Profiles["test"] = profileRecord{Method: "oauth", Origin: server.URL, Store: "original", VaultEntry: "test"}
	if err := saveProfiles(doc); err != nil {
		t.Fatal(err)
	}
	if _, err := execute(t, "stores", "use", "launch-lab", "--base-url", server.URL, "--dry-run"); err != nil {
		t.Fatal(err)
	}
	doc, _ = loadProfiles()
	if doc.Profiles["test"].Store != "original" || requests != 0 || reads != 0 {
		t.Fatal("dry run changed state or loaded credentials")
	}
	if _, err := execute(t, "stores", "use", "foreign", "--base-url", server.URL); err == nil {
		t.Fatal("ungranted store accepted")
	}
	doc, _ = loadProfiles()
	if doc.Profiles["test"].Store != "original" {
		t.Fatal("failed selection persisted")
	}
	if _, err := execute(t, "stores", "use", "launch-lab", "--base-url", server.URL); err != nil {
		t.Fatal(err)
	}
	doc, _ = loadProfiles()
	if doc.Profiles["test"].Store != "launch-lab" || requests != 2 {
		t.Fatal("granted selection was not saved")
	}
}

func TestOAuthDiagnosticsRedactProviderBodies(t *testing.T) {
	for _, code := range []string{"access_denied", "invalid_client", "invalid_scope", "invalid_grant", "private-token"} {
		t.Run(code, func(t *testing.T) {
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.WriteHeader(400)
				_ = json.NewEncoder(w).Encode(map[string]string{"error": code, "error_description": "private-token", "refresh_token": "private-token"})
			}))
			defer server.Close()
			err := oauthPost(context.Background(), server.URL, "/oauth/token", url.Values{}, nil)
			detail := FormatError(err)
			if strings.Contains(detail, "private-token") {
				t.Fatal("provider response leaked")
			}
			if code != "private-token" && !strings.Contains(detail, code) {
				t.Fatal("missing diagnostic category", detail)
			}
			if (code == "invalid_client" || code == "invalid_scope") && strings.Contains(detail, "authorize again") {
				t.Fatal("configuration failure suggested reauthorization")
			}
		})
	}
}
func TestOAuthConsentErrorCategories(t *testing.T) {
	for _, code := range []string{"access_denied", "invalid_client", "invalid_scope"} {
		t.Run(code, func(t *testing.T) {
			ctx, cancel := context.WithTimeout(context.Background(), time.Second)
			defer cancel()
			_, err := authorizeOAuth(ctx, "http://127.0.0.1:1", "client", "stores:read", func(target string) error {
				u, _ := url.Parse(target)
				callback := u.Query().Get("redirect_uri")
				response, err := http.Get(callback + "?state=" + u.Query().Get("state") + "&error=" + code + "&error_description=private-token")
				if err == nil {
					response.Body.Close()
				}
				return err
			})
			detail := FormatError(err)
			if !strings.Contains(detail, code) || strings.Contains(detail, "private-token") {
				t.Fatal(detail)
			}
		})
	}
}
func TestStoreDenialPreservesOAuthCredentials(t *testing.T) {
	credentialTestHome(t)
	t.Setenv("SELLAPP_API_KEY", "")
	t.Setenv("SELLAPP_STORE", "")
	oldRead, oldWrite := credentialVaultRead, credentialVaultWrite
	defer func() { credentialVaultRead = oldRead; credentialVaultWrite = oldWrite }()
	credentialVaultRead = func(string) (string, error) {
		data, _ := json.Marshal(oauthPair{AccessToken: "access", RefreshToken: "refresh", ExpiresAt: time.Now().Add(time.Hour)})
		return string(data), nil
	}
	credentialVaultWrite = func(string, string) error { t.Fatal("denial modified credentials"); return nil }
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		if r.Header.Get("X-STORE") == "denied" {
			w.WriteHeader(403)
			_, _ = io.WriteString(w, "{\"error\":{\"code\":\"forbidden\",\"message\":\"private-token\"}}")
			return
		}
		_, _ = io.WriteString(w, responseFixture("GET /v2/products"))
	}))
	defer server.Close()
	doc, _ := loadProfiles()
	doc.Active = "test"
	doc.Profiles["test"] = profileRecord{Method: "oauth", Origin: server.URL, Store: "denied", VaultEntry: "test"}
	if err := saveProfiles(doc); err != nil {
		t.Fatal(err)
	}
	_, err := execute(t, "products", "list", "--base-url", server.URL)
	if err == nil {
		t.Fatal("denial accepted")
	}
	detail := FormatError(err)
	if !strings.Contains(detail, "Credentials are retained") || strings.Contains(detail, "private-token") {
		t.Fatal(detail)
	}
	doc, _ = loadProfiles()
	if doc.Profiles["test"].VaultEntry != "test" {
		t.Fatal("denial deleted profile")
	}
	if _, err = execute(t, "products", "list", "--base-url", server.URL, "--store", "allowed"); err != nil {
		t.Fatal("other store credentials lost", err)
	}
}
func TestExplicitNarrowerLoginScopes(t *testing.T) {
	if _, err := execute(t, "login", "--client-id", "test-client", "--scopes", "stores:read products:read", "--dry-run"); err != nil {
		t.Fatal(err)
	}
}

func TestOAuthAPIConfigurationDiagnostics(t *testing.T) {
	for _, code := range []string{"invalid_client", "invalid_scope", "invalid_grant"} {
		t.Run(code, func(t *testing.T) {
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(401)
				_ = json.NewEncoder(w).Encode(map[string]any{"error": code, "code": code, "message": "private-token", "status": 401, "type": "authentication_error"})
			}))
			defer server.Close()
			_, err := execute(t, "products", "list", "--base-url", server.URL, "--api-key", "test-key", "--store", "test-store")
			if err == nil {
				t.Fatal("API denial accepted")
			}
			detail := FormatError(err)
			if !strings.Contains(detail, code) || strings.Contains(detail, "private-token") {
				t.Fatal(detail)
			}
			if code != "invalid_grant" && strings.Contains(detail, "authorize again") {
				t.Fatal("configuration failure recommended login", detail)
			}
		})
	}
}
func TestOAuthRefreshConfigurationFailurePreservesCredentials(t *testing.T) {
	for _, code := range []string{"invalid_client", "invalid_scope"} {
		t.Run(code, func(t *testing.T) {
			credentialTestHome(t)
			oldRead, oldWrite := credentialVaultRead, credentialVaultWrite
			defer func() { credentialVaultRead = oldRead; credentialVaultWrite = oldWrite }()
			credentialVaultRead = func(string) (string, error) {
				data, _ := json.Marshal(oauthPair{AccessToken: "access", RefreshToken: "refresh", ExpiresAt: time.Now().Add(-time.Hour)})
				return string(data), nil
			}
			credentialVaultWrite = func(string, string) error { t.Fatal("configuration rejection overwrote credentials"); return nil }
			requests := 0
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				requests++
				w.WriteHeader(400)
				_ = json.NewEncoder(w).Encode(map[string]string{"error": code})
			}))
			defer server.Close()
			record := profileRecord{Origin: server.URL, ClientID: "client", VaultEntry: "entry"}
			for attempt := 0; attempt < 2; attempt++ {
				err := resolveOAuth(record, &Config{BaseURL: server.URL})
				if err == nil || !strings.Contains(FormatError(err), code) {
					t.Fatal("configuration rejection became uncertain refresh", err)
				}
			}
			if requests != 2 {
				t.Fatal("refresh was blocked after definitive configuration rejection")
			}
		})
	}
}
