// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	sdk "github.com/sellapp/sellapp-cli/internal/sdk"
	"github.com/spf13/cobra"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"time"
)

// Public registration ID is supplied by release configuration; it is not a secret.
var firstPartyClientID = ""
var firstPartyOrigin = "https://sell.app"

type oauthFailure struct {
	Message string
	Exit    int
	Code    string
}

func (e *oauthFailure) Error() string { return e.Message }
func oauthProtocolFailure(code string, status int) *oauthFailure {
	switch code {
	case "access_denied":
		return &oauthFailure{Message: "CLI consent was declined; no connection was approved", Exit: 4, Code: code}
	case "invalid_client":
		return &oauthFailure{Message: "unsupported CLI client or server configuration; check the CLI build and official server registration", Exit: 4, Code: code}
	case "invalid_scope":
		return &oauthFailure{Message: "requested scopes are not supported by the CLI registration; ask the operator to synchronize the CLI and server scope configuration. Repeating login with the same scopes will not fix this", Exit: 4, Code: code}
	case "invalid_grant":
		return &oauthFailure{Message: "OAuth credentials are invalid, expired, revoked, or already used; authorize again", Exit: 4, Code: code}
	default:
		exit := 3
		if status == 400 || status == 401 || status == 403 {
			exit = 4
		}
		return &oauthFailure{Message: fmt.Sprintf("OAuth request failed (HTTP %d); check server availability and configuration", status), Exit: exit}
	}
}

type oauthPair struct {
	Scope        string    `json:"scope"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	TokenType    string    `json:"token_type"`
	ExpiresIn    int64     `json:"expires_in"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func oauthRandom() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}
func oauthOrigin(base string) (string, error) {
	u, err := url.Parse(base)
	if err != nil || u.Host == "" || u.User != nil || u.RawQuery != "" || u.Fragment != "" {
		return "", errors.New("invalid OAuth origin")
	}
	if u.Scheme != "https" && !(u.Scheme == "http" && (u.Hostname() == "127.0.0.1" || u.Hostname() == "::1")) {
		return "", errors.New("OAuth requires HTTPS or a numeric loopback test server")
	}
	return u.Scheme + "://" + u.Host, nil
}
func oauthPost(ctx context.Context, origin, path string, form url.Values, target any) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, origin+path, strings.NewReader(form.Encode()))
	if err != nil {
		return errors.New("cannot prepare OAuth request")
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Accept", "application/json")
	client := &http.Client{Timeout: 30 * time.Second, CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}
	response, err := client.Do(req)
	if err != nil {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		return &oauthFailure{Message: "OAuth response was not received; do not retry the credential, authorize again", Exit: 5}
	}
	defer response.Body.Close()
	data, err := io.ReadAll(io.LimitReader(response.Body, 1<<20))
	if err != nil {
		return &oauthFailure{Message: "OAuth response was incomplete; authorize again", Exit: 5}
	}
	if response.StatusCode < 200 || response.StatusCode >= 300 {
		var problem struct {
			Code string `json:"error"`
		}
		_ = json.Unmarshal(data, &problem)
		return oauthProtocolFailure(problem.Code, response.StatusCode)
	}
	if target != nil {
		if err = json.Unmarshal(data, target); err != nil {
			return &oauthFailure{Message: "invalid OAuth response; authorize again", Exit: 6}
		}
	}
	return nil
}
func validateOAuthPair(pair *oauthPair) error {
	if pair.AccessToken == "" || pair.RefreshToken == "" || !strings.EqualFold(pair.TokenType, "Bearer") || pair.ExpiresIn <= 0 || pair.ExpiresIn > 31536000 {
		return errors.New("invalid OAuth token pair; authorize again")
	}
	pair.ExpiresAt = time.Now().Add(time.Duration(pair.ExpiresIn) * time.Second)
	return nil
}
func writeOAuthLoginSuccess(output io.Writer, name, scope string) error {
	message := "Connected successfully."
	if granted := strings.TrimSpace(scope); granted != "" {
		message = "Granted scopes: " + granted + "."
	}
	_, err := fmt.Fprintf(output, "Saved OAuth profile %s. %s Select a store with stores use after listing accessible stores.\n", name, message)
	return err
}
func writeAuthorizationURL(output io.Writer, address string) error {
	encoder := json.NewEncoder(output)
	encoder.SetEscapeHTML(false)
	return encoder.Encode(map[string]any{"type": "authorization_url", "url": address, "timeout_seconds": 300})
}
func openOAuthBrowser(target string) error {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		cmd = exec.Command("open", target)
	case "windows":
		cmd = exec.Command("rundll32", "url.dll,FileProtocolHandler", target)
	default:
		cmd = exec.Command("xdg-open", target)
	}
	if err := cmd.Start(); err != nil {
		return errors.New("cannot open browser; check the system browser configuration")
	}
	go func() { _ = cmd.Wait() }()
	return nil
}
func authorizeOAuth(ctx context.Context, origin, clientID, scopes string, open func(string) error) (oauthPair, error) {
	var pair oauthPair
	state, err := oauthRandom()
	if err != nil {
		return pair, err
	}
	verifier, err := oauthRandom()
	if err != nil {
		return pair, err
	}
	digest := sha256.Sum256([]byte(verifier))
	listener, err := net.Listen("tcp4", "127.0.0.1:0")
	if err != nil {
		return pair, err
	}
	defer listener.Close()
	redirect := "http://" + listener.Addr().String() + "/callback"
	callback, _ := url.Parse(redirect)
	type result struct {
		code string
		err  error
	}
	received := make(chan result, 1)
	var once sync.Once
	server := &http.Server{ReadHeaderTimeout: 5 * time.Second, Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		q, parseErr := url.ParseQuery(r.URL.RawQuery)
		if r.Method != "GET" || r.Host != callback.Host || r.URL.EscapedPath() != callback.EscapedPath() || parseErr != nil || len(q["state"]) != 1 || subtle.ConstantTimeCompare([]byte(q.Get("state")), []byte(state)) != 1 {
			http.Error(w, "Invalid authorization callback.", 400)
			return
		}
		if len(q["code"]) > 1 || len(q["error"]) > 1 || (q.Get("code") != "" && q.Get("error") != "") {
			http.Error(w, "Invalid authorization callback.", 400)
			return
		}
		answer := result{code: q.Get("code")}
		if q.Get("error") != "" {
			answer.err = oauthProtocolFailure(q.Get("error"), 400)
		} else if answer.code == "" {
			http.Error(w, "Missing authorization code.", 400)
			return
		}
		accepted := false
		once.Do(func() { accepted = true; received <- answer })
		if !accepted {
			http.Error(w, "Authorization callback already used.", 400)
			return
		}
		_, _ = io.WriteString(w, "Authorization received. Return to the CLI.")
	})}
	defer server.Close()
	go func() { _ = server.Serve(listener) }()
	params := url.Values{"response_type": {"code"}, "client_id": {clientID}, "redirect_uri": {redirect}, "scope": {scopes}, "state": {state}, "code_challenge": {base64.RawURLEncoding.EncodeToString(digest[:])}, "code_challenge_method": {"S256"}}
	if err = open(origin + "/oauth/authorize?" + params.Encode()); err != nil {
		return pair, err
	}
	select {
	case <-ctx.Done():
		return pair, ctx.Err()
	case answer := <-received:
		if answer.err != nil {
			return pair, answer.err
		}
		err = oauthPost(ctx, origin, "/oauth/token", url.Values{"grant_type": {"authorization_code"}, "client_id": {clientID}, "code": {answer.code}, "redirect_uri": {redirect}, "code_verifier": {verifier}}, &pair)
	}
	if err != nil {
		return pair, err
	}
	return pair, validateOAuthPair(&pair)
}

// A process owns this directory until it exits the refresh/revoke critical section.
// Never break an existing lock automatically: its owner may still be sending a token.
func lockOAuth(entry string) (func(), string, error) {
	root, err := credentialConfigDir()
	if err != nil {
		return nil, "", err
	}
	if _, err = credentialDir(); err != nil {
		return nil, "", err
	}
	dir := filepath.Join(root, "oauth")
	if err = privateDirectory(dir, true); err != nil {
		return nil, "", err
	}
	sum := sha256.Sum256([]byte(entry))
	base := filepath.Join(dir, fmt.Sprintf("%x", sum))
	unlock, err := lockCredentialPath(base+".lock", false)
	return unlock, base + ".uncertain", err
}
func loadOAuthPair(record profileRecord) (oauthPair, error) {
	var pair oauthPair
	secret, err := credentialRead(record)
	if err != nil {
		return pair, err
	}
	if err = json.Unmarshal([]byte(secret), &pair); err != nil {
		return pair, errors.New("invalid saved OAuth credential; the record was retained. Run sellapp login to replace this profile")
	}
	if pair.AccessToken == "" || pair.RefreshToken == "" || pair.ExpiresAt.IsZero() {
		return pair, errors.New("incomplete saved OAuth credential; the record was retained. Run sellapp login to replace this profile")
	}
	return pair, nil
}
func saveOAuthPair(record profileRecord, pair oauthPair) error {
	data, err := json.Marshal(pair)
	if err != nil {
		return err
	}
	return credentialWrite(record, string(data))
}
func markOAuthUncertain(path string) error { return privateCreateMarker(path) }
func resolveOAuth(record profileRecord, cfg *Config) error {
	origin, err := oauthOrigin(record.Origin)
	if err != nil {
		return err
	}
	if cfg.BaseURL == "" || (cfg.BaseURL == defaultBaseURL && !cfg.BaseURLExplicit) {
		cfg.BaseURL = origin + "/api"
	}
	target, err := oauthOrigin(cfg.BaseURL)
	if err != nil || target != origin {
		return errors.New("OAuth profile origin does not match --base-url; use the profile's registered origin")
	}

	if cfg.DryRun {
		cfg.AccessToken = "dry-run-access-token"
		return nil
	}
	unlock, marker, err := lockOAuth(record.VaultEntry)
	if err != nil {
		return err
	}
	defer unlock()
	if _, err = os.Lstat(marker); err == nil {
		return errors.New("previous OAuth refresh has an uncertain outcome; authorize again")
	} else if !os.IsNotExist(err) {
		return err
	}
	record, err = prepareCredentialRecord(record)
	if err != nil {
		return err
	}
	pair, err := loadOAuthPair(record)
	if err != nil {
		return err
	}
	if time.Until(pair.ExpiresAt) < 30*time.Second {
		if err = markOAuthUncertain(marker); err != nil {
			return err
		}
		parent := cfg.Context
		if parent == nil {
			parent = context.Background()
		}
		ctx, cancel := context.WithTimeout(parent, 30*time.Second)
		defer cancel()
		var replacement oauthPair
		err = oauthPost(ctx, record.Origin, "/oauth/token", url.Values{"grant_type": {"refresh_token"}, "client_id": {record.ClientID}, "refresh_token": {pair.RefreshToken}}, &replacement)
		if err != nil {
			var failure *oauthFailure
			if errors.As(err, &failure) && (failure.Code == "invalid_client" || failure.Code == "invalid_scope") {
				if removeErr := privateRemove(marker); removeErr != nil {
					return removeErr
				}
			}
			return err
		}
		if err = validateOAuthPair(&replacement); err != nil {
			return err
		}
		if err = saveOAuthPair(record, replacement); err != nil {
			return err
		}
		if err = privateRemove(marker); err != nil {
			return err
		}
		pair = replacement
	}
	cfg.AccessToken = pair.AccessToken
	return nil
}
func oauthLogin(cmd *cobra.Command, cfg *Config, name, store, clientID, scopes string) error {
	if !validProfileName(name) {
		return &UsageError{Message: "invalid profile name"}
	}
	origin, err := oauthOrigin(cfg.BaseURL)
	if err != nil {
		return err
	}
	if clientID == "" {
		clientID = os.Getenv("SELLAPP_CLIENT_ID")
	}
	if clientID == "" {
		if origin != firstPartyOrigin {
			return &UsageError{Message: "this built-in OAuth client is registered for " + firstPartyOrigin + "; use --base-url " + firstPartyOrigin + "/api or provide --client-id for another origin"}
		}
		clientID = firstPartyClientID
	}
	if strings.TrimSpace(clientID) == "" {
		return &UsageError{Message: "this build has no configured official SellApp login registration; use the official release or contact your operator"}
	}
	if cfg.DryRun {
		_, err = fmt.Fprintln(cfg.Stdout, "OAuth login plan: public native client; PKCE S256; numeric loopback callback; contacted_network=false")
		return err
	}
	backend, err := newSecretStore()
	if err != nil {
		return err
	}
	if backend == "file" {
		if _, err = credentialDir(); err != nil {
			return err
		}
		if _, _, err = credentialIdentity("", true); err != nil {
			return err
		}
	}
	ctx, cancel := context.WithTimeout(cmd.Context(), 5*time.Minute)
	defer cancel()
	noBrowser, _ := cmd.Flags().GetBool("no-browser")
	open := func(address string) error {
		if noBrowser {
			return writeAuthorizationURL(cfg.Stdout, address)
		}
		presentStage(cmd, cfg, "Opening your browser")
		if err := openOAuthBrowser(address); err != nil {
			return err
		}
		presentStage(cmd, cfg, "Waiting for consent")
		return nil
	}
	pair, err := authorizeOAuth(ctx, origin, clientID, scopes, open)
	if err != nil {
		return err
	}
	candidate := *cfg
	candidate.APIKey = ""
	candidate.AccessToken = pair.AccessToken
	candidate.CustomerSession = ""
	candidate.BrowserSession = ""
	candidate.Store = ""
	stores, err := permittedOAuthStores(ctx, &candidate)
	if err != nil {
		return err
	}
	if store == "" && len(stores) == 1 {
		store = stores[0]
	}
	if store == "" && len(stores) > 1 && interactivePresentation(cmd, cfg) {
		presentStage(cmd, cfg, "Selecting a store")
		store, err = promptChoice(cmd, cfg, "Choose a store", stores, "")
		if err != nil {
			return err
		}
	}
	if store != "" {
		found := false
		for _, slug := range stores {
			if slug == store {
				found = true
			}
		}
		if !found {
			return &UsageError{Message: "selected store is not currently accessible"}
		}
	}
	if len(stores) == 0 && interactivePresentation(cmd, cfg) {
		fmt.Fprintln(cfg.Stderr, "Connected. You have no stores yet. Run sellapp setup or sellapp stores create to create one.")
	}
	nonce, err := oauthRandom()
	if err != nil {
		return err
	}
	entry := "oauth:" + name + ":" + nonce
	record := profileRecord{Store: store, VaultEntry: entry, Method: "oauth", ClientID: clientID, Origin: origin, SecretStore: backend}
	data, err := json.Marshal(pair)
	if err != nil {
		return err
	}
	presentStage(cmd, cfg, "Saving access")
	if err = saveNewProfile(name, record, string(data)); err != nil {
		return err
	}
	if interactivePresentation(cmd, cfg) {
		return writeOAuthLoginSuccess(cfg.Stderr, name, pair.Scope)
	}
	result := map[string]any{"type": "connected", "profile": name, "store": store, "storage_backend": backend}
	if len(stores) == 0 {
		result["connection_state"] = "connected_without_stores"
		result["next_step"] = "Run sellapp setup or sellapp stores create."
	}
	if granted := strings.TrimSpace(pair.Scope); granted != "" {
		result["granted_scopes"] = strings.Fields(granted)
	}
	if noBrowser {
		return json.NewEncoder(cfg.Stdout).Encode(result)
	}
	return cfg.writeResult(result)
}
func permittedOAuthStores(ctx context.Context, cfg *Config) ([]string, error) {
	result, err := sdk.ExecuteCLI(ctx, cfg.client(), "GET /v2/stores", sdk.CLIInvocation{})
	if err != nil {
		return nil, err
	}
	encoded, err := json.Marshal(result)
	if err != nil {
		return nil, err
	}
	var response struct {
		Data []struct {
			Slug string `json:"slug"`
		} `json:"data"`
	}
	if err = json.Unmarshal(encoded, &response); err != nil {
		return nil, err
	}
	stores := []string{}
	for _, store := range response.Data {
		if store.Slug != "" {
			stores = append(stores, store.Slug)
		}
	}
	return stores, nil
}
func revokeOAuth(ctx context.Context, record profileRecord) error {
	unlock, _, err := lockOAuth(record.VaultEntry)
	if err != nil {
		return err
	}
	defer unlock()
	record, err = prepareCredentialRecord(record)
	if err != nil {
		return err
	}
	return revokeOAuthLocked(ctx, record)
}
func revokeOAuthLocked(ctx context.Context, record profileRecord) error {
	pair, err := loadOAuthPair(record)
	if err != nil {
		return err
	}
	if err = oauthPost(ctx, record.Origin, "/oauth/revoke", url.Values{"client_id": {record.ClientID}, "token": {pair.RefreshToken}, "token_type_hint": {"refresh_token"}}, nil); err != nil {
		return err
	}
	return deleteProfileCredentials(record)
}
