// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"runtime"
	"strings"
	"testing"
	"time"
)

func TestOutputFormats(t *testing.T) {
	for _, format := range []string{"json", "jsonl", "yaml", "csv", "markdown", "table", "raw"} {
		var out bytes.Buffer
		cfg := &Config{Output: format, Stdout: &out, Fields: "id,name", Filter: "name=shop"}
		if err := writeFormattedResult(cfg, []map[string]any{{"id": 1, "name": "shop", "secret": "no"}}); err != nil {
			t.Fatal(format, err)
		}
		if strings.Contains(out.String(), "secret") {
			t.Fatal("selection leak")
		}
	}
}
func TestNonTTYWritesRequireYes(t *testing.T) {
	err := confirmWrite(nil, &Config{Store: "demo", NoInteractive: true}, CatalogEntry{Method: "POST", OperationID: "createThing"})
	if err == nil || !strings.Contains(err.Error(), "--yes") {
		t.Fatal(err)
	}
}
func TestDeclaredIdempotencyOnly(t *testing.T) {
	none, err := invocationIdempotencyKey(CatalogEntry{})
	if err != nil || none != "" {
		t.Fatal("undeclared key")
	}
	a, err := invocationIdempotencyKey(CatalogEntry{IdempotencyKey: true})
	if err != nil {
		t.Fatal(err)
	}
	b, err := invocationIdempotencyKey(CatalogEntry{IdempotencyKey: true})
	if err != nil || a == "" || a == b {
		t.Fatal(a, b, err)
	}
}
func TestAuditRedactionAndMode(t *testing.T) {
	credentialTestHome(t)
	t.Setenv("SELLAPP_AUDIT_DISABLED", "")
	cfg := &Config{Profile: "dev", Store: "shop"}
	writeAudit(cfg, "listProducts", time.Now(), nil)
	path, _ := auditPath()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), "Authorization") {
		t.Fatal("secret leak")
	}
	var entry auditEntry
	if err = json.Unmarshal(bytes.TrimSpace(data), &entry); err != nil || entry.Operation != "listProducts" {
		t.Fatal(err)
	}
	info, _ := os.Stat(path)
	if runtime.GOOS != "windows" && info.Mode().Perm() != 0600 {
		t.Fatal(info.Mode())
	}
}
func TestMCPHasReadAndWritePolicies(t *testing.T) {
	reads, writes := 0, 0
	for _, e := range CommandCatalog {
		if e.Method == "GET" || e.Method == "HEAD" {
			reads++
		} else {
			writes++
		}
	}
	if reads == 0 || writes == 0 {
		t.Fatal(reads, writes)
	}
}
func TestMCPSchemaAndInvocationUseCatalogInputs(t *testing.T) { testBridgeDiscoveryAndCall(t, true) }
func TestStoreReadinessComposesExactReads(t *testing.T) {
	seen := map[string]int{}
	fixtures := map[string]string{"/v2/store/settings": "GET /v2/store/settings", "/v2/payment-methods": "GET /v2/payment-methods", "/v2/webhook-channels": "GET /v2/webhook-channels", "/v2/store/custom-domains": "GET /v2/store/custom-domains"}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		seen[r.URL.Path]++
		key, ok := fixtures[r.URL.Path]
		if !ok {
			t.Errorf("unexpected path %s", r.URL.Path)
			http.Error(w, "unexpected", 500)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		io.WriteString(w, responseFixture(key))
	}))
	defer server.Close()
	args := append(baseArgs(server), "workflow", "store-readiness")
	out, err := execute(t, args...)
	if err != nil {
		t.Fatal(err)
	}
	if len(seen) != 4 || !strings.Contains(out, "getStoreSettings") || !strings.Contains(out, "listCustomDomains") {
		t.Fatalf("seen=%v out=%s", seen, out)
	}
}
func TestOrderPollingIsBounded(t *testing.T) {
	requests := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests++
		if r.URL.Path != "/v2/orders" {
			t.Errorf("path=%s", r.URL.Path)
		}
		w.Header().Set("Content-Type", "application/json")
		io.WriteString(w, responseFixture("GET /v2/orders"))
	}))
	defer server.Close()
	args := append(baseArgs(server), "workflow", "orders-poll", "--max-polls", "2", "--interval", "0s")
	if _, err := execute(t, args...); err != nil {
		t.Fatal(err)
	}
	if requests != 2 {
		t.Fatalf("requests=%d", requests)
	}
}
func TestWebhookWorkflowReadsBeforeTest(t *testing.T) {
	methods := []string{}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		methods = append(methods, r.Method+" "+r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		if r.Method == "GET" {
			io.WriteString(w, responseFixture("GET /v2/webhook-channels/{webhookChannel}"))
		} else {
			io.WriteString(w, responseFixture("POST /v2/webhook-channels/{webhookChannel}/test"))
		}
	}))
	defer server.Close()
	args := append(baseArgs(server), "workflow", "webhook-test", "--channel", "channel_1", "--event", "order.created")
	if _, err := execute(t, args...); err != nil {
		t.Fatal(err)
	}
	if len(methods) != 2 || methods[0] != "GET /v2/webhook-channels/channel_1" || methods[1] != "POST /v2/webhook-channels/channel_1/test" {
		t.Fatal(methods)
	}
}
func TestCatalogApplyRefusesRereadMismatchBeforeWrites(t *testing.T) {
	writes := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != "GET" {
			writes++
		}
		w.Header().Set("Content-Type", "application/json")
		io.WriteString(w, responseFixture("GET /v2/products/{product}"))
	}))
	defer server.Close()
	plan := t.TempDir() + "/plan.json"
	data := "{\"changes\":[{\"read_operation\":\"getProduct\",\"write_operation\":\"updateProduct\",\"path\":{\"product\":\"42\"},\"expected\":{\"different\":true},\"body\":{\"title\":\"new\"}}]}"
	if err := os.WriteFile(plan, []byte(data), 0600); err != nil {
		t.Fatal(err)
	}
	args := append(baseArgs(server), "workflow", "catalog", "apply", plan)
	_, err := execute(t, args...)
	if err == nil || !strings.Contains(err.Error(), "reread mismatch") {
		t.Fatal(err)
	}
	if writes != 0 {
		t.Fatalf("writes=%d", writes)
	}
}
func TestDraftUploadDryRunCannotReachNetwork(t *testing.T) {
	upload := t.TempDir() + "/file.txt"
	if err := os.WriteFile(upload, []byte("serial"), 0600); err != nil {
		t.Fatal(err)
	}
	out, err := execute(t, "--dry-run", "--yes", "workflow", "product-draft", "--title", "Draft", "--description", "Guided", "--product", "prod_1", "--variant", "1", "--deliverable", upload)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "createProduct") || !strings.Contains(out, "uploadVariantDeliverableFile") || !strings.Contains(out, "contacted_network") {
		t.Fatal(out)
	}
}
