// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/spf13/cobra"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

const vaultService = "sellapp-cli"

type profileRecord struct {
	Method              string `json:"method,omitempty"`
	ClientID            string `json:"client_id,omitempty"`
	Origin              string `json:"origin,omitempty"`
	Store               string `json:"store"`
	VaultEntry          string `json:"vault_entry"`
	SecretStore         string `json:"secret_store,omitempty"`
	PreviousSecretStore string `json:"previous_secret_store,omitempty"`
}
type profileDocument struct {
	SchemaVersion int                      `json:"schema_version"`
	Active        string                   `json:"active,omitempty"`
	Profiles      map[string]profileRecord `json:"profiles"`
}

func profilePath() (string, error) {
	root, err := credentialConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(root, "profiles.json"), nil
}
func loadProfiles() (profileDocument, error) {
	doc := profileDocument{SchemaVersion: 1, Profiles: map[string]profileRecord{}}
	path, err := profilePath()
	if err != nil {
		return doc, err
	}
	for _, dir := range []string{filepath.Dir(filepath.Dir(path)), filepath.Dir(path)} {
		if err = privateDirectory(dir, false); os.IsNotExist(err) {
			return doc, nil
		} else if err != nil {
			return doc, err
		}
	}
	data, err := privateRead(path)
	if errors.Is(err, os.ErrNotExist) {
		return doc, nil
	}
	if err != nil {
		return doc, err
	}
	if err = json.Unmarshal(data, &doc); err != nil {
		return doc, errors.New("invalid profile metadata")
	}
	if doc.SchemaVersion != 1 || doc.Profiles == nil {
		return doc, errors.New("unsupported profile metadata")
	}
	for name, record := range doc.Profiles {
		if !validProfileName(name) || record.VaultEntry == "" {
			return doc, errors.New("invalid profile metadata")
		}
		if _, err = storeFor(record); err != nil {
			return doc, err
		}
		if record.PreviousSecretStore != "" && record.PreviousSecretStore != "file" && record.PreviousSecretStore != "keyring" {
			return doc, errors.New("invalid credential migration metadata")
		}
	}
	return doc, nil
}
func saveProfiles(doc profileDocument) error {
	path, err := profilePath()
	if err != nil {
		return err
	}
	if _, err = credentialDir(); err != nil {
		return err
	}
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return err
	}
	return privateAtomicWrite(path, append(data, '\n'))
}
func validProfileName(value string) bool {
	if value == "" || len(value) > 64 {
		return false
	}
	for _, r := range value {
		if !(r == '-' || r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9') {
			return false
		}
	}
	return true
}
func vaultAvailable() bool {
	switch runtime.GOOS {
	case "darwin":
		return nativeVaultAvailable()
	case "linux":
		_, e := exec.LookPath("secret-tool")
		return e == nil
	case "windows":
		_, e := exec.LookPath("powershell.exe")
		return e == nil
	}
	return false
}
func vaultWrite(entry, secret string) error {
	if !vaultAvailable() {
		return errors.New("keyring credential storage is unavailable; enable your OS vault or choose SELLAPP_CLI_SECRET_STORE=file (the credential was not saved)")
	}
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		return nativeVaultWrite(entry, secret)
	case "linux":
		cmd = exec.Command("secret-tool", "store", "--label=SellApp CLI", "service", vaultService, "profile", entry)
		cmd.Stdin = strings.NewReader(secret)
	case "windows":
		cmd = exec.Command("powershell.exe", "-NoProfile", "-NonInteractive", "-Command", "$ErrorActionPreference='Stop';$v=[Windows.Security.Credentials.PasswordVault,Windows.Security.Credentials,ContentType=WindowsRuntime]::new();$v.Add([Windows.Security.Credentials.PasswordCredential,Windows.Security.Credentials,ContentType=WindowsRuntime]::new('sellapp-cli',$env:SELLAPP_VAULT_ENTRY,$env:SELLAPP_VAULT_SECRET))")
		cmd.Env = append(os.Environ(), "SELLAPP_VAULT_ENTRY="+entry, "SELLAPP_VAULT_SECRET="+secret)
	}
	if _, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("credential vault write failed: %w", err)
	}
	return nil
}
func vaultRead(entry string) (string, error) {
	if !vaultAvailable() {
		return "", errors.New("OS credential vault unavailable; set SELLAPP_API_KEY for this invocation")
	}
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		return nativeVaultRead(entry)
	case "linux":
		cmd = exec.Command("secret-tool", "lookup", "service", vaultService, "profile", entry)
	case "windows":
		cmd = exec.Command("powershell.exe", "-NoProfile", "-NonInteractive", "-Command", "$ErrorActionPreference='Stop';$v=[Windows.Security.Credentials.PasswordVault,Windows.Security.Credentials,ContentType=WindowsRuntime]::new();$c=$v.Retrieve('sellapp-cli',$env:SELLAPP_VAULT_ENTRY);$c.RetrievePassword();[Console]::Out.Write($c.Password)")
		cmd.Env = append(os.Environ(), "SELLAPP_VAULT_ENTRY="+entry)
	}
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("credential vault entry unavailable: %w", err)
	}
	secret := strings.TrimSpace(string(out))
	if secret == "" {
		return "", errors.New("credential vault returned an empty key")
	}
	return secret, nil
}
func vaultDelete(entry string) error {
	if !vaultAvailable() {
		return errors.New("keyring credential storage is unavailable; the saved credential was retained")
	}
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		return nativeVaultDelete(entry)
	case "linux":
		cmd = exec.Command("secret-tool", "clear", "service", vaultService, "profile", entry)
	case "windows":
		cmd = exec.Command("powershell.exe", "-NoProfile", "-NonInteractive", "-Command", "$ErrorActionPreference='Stop';$v=[Windows.Security.Credentials.PasswordVault,Windows.Security.Credentials,ContentType=WindowsRuntime]::new();$c=$null;try{$c=$v.Retrieve('sellapp-cli',$env:SELLAPP_VAULT_ENTRY)}catch{$e=$_.Exception;if($e.InnerException){$e=$e.InnerException};if($e.HResult -ne -2147023728){throw}};if($null -ne $c){$v.Remove($c)}")
		cmd.Env = append(os.Environ(), "SELLAPP_VAULT_ENTRY="+entry)
	}
	output, err := cmd.CombinedOutput()
	if err != nil {
		var exited *exec.ExitError
		if runtime.GOOS == "linux" && errors.As(err, &exited) && exited.ExitCode() == 1 && len(output) == 0 {
			return nil
		}
		return fmt.Errorf("credential vault delete failed: %w", err)
	}
	return nil
}
func resolveProfileConfig(cfg *Config) error {
	if cfg.APIKey == "" {
		cfg.APIKey = os.Getenv("SELLAPP_API_KEY")
	}
	if cfg.Store == "" {
		cfg.Store = os.Getenv("SELLAPP_STORE")
	}
	if !cfg.oauthProfile && (cfg.APIKey != "" || cfg.AccessToken != "") && cfg.Store != "" {
		return nil
	}
	doc, err := loadProfiles()
	if err != nil {
		return err
	}
	name := cfg.Profile
	if name == "" {
		name = doc.Active
	}
	if name == "" {
		return nil
	}
	record, ok := doc.Profiles[name]
	if !ok {
		return &UsageError{Message: "unknown profile " + name}
	}
	if cfg.Store == "" {
		cfg.Store = record.Store
	}
	if cfg.APIKey == "" && (cfg.AccessToken == "" || cfg.oauthProfile) && cfg.CustomerSession == "" && cfg.BrowserSession == "" {
		if record.Method == "oauth" {
			err = resolveOAuth(record, cfg)
			if err == nil {
				cfg.oauthProfile = true
			}
		} else if !cfg.DryRun {
			unlock, _, lockErr := lockOAuth(record.VaultEntry)
			if lockErr != nil {
				return lockErr
			}
			record, err = prepareCredentialRecord(record)
			if err == nil {
				cfg.APIKey, err = credentialRead(record)
			}
			unlock()
		}
		if err != nil {
			return err
		}
	}
	cfg.Profile = name
	return nil
}
func isTTY() bool { return isTerminalFile(os.Stdin) }
func interactivePresentation(cmd *cobra.Command, cfg *Config) bool {
	if cfg.NoInteractive || cfg.Output != "table" || !isTTY() {
		return false
	}
	out, ok := cfg.Stdout.(*os.File)
	if !ok || !isTerminalFile(out) {
		return false
	}
	stderr, ok := cfg.Stderr.(*os.File)
	if !ok || !isTerminalFile(stderr) {
		return false
	}
	for current := cmd; current != nil; current = current.Parent() {
		if current.Name() == "mcp" {
			return false
		}
	}
	return true
}
func presentStage(cmd *cobra.Command, cfg *Config, label string) {
	if !interactivePresentation(cmd, cfg) {
		return
	}
	if _, noColor := os.LookupEnv("NO_COLOR"); !noColor && os.Getenv("TERM") != "" && os.Getenv("TERM") != "dumb" {
		fmt.Fprintf(cfg.Stderr, "\x1b[36m%s\x1b[0m\n", label)
	} else {
		fmt.Fprintln(cfg.Stderr, label)
	}
}
func promptLineContext(ctx context.Context, label string) (string, error) {
	if !isTTY() {
		return "", &UsageError{Message: label + " is required in non-TTY mode"}
	}
	if err := ctx.Err(); err != nil {
		return "", err
	}
	fmt.Fprint(os.Stderr, label+": ")
	type answer struct {
		value string
		err   error
	}
	result := make(chan answer, 1)
	go func() {
		var value strings.Builder
		for {
			var single [1]byte
			_, err := os.Stdin.Read(single[:])
			b := single[0]
			if err != nil {
				result <- answer{"", err}
				return
			}
			if b == '\n' {
				result <- answer{strings.TrimSpace(value.String()), nil}
				return
			}
			if b == 3 {
				result <- answer{"", context.Canceled}
				return
			}
			if b != '\r' {
				value.WriteByte(b)
			}
		}
	}()
	select {
	case <-ctx.Done():
		return "", ctx.Err()
	case item := <-result:
		if errors.Is(item.err, io.EOF) {
			return "", context.Canceled
		}
		return item.value, item.err
	}
}
func promptLine(label string) (string, error) { return promptLineContext(context.Background(), label) }
func promptChoice(cmd *cobra.Command, cfg *Config, label string, choices []string, current string) (string, error) {
	if !interactivePresentation(cmd, cfg) {
		return "", &UsageError{Message: label + " requires an explicit value in noninteractive output"}
	}
	for i, choice := range choices {
		mark := ""
		if choice == current {
			mark = " (current)"
		}
		fmt.Fprintf(cfg.Stderr, "  %d. %s%s\n", i+1, choice, mark)
	}
	for {
		value, err := promptLineContext(cmd.Context(), label+" (number or value; Ctrl+C cancels)")
		if err != nil {
			return "", err
		}
		for i, choice := range choices {
			if value == choice || value == fmt.Sprint(i+1) {
				return choice, nil
			}
		}
		fmt.Fprintln(cfg.Stderr, "Choose one of the listed values.")
	}
}
func promptSecretContext(ctx context.Context, label string) (value string, resultErr error) {
	if !isTTY() {
		return "", &UsageError{Message: label + " is required in non-TTY mode"}
	}
	restore, err := hideTerminalInput()
	if err != nil {
		return "", fmt.Errorf("cannot read hidden input: %w", err)
	}
	defer func() {
		if err := restore(); err != nil && resultErr == nil {
			value = ""
			resultErr = fmt.Errorf("cannot restore terminal input: %w", err)
		}
		fmt.Fprintln(os.Stderr)
	}()
	value, err = promptLineContext(ctx, label)
	if err != nil {
		return "", err
	}
	if value == "" {
		return "", &UsageError{Message: label + " cannot be empty"}
	}
	return value, nil
}
func promptSecret(label string) (string, error) {
	return promptSecretContext(context.Background(), label)
}
func addAuthCommands(root *cobra.Command, cfg *Config) {
	auth := &cobra.Command{Use: "auth", Short: "Manage OAuth and manual API-key profiles"}
	root.AddCommand(auth)
	var name, store, key, method, clientID, scopes string
	login := &cobra.Command{Use: "login", Short: "Connect SellApp through browser consent", RunE: func(cmd *cobra.Command, _ []string) error {
		if method == "oauth" {
			return oauthLogin(cmd, cfg, name, store, clientID, scopes)
		}
		if method != "api-key" {
			return &UsageError{Message: "--method must be oauth or api-key"}
		}
		if !validProfileName(name) {
			return &UsageError{Message: "invalid profile name"}
		}
		if cfg.DryRun {
			_, err := fmt.Fprintln(cfg.Stdout, "Manual-key login plan: validate credentials and save access; contacted_network=false")
			return err
		}
		backend, err := newSecretStore()
		if err != nil {
			return err
		}
		if _, err = credentialDir(); err != nil {
			return err
		}
		if store == "" {
			if !interactivePresentation(cmd, cfg) {
				return &UsageError{Message: "--store is required for manual API-key login"}
			}
			store, err = promptLineContext(cmd.Context(), "Store slug")
			if err != nil {
				return err
			}
			if store == "" {
				return &UsageError{Message: "store slug cannot be empty"}
			}
		}
		if key == "" {
			key = os.Getenv("SELLAPP_API_KEY")
		}
		if key == "" {
			if !interactivePresentation(cmd, cfg) {
				return &UsageError{Message: "supply SELLAPP_API_KEY for manual API-key login in noninteractive mode"}
			}
			key, err = promptSecretContext(cmd.Context(), "API key")
			if err != nil {
				return err
			}
			if key == "" {
				return &UsageError{Message: "API key cannot be empty"}
			}
		}
		candidate := *cfg
		candidate.APIKey = key
		candidate.AccessToken = ""
		candidate.CustomerSession = ""
		candidate.BrowserSession = ""
		candidate.Store = store
		if _, err = runRead(cmd.Context(), &candidate); err != nil {
			return fmt.Errorf("credential validation failed: %w", err)
		}
		nonce, err := oauthRandom()
		if err != nil {
			return err
		}
		record := profileRecord{Method: "api-key", Store: store, VaultEntry: "profile:" + name + ":" + nonce, SecretStore: backend}
		presentStage(cmd, cfg, "Saving access")
		if err = saveNewProfile(name, record, key); err != nil {
			return err
		}
		return cfg.writeResult(map[string]any{"profile": name, "store": store, "storage_backend": backend, "connected": true})
	}}
	login.Flags().StringVar(&clientID, "client-id", "", "official public registration override for operator testing")
	login.Flags().StringVar(&scopes, "scopes", defaultOAuthScopes, "advanced: request an intentionally narrower grant")
	login.Flags().StringVar(&method, "method", "oauth", "oauth or api-key")
	login.Flags().StringVar(&name, "profile", "default", "profile name")
	login.Flags().StringVar(&store, "store", "", "explicit store slug")
	login.Flags().StringVar(&key, "api-key", "", "manual key; prefer hidden prompt or environment")
	login.Flags().Bool("no-browser", false, "print a usable authorization URL as JSONL without opening a browser")
	auth.AddCommand(login)
	topLogin := *login
	root.AddCommand(&topLogin)
	auth.AddCommand(&cobra.Command{Use: "profiles", RunE: func(_ *cobra.Command, _ []string) error {
		doc, err := loadProfiles()
		if err != nil {
			return err
		}
		names := []string{}
		for n := range doc.Profiles {
			names = append(names, n)
		}
		sort.Strings(names)
		rows := []map[string]any{}
		for _, n := range names {
			rows = append(rows, map[string]any{"profile": n, "store": doc.Profiles[n].Store, "active": n == doc.Active, "storage_backend": credentialBackend(doc.Profiles[n])})
		}
		return cfg.writeResult(rows)
	}})
	auth.AddCommand(&cobra.Command{Use: "use PROFILE", Args: cobra.ExactArgs(1), RunE: func(_ *cobra.Command, args []string) error {
		return updateProfiles(func(doc *profileDocument) error {
			if _, ok := doc.Profiles[args[0]]; !ok {
				return &UsageError{Message: "unknown profile " + args[0]}
			}
			doc.Active = args[0]
			return nil
		})
	}})
	auth.AddCommand(&cobra.Command{Use: "status", RunE: func(_ *cobra.Command, _ []string) error {
		if err := resolveProfileConfig(cfg); err != nil {
			return err
		}
		backend := "none"
		cleanupPending := false
		doc, err := loadProfiles()
		if err != nil {
			return err
		}
		if record, ok := doc.Profiles[cfg.Profile]; ok {
			backend = credentialBackend(record)
			cleanupPending = record.PreviousSecretStore != ""
		}
		return cfg.writeResult(map[string]any{"profile": cfg.Profile, "store": effectiveStore(cfg), "api_key_configured": cfg.APIKey != "", "access_token_configured": cfg.AccessToken != "", "storage_backend": backend, "migration_cleanup_pending": cleanupPending, "precedence": "flags > environment > profile > defaults", "store_discovery": cfg.AccessToken != ""})
	}})
	auth.AddCommand(&cobra.Command{Use: "logout [PROFILE]", Args: cobra.MaximumNArgs(1), RunE: func(cmd *cobra.Command, args []string) error {
		doc, err := loadProfiles()
		if err != nil {
			return err
		}
		name := cfg.Profile
		if name == "" {
			name = doc.Active
		}
		if len(args) == 1 {
			name = args[0]
		}
		record, ok := doc.Profiles[name]
		if !ok {
			return &UsageError{Message: "unknown profile " + name}
		}
		if cfg.DryRun {
			_, err = fmt.Fprintln(cfg.Stdout, "Logout plan: revoke OAuth installation when applicable; contacted_network=false")
			return err
		}
		unlock, _, err := lockOAuth(record.VaultEntry)
		if err != nil {
			return err
		}
		defer unlock()
		record, err = prepareCredentialRecord(record)
		if err != nil {
			return err
		}
		if record.Method == "oauth" {
			if err = revokeOAuthLocked(cmd.Context(), record); err != nil {
				return err
			}
		} else if err = deleteProfileCredentials(record); err != nil {
			return err
		}
		return updateProfiles(func(doc *profileDocument) error {
			if current, ok := doc.Profiles[name]; ok && current.VaultEntry == record.VaultEntry {
				delete(doc.Profiles, name)
				if doc.Active == name {
					doc.Active = ""
				}
			}
			return nil
		})
	}})
}
func addStoreCommands(root *cobra.Command, cfg *Config) {
	var store *cobra.Command
	for _, existing := range root.Commands() {
		if existing.Name() == "stores" {
			store = existing
			break
		}
	}
	created := false
	if store == nil {
		store = &cobra.Command{Use: "stores", Short: "Store operations and active-store selection"}
		created = true
	}
	store.AddCommand(&cobra.Command{Use: "use SLUG", Args: cobra.ExactArgs(1), RunE: func(cmd *cobra.Command, args []string) error {
		doc, err := loadProfiles()
		if err != nil {
			return err
		}
		name := cfg.Profile
		if name == "" {
			name = doc.Active
		}
		record, ok := doc.Profiles[name]
		if !ok {
			return &UsageError{Message: "select a profile first"}
		}
		if cfg.DryRun {
			return json.NewEncoder(cfg.Stdout).Encode(map[string]any{"profile": name, "store": args[0], "contacted_network": false, "saved": false})
		}
		if record.Method == "oauth" {
			candidate := *cfg
			candidate.APIKey = ""
			candidate.AccessToken = ""
			candidate.CustomerSession = ""
			candidate.BrowserSession = ""
			candidate.Store = ""
			if err = resolveOAuth(record, &candidate); err != nil {
				return err
			}
			stores, err := permittedOAuthStores(cmd.Context(), &candidate)
			if err != nil {
				return err
			}
			found := false
			for _, slug := range stores {
				if slug == args[0] {
					found = true
				}
			}
			if !found {
				return &UsageError{Message: "store " + args[0] + " is not available to this OAuth installation", Suggestions: []string{"Run sellapp stores list to see available stores."}}
			}
		}
		return updateProfiles(func(doc *profileDocument) error {
			current, ok := doc.Profiles[name]
			if !ok || current.VaultEntry != record.VaultEntry {
				return errors.New("profile changed during store selection; retry")
			}
			current.Store = args[0]
			doc.Profiles[name] = current
			return nil
		})
	}})
	if created {
		root.AddCommand(store)
	}
}
