// Code generated by oagen. DO NOT EDIT.

//go:build windows

package cli

import (
	"os"
	"syscall"
)

func setPromptConsoleMode(handle syscall.Handle, mode uint32) error {
	procedure := syscall.NewLazyDLL("kernel32.dll").NewProc("SetConsoleMode")
	result, _, err := procedure.Call(uintptr(handle), uintptr(mode))
	if result == 0 {
		return err
	}
	return nil
}
func hideTerminalInput() (func() error, error) {
	handle := syscall.Handle(os.Stdin.Fd())
	var mode uint32
	if err := syscall.GetConsoleMode(handle, &mode); err != nil {
		return nil, err
	}
	if err := setPromptConsoleMode(handle, mode&^uint32(4)); err != nil {
		return nil, err
	}
	return func() error { return setPromptConsoleMode(handle, mode) }, nil
}
