// Code generated by oagen. DO NOT EDIT.

//go:build !windows

package cli

import (
	"os"
	"os/exec"
	"strings"
)

func hideTerminalInput() (func() error, error) {
	read := exec.Command("stty", "-g")
	read.Stdin = os.Stdin
	state, err := read.Output()
	if err != nil {
		return nil, err
	}
	disable := exec.Command("stty", "-echo")
	disable.Stdin = os.Stdin
	if err = disable.Run(); err != nil {
		return nil, err
	}
	return func() error {
		restore := exec.Command("stty", strings.TrimSpace(string(state)))
		restore.Stdin = os.Stdin
		return restore.Run()
	}, nil
}
