// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

func NewRootCommand(stdout, stderr io.Writer) *cobra.Command {
	cfg := &Config{BaseURL: defaultBaseURL, Timeout: 60 * time.Second, MaxRetries: 3, Output: "json", Stdout: stdout, Stderr: stderr}
	if base := os.Getenv("SELLAPP_API_BASE_URL"); base != "" {
		cfg.BaseURL = base
	}
	root := &cobra.Command{Use: "sellapp", Version: cliVersion, Short: "SellApp API command line client", SilenceErrors: true, SilenceUsage: true}
	if terminal, ok := stdout.(*os.File); ok {
		if isTerminalFile(terminal) {
			cfg.Output = "table"
		}
	}
	var llms, llmsFull, mcpServe bool
	mcpMode := "compact"
	root.Flags().BoolVar(&llms, "llms", false, "print a compact machine-readable command index")
	root.Flags().BoolVar(&llmsFull, "llms-full", false, "print full machine-readable command metadata")
	root.Flags().BoolVar(&mcpServe, "mcp", false, "bridge stdio to hosted Sell MCP")
	root.Flags().StringVar(&mcpMode, "mode", "compact", "MCP mode: compact, catalog, full, or retrieval")
	root.MarkFlagsMutuallyExclusive("llms", "llms-full", "mcp")
	root.RunE = func(cmd *cobra.Command, _ []string) error {
		if mcpServe {
			return serveMCP(cmd.Context(), cfg, mcpMode)
		}
		if llms || llmsFull {
			return commandManifest(cfg, llmsFull)
		}
		doc, err := loadProfiles()
		if err != nil {
			return err
		}
		name := cfg.Profile
		if name == "" {
			name = doc.Active
		}
		store := effectiveStore(cfg)
		if store == "(unset)" && doc.Profiles[name].Store != "" {
			store = doc.Profiles[name].Store
		}
		fmt.Fprintf(stdout, "SellApp: work with your store from the terminal.\nProfile: %s  Store: %s\n\nStart with:\n  sellapp login\n  sellapp products list\n  sellapp search products\n  sellapp commands products create --json\n", name, store)
		return nil
	}
	root.SetOut(stdout)
	root.SetErr(stderr)
	flags := root.PersistentFlags()
	flags.StringVar(&cfg.APIKey, "api-key", "", "SellApp bearer API key (or SELLAPP_API_KEY)")
	flags.StringVar(&cfg.Store, "store", "", "SellApp store identifier (or SELLAPP_STORE)")
	flags.StringVar(&cfg.BaseURL, "base-url", cfg.BaseURL, "SellApp API base URL (or SELLAPP_API_BASE_URL)")
	flags.DurationVar(&cfg.Timeout, "timeout", 60*time.Second, "request timeout")
	flags.IntVar(&cfg.MaxRetries, "max-retries", 3, "retries after the initial attempt; zero disables retries")
	flags.StringVarP(&cfg.Output, "output", "o", cfg.Output, "output format: json, jsonl, yaml, csv, markdown, table, or raw")
	flags.StringVar(&cfg.Fields, "fields", "", "comma-separated top-level fields to select")
	flags.StringVar(&cfg.Filter, "filter", "", "small filter expression FIELD=VALUE")
	flags.StringVar(&cfg.Template, "template", "", "small template using {{field}} placeholders")
	flags.BoolVar(&cfg.DryRun, "dry-run", false, "build the SDK request without network I/O and redact secrets")
	flags.BoolVar(&cfg.NoInteractive, "no-interactive", false, "disable prompts even in a TTY")
	flags.BoolVar(&cfg.Yes, "yes", false, "confirm high-impact writes for automation")
	flags.BoolVar(&cfg.NoAudit, "no-audit", false, "disable the redacted local invocation audit log")
	flags.StringVar(&cfg.AccessToken, "access-token", os.Getenv("SELLAPP_ACCESS_TOKEN"), "OAuth access token; prefer environment or a saved profile")
	flags.StringVar(&cfg.CustomerSession, "customer-session", os.Getenv("SELLAPP_CUSTOMER_SESSION"), "customer session credential; never combined with merchant credentials")
	flags.StringVar(&cfg.BrowserSession, "browser-session", "", "explicit browser session cookie for consent endpoints")
	flags.StringVar(&cfg.Profile, "profile", "", "named credential profile")
	root.PersistentPreRunE = func(cmd *cobra.Command, _ []string) error {
		cfg.Context = cmd.Context()
		cfg.BaseURLExplicit = cmd.Flags().Changed("base-url") || os.Getenv("SELLAPP_API_BASE_URL") != ""
		if !validOutput(cfg.Output) {
			return &UsageError{Message: "--output must be json, jsonl, yaml, csv, markdown, table, or raw"}
		}
		if cfg.Timeout <= 0 {
			return &UsageError{Message: "--timeout must be positive"}
		}
		if cfg.MaxRetries < 0 {
			return &UsageError{Message: "--max-retries cannot be negative"}
		}
		return nil
	}
	addCatalogCommands(root, cfg)
	addCommerceCommands(root, cfg)
	addDiscoveryCommands(root, cfg)
	addCompletionCommand(root)
	addProductCommands(root, cfg)
	configureHelp(root)
	return root
}

func addCatalogCommands(root *cobra.Command, cfg *Config) {
	groups := map[string]*cobra.Command{"": root}
	for _, catalogEntry := range CommandCatalog {
		entry := catalogEntry
		parentKey := ""
		parent := root
		for _, segment := range entry.Path[:len(entry.Path)-1] {
			key := strings.TrimSpace(parentKey + " " + segment)
			group := groups[key]
			if group == nil {
				group = &cobra.Command{Use: segment, Short: segment + " operations"}
				parent.AddCommand(group)
				groups[key] = group
			}
			parent, parentKey = group, key
		}
		leaf := &cobra.Command{Use: entry.Path[len(entry.Path)-1], Short: strings.Split(entry.Description, "\n")[0], Long: entry.Description, Example: entry.Example, Args: cobra.NoArgs}
		for _, parameter := range entry.Parameters {
			if parameter.Positional {
				leaf.Use += " [ID]"
				leaf.Args = cobra.MaximumNArgs(1)
			}
		}
		configureAdapter(leaf, cfg, entry)
		configureCommerceShorthand(leaf, cfg, entry)
		parent.AddCommand(leaf)
	}
}

func addDiscoveryCommands(root *cobra.Command, cfg *Config) {
	jsonOutput := false
	commands := &cobra.Command{Use: "commands [RESOURCE ACTION]", Short: "Discover commands or inspect one complete command schema", RunE: func(_ *cobra.Command, args []string) error {
		var value any
		if len(args) > 0 {
			found := false
			for _, entry := range CommandCatalog {
				if strings.Join(entry.Path, " ") == strings.Join(args, " ") {
					value = entry
					found = true
					break
				}
			}
			if !found {
				return &UsageError{Message: "unknown command; use sellapp search " + args[0]}
			}
		} else {
			index := []map[string]any{}
			for _, entry := range CommandCatalog {
				index = append(index, map[string]any{"command_path": entry.Path, "description": entry.Description, "effect": entry.Effect, "operation_id": entry.OperationID})
			}
			value = index
		}
		if jsonOutput {
			data, err := json.MarshalIndent(value, "", "  ")
			if err != nil {
				return err
			}
			_, err = fmt.Fprintln(cfg.Stdout, string(data))
			return err
		}
		if len(args) > 0 || cfg.Output == "json" || cfg.Output == "jsonl" {
			return writeFormattedResult(cfg, value)
		}
		for _, entry := range CommandCatalog {
			fmt.Fprintln(cfg.Stdout, strings.Join(entry.Path, " "))
		}
		return nil
	}}
	commands.Flags().BoolVar(&jsonOutput, "json", false, "emit the catalog as JSON")
	root.AddCommand(commands)
	root.AddCommand(&cobra.Command{Use: "docs RESOURCE ACTION", Short: "Print the API documentation link for a command", Args: cobra.MinimumNArgs(1), RunE: func(_ *cobra.Command, args []string) error {
		for _, entry := range CommandCatalog {
			if strings.Join(entry.Path, " ") == strings.Join(args, " ") {
				_, err := fmt.Fprintln(cfg.Stdout, entry.DocumentationURL)
				return err
			}
		}
		return &UsageError{Message: "unknown command; use sellapp search " + args[0]}
	}})
	root.AddCommand(&cobra.Command{Use: "search TERM", Short: "Search command paths and operation IDs", Args: cobra.ExactArgs(1), RunE: func(_ *cobra.Command, args []string) error {
		needle := strings.ToLower(args[0])
		matches := []any{}
		for _, entry := range CommandCatalog {
			haystack := strings.ToLower(strings.Join(entry.Path, " ") + " " + entry.OperationID + " " + entry.Description)
			if strings.Contains(haystack, needle) {
				if cfg.Output == "json" || cfg.Output == "jsonl" {
					matches = append(matches, entry)
				} else {
					fmt.Fprintln(cfg.Stdout, strings.Join(entry.Path, " "))
				}
			}
		}
		if cfg.Output == "json" || cfg.Output == "jsonl" {
			return writeMetadataResult(cfg, matches)
		}
		return nil
	}})
}

func addCompletionCommand(root *cobra.Command) {
	root.AddCommand(&cobra.Command{Use: "completion [bash|zsh|fish|powershell]", Short: "Generate shell completion", Args: cobra.ExactArgs(1), RunE: func(cmd *cobra.Command, args []string) error {
		switch args[0] {
		case "bash":
			return cmd.Root().GenBashCompletion(cmd.OutOrStdout())
		case "zsh":
			return cmd.Root().GenZshCompletion(cmd.OutOrStdout())
		case "fish":
			return cmd.Root().GenFishCompletion(cmd.OutOrStdout(), true)
		case "powershell":
			return cmd.Root().GenPowerShellCompletion(cmd.OutOrStdout())
		default:
			return &UsageError{Message: "unsupported shell " + args[0]}
		}
	}})
}
