// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/json"
	"io"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
)

func execute(t *testing.T, args ...string) (string, error) {
	t.Helper()
	var stdout, stderr bytes.Buffer
	root := NewRootCommand(&stdout, &stderr)
	root.SetArgs(args)
	err := root.Execute()
	return stdout.String(), err
}

func baseArgs(server *httptest.Server) []string {
	return []string{"--api-key", "test-key", "--store", "test-store", "--base-url", server.URL, "--max-retries", "0", "--yes"}
}

func TestCatalogHasExactCoverage(t *testing.T) {
	if len(CommandCatalog) != 434 {
		t.Fatalf("catalog=%d want=434", len(CommandCatalog))
	}
	executable := 0
	seen := map[string]bool{}
	for _, entry := range CommandCatalog {
		key := strings.Join(entry.Path, " ")
		if seen[key] {
			t.Fatalf("duplicate command path %s", key)
		}
		seen[key] = true
		if entry.Executable {
			executable++
		}
	}
	if executable != 434 {
		t.Fatalf("executable=%d want=434", executable)
	}
}

func TestSearchPreservesBodyAcrossPagesAndAllowsOmission(t *testing.T) {
	calls := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls++
		body, err := io.ReadAll(r.Body)
		if err != nil {
			t.Fatal(err)
		}
		if calls <= 2 {
			var filters map[string]any
			if err = json.Unmarshal(body, &filters); err != nil || filters["filters"] == nil {
				t.Errorf("missing search body: %s", body)
			}
			if calls == 2 {
				pagination, _ := filters["pagination"].(map[string]any)
				if pagination["page"] != float64(2) || r.URL.Query().Has("page") {
					t.Errorf("search must paginate in its body: %s %s", r.URL.String(), body)
				}
			}
		} else if len(body) != 0 {
			t.Errorf("optional body should be absent: %s", body)
		}
		w.Header().Set("Content-Type", "application/json")
		if calls == 1 {
			io.WriteString(w, "{\"data\":[],\"meta\":{\"current_page\":1,\"last_page\":2}}")
		} else {
			io.WriteString(w, "{\"data\":[],\"meta\":{\"current_page\":2,\"last_page\":2}}")
		}
	}))
	defer server.Close()
	args := append(baseArgs(server), "orders", "search", "--body", "{\"filters\":[]}", "--all")
	if _, err := execute(t, args...); err != nil {
		t.Fatal(err)
	}
	args = append(baseArgs(server), "orders", "search")
	if _, err := execute(t, args...); err != nil {
		t.Fatal(err)
	}
	if calls != 3 {
		t.Fatalf("calls=%d", calls)
	}
}

func TestCommandDiscoveryIncludesCredentialScopes(t *testing.T) {
	output, err := execute(t, "commands", "products", "create", "--json")
	if err != nil {
		t.Fatal(err)
	}
	var result map[string]any
	if err = json.Unmarshal([]byte(output), &result); err != nil {
		t.Fatal(err)
	}
	if result["authentication"] == nil || result["example"] == nil || result["effect"] != "write" {
		t.Fatalf("incomplete command discovery: %s", output)
	}
}
func TestEnumFlagsHaveHelpAndCompletion(t *testing.T) {
	output, err := execute(t, "products", "create", "--help")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(output, "Choices:") || !strings.Contains(output, "HIDDEN") {
		t.Fatal(output)
	}
	output, err = execute(t, "__complete", "products", "create", "--visibility", "")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(output, "HIDDEN") {
		t.Fatal(output)
	}
}

func TestAllTypedAdaptersExecuteDryRun(t *testing.T) {
	upload := t.TempDir() + "/fixture.bin"
	if err := os.WriteFile(upload, []byte("fixture-bytes"), 0o600); err != nil {
		t.Fatal(err)
	}
	for _, entry := range CommandCatalog {
		t.Run(entry.OperationKey, func(t *testing.T) {
			args := []string{"--dry-run", "--max-retries", "0"}
			args = append(args, entry.Path...)
			for _, parameter := range entry.Parameters {
				if parameter.Required {
					args = append(args, "--"+parameter.Flag, parameter.Fixture)
				}
			}
			if entry.Body != nil && entry.Body.Fixture != "" {
				args = append(args, "--body", entry.Body.Fixture)
			}
			if entry.Body != nil && entry.Body.Fixture == "" {
				bodyProvided := false
				for _, field := range entry.Body.Fields {
					if !field.Required {
						continue
					}
					bodyProvided = true
					if field.Binary || field.BinaryArray {
						args = append(args, "--upload", field.Name+"="+upload)
					} else {
						args = append(args, "--set", field.Name+"="+field.Fixture)
					}
				}
				if !bodyProvided {
					for _, field := range entry.Body.Fields {
						if !field.Binary && !field.BinaryArray {
							args = append(args, "--set", field.Name+"="+field.Fixture)
							bodyProvided = true
							break
						}
					}
					if !bodyProvided {
						args = append(args, "--body", "{}")
					}
				}
			}
			if _, err := execute(t, args...); err != nil {
				t.Fatalf("%s (%v): %v", entry.OperationKey, entry.Path, err)
			}
		})
	}
}

func TestTypedGetAdapterUsesSDKWireContract(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/v2/products/42" || r.URL.Query().Get("with_drafts") != "true" {
			t.Errorf("unexpected request %s", r.URL.String())
		}
		if r.Header.Get("Authorization") != "Bearer test-key" || r.Header.Get("X-STORE") != "test-store" {
			t.Errorf("missing auth headers")
		}
		w.Header().Set("Content-Type", "application/json")
		io.WriteString(w, responseFixture("GET /v2/products/{product}"))
	}))
	defer server.Close()
	args := append(baseArgs(server), "products", "get", "--product", "42", "--with-drafts")
	if _, err := execute(t, args...); err != nil {
		t.Fatal(err)
	}
}

func TestTypedJSONAdapter(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var body map[string]any
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			t.Fatal(err)
		}
		if body["title"] != "Fixture" {
			t.Errorf("body=%v", body)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		io.WriteString(w, responseFixture("POST /v2/products"))
	}))
	defer server.Close()
	args := append(baseArgs(server), "products", "create", "--body", "{\"title\":\"Fixture\",\"description\":\"D\",\"visibility\":\"PUBLIC\"}")
	if _, err := execute(t, args...); err != nil {
		t.Fatal(err)
	}
}

func TestOptionalNullableBodyFieldIsSentAsNull(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var body map[string]any
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			t.Fatal(err)
		}
		value, present := body["maximum_cashback_cents"]
		if !present || value != nil {
			t.Errorf("nullable field was not sent as null: %v", body)
		}
		w.Header().Set("Content-Type", "application/json")
		io.WriteString(w, responseFixture("PATCH /v2/cashback-rules/{cashbackRule}"))
	}))
	defer server.Close()
	args := append(baseArgs(server), "cashback-rules", "update", "--cashback-rule", "1", "--set", "maximum_cashback_cents=null")
	if _, err := execute(t, args...); err != nil {
		t.Fatal(err)
	}
}

func TestTypedMultipartAdapter(t *testing.T) {
	temp, err := os.CreateTemp(t.TempDir(), "upload-*.txt")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := temp.WriteString("fixture-bytes"); err != nil {
		t.Fatal(err)
	}
	if err := temp.Close(); err != nil {
		t.Fatal(err)
	}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		reader, err := r.MultipartReader()
		if err != nil {
			t.Fatal(err)
		}
		part, err := reader.NextPart()
		if err != nil {
			t.Fatal(err)
		}
		data, _ := io.ReadAll(part)
		if part.FormName() != "file" || string(data) != "fixture-bytes" {
			t.Errorf("bad multipart part %s %q", part.FormName(), data)
		}
		if _, err := reader.NextPart(); err != io.EOF && err != nil {
			t.Fatal(err)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		io.WriteString(w, responseFixture("POST /v2/products/{product}/variants/{variant}/deliverable/files"))
	}))
	defer server.Close()
	_ = multipart.ErrMessageTooLarge
	args := append(baseArgs(server), "variant-deliverable-files", "upload", "--product", "prod_1", "--variant", "7", "--upload", "file="+temp.Name())
	if _, err := execute(t, args...); err != nil {
		t.Fatal(err)
	}
}

func TestTypedPaginationAdapter(t *testing.T) {
	requests := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests++
		w.Header().Set("Content-Type", "application/json")
		var page map[string]any
		if err := json.Unmarshal([]byte(responseFixture("GET /v2/products")), &page); err != nil {
			t.Fatal(err)
		}
		page["links"] = map[string]any{"next": nil}
		if r.URL.Query().Get("page") != "2" {
			page["links"] = map[string]any{"next": serverURL(r) + "/v2/products?page=2"}
		}
		json.NewEncoder(w).Encode(page)
	}))
	defer server.Close()
	args := append(baseArgs(server), "products", "list", "--all")
	out, err := execute(t, args...)
	if err != nil {
		t.Fatal(err)
	}
	var values []any
	if err := json.Unmarshal([]byte(out), &values); err != nil {
		t.Fatal(err)
	}
	if len(values) != 2 {
		t.Fatalf("items=%d want=2", len(values))
	}
	first, ok := values[0].(map[string]any)
	if !ok || first["id"] == nil {
		t.Fatalf("expected product items, not nested pagination envelopes: %v", values[0])
	}
	requests = 0
	args = append(baseArgs(server), "products", "list", "--all", "--max-pages", "1")
	out, err = execute(t, args...)
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal([]byte(out), &values); err != nil {
		t.Fatal(err)
	}
	if len(values) != 1 || requests != 1 {
		t.Fatalf("max-pages fetched requests=%d items=%d", requests, len(values))
	}
}

func TestRetryRequiresSafeMethodOrIdempotencyKey(t *testing.T) {
	attempts := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		attempts++
		if attempts == 1 {
			w.Header().Set("Retry-After", "0")
			http.Error(w, "retry", http.StatusServiceUnavailable)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		if r.Method == "POST" {
			io.WriteString(w, responseFixture("POST /v2/affiliates/{affiliate}/payouts"))
		} else {
			io.WriteString(w, responseFixture("GET /v2/products/{product}"))
		}
	}))
	defer server.Close()
	args := []string{"--api-key", "test-key", "--store", "test-store", "--base-url", server.URL, "--max-retries", "1", "products", "get", "--product", "42"}
	if _, err := execute(t, args...); err != nil {
		t.Fatal(err)
	}
	if attempts != 2 {
		t.Fatalf("safe GET attempts=%d want=2", attempts)
	}

	attempts = 0
	args = []string{"--api-key", "test-key", "--store", "test-store", "--base-url", server.URL, "--max-retries", "1", "--yes", "affiliate-payouts", "create", "--affiliate", "1", "--idempotency-key", "retry-key"}
	if _, err := execute(t, args...); err != nil {
		t.Fatal(err)
	}
	if attempts != 2 {
		t.Fatalf("idempotent POST attempts=%d want=2", attempts)
	}
}

func TestMalformedResponseAndStableExitCodes(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		io.WriteString(w, "{")
	}))
	defer server.Close()
	args := append(baseArgs(server), "products", "get", "--product", "42")
	_, err := execute(t, args...)
	if err == nil {
		t.Fatal("expected malformed-response failure")
	}
	if ExitCode(err) != 6 {
		t.Fatalf("exit=%d want=6 (%v)", ExitCode(err), err)
	}
	if ExitCode(&UsageError{Message: "bad input"}) != 2 {
		t.Fatal("usage exit code changed")
	}
}

func serverURL(r *http.Request) string { return "http://" + r.Host }

func responseFixture(key string) string {
	for _, entry := range CommandCatalog {
		if entry.OperationKey == key {
			return entry.ResponseFixture
		}
	}
	panic("missing fixture for " + key)
}

func TestDryRunRedactsAndCannotReachProduction(t *testing.T) {
	out, err := execute(t, "--api-key", "secret-key", "--store", "secret-store", "--dry-run", "products", "get", "--product", "1")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(out, "secret-key") || strings.Contains(out, "secret-store") {
		t.Fatal("dry-run leaked a secret")
	}
	if !strings.Contains(out, "[REDACTED]") {
		t.Fatal("dry-run did not show redaction")
	}
}

func TestDryRunNeedsNoCredentials(t *testing.T) {
	if _, err := execute(t, "--dry-run", "products", "get", "--product", "1"); err != nil {
		t.Fatal(err)
	}
}

func TestEveryCatalogEntryHasTypedAdapter(t *testing.T) {
	for _, entry := range CommandCatalog {
		if !entry.Executable || entry.Adapter != entry.OperationKey {
			t.Fatalf("missing typed adapter for %s", entry.OperationKey)
		}
	}
}
