// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"
)

func setupOAuthFixture(t *testing.T, origin, store string) {
	t.Helper()
	credentialTestHome(t)
	t.Setenv("SELLAPP_API_KEY", "")
	t.Setenv("SELLAPP_STORE", "")
	t.Setenv("SELLAPP_ACCESS_TOKEN", "")
	t.Setenv("SELLAPP_PROFILE", "")
	old := credentialVaultRead
	t.Cleanup(func() { credentialVaultRead = old })
	credentialVaultRead = func(string) (string, error) {
		raw, _ := json.Marshal(oauthPair{AccessToken: "setup-parent", RefreshToken: "setup-refresh", ExpiresAt: time.Now().Add(time.Hour)})
		return string(raw), nil
	}
	doc, _ := loadProfiles()
	doc.Active = "setup"
	doc.Profiles["setup"] = profileRecord{Method: "oauth", Origin: origin, Store: store, VaultEntry: "fixture", ClientID: "official"}
	if err := saveProfiles(doc); err != nil {
		t.Fatal(err)
	}
}
func TestStoreCreateTargetsAccountAndSelectsOnlyWithUse(t *testing.T) {
	requests := 0
	failSave := false
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests++
		if r.Method != "POST" || r.URL.Path != "/api/v2/stores" || r.Header.Get("X-STORE") != "" || r.Header.Get("Idempotency-Key") == "" || r.Header.Get("Authorization") != "Bearer setup-parent" {
			t.Errorf("wrong account request: %s %s", r.Method, r.URL.Path)
		}
		if failSave {
			path, _ := profilePath()
			os.WriteFile(path, []byte("broken"), 0600)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(201)
		io.WriteString(w, `{"data":{"id":"1","name":"New Store","slug":"newstore","visibility":"PUBLIC","storefront_url":"https://newstore.sell.app","dashboard_url":"https://sell.app/dashboard"}}`)
	}))
	defer server.Close()
	setupOAuthFixture(t, server.URL, "previous")
	out, err := execute(t, "stores", "create", "--name", "New Store", "--slug", "newstore")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "newstore") {
		t.Fatal(out)
	}
	doc, _ := loadProfiles()
	if doc.Profiles["setup"].Store != "previous" {
		t.Fatal("creation changed selection without --use")
	}
	out, err = execute(t, "stores", "create", "--name", "New Store", "--slug", "newstore", "--use")
	if err != nil {
		t.Fatal(err)
	}
	doc, _ = loadProfiles()
	if doc.Profiles["setup"].Store != "newstore" {
		t.Fatal("explicit selection not saved")
	}
	failSave = true
	out, err = execute(t, "stores", "create", "--name", "New Store", "--slug", "newstore", "--use")
	if err == nil || !strings.Contains(out, "profile_selection_failed") || !strings.Contains(out, "newstore") {
		t.Fatalf("successful creation lost on profile failure: %s %v", out, err)
	}
	if requests != 3 {
		t.Fatalf("unexpected retry: %d", requests)
	}
}
func TestSetupZeroStoresRequiresExplicitCreationAndMakesOneBoundedRead(t *testing.T) {
	writes, reads := 0, 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch r.Method + " " + r.URL.Path {
		case "GET /api/v2/stores":
			io.WriteString(w, `{"data":[]}`)
		case "POST /api/v2/stores":
			writes++
			w.WriteHeader(201)
			io.WriteString(w, `{"data":{"id":"1","name":"New Store","slug":"newstore","visibility":"PUBLIC","storefront_url":"https://newstore.sell.app","dashboard_url":"https://sell.app/dashboard"}}`)
		case "GET /api/v2/products":
			reads++
			if r.Header.Get("X-STORE") != "newstore" || r.URL.Query().Get("limit") != "1" {
				t.Error("first read not bounded/targeted")
			}
			io.WriteString(w, `{"data":[]}`)
		default:
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
			w.WriteHeader(404)
		}
	}))
	defer server.Close()
	setupOAuthFixture(t, server.URL, "")
	if _, err := execute(t, "setup", "--no-interactive"); err == nil || !strings.Contains(err.Error(), "explicitly create") {
		t.Fatal(err)
	}
	if writes != 0 || reads != 0 {
		t.Fatal("missing choice caused side effects")
	}
	out, err := execute(t, "setup", "--create", "--name", "New Store", "--slug", "newstore", "--output", "jsonl")
	if err != nil {
		t.Fatal(err)
	}
	var result map[string]any
	if json.Unmarshal([]byte(out), &result) != nil || result["status"] != "ready" {
		t.Fatal(out)
	}
	if writes != 1 || reads != 1 {
		t.Fatalf("writes %d reads %d", writes, reads)
	}
}
func TestDiscoveryAndWorkflowCommandsNeedNoCredentials(t *testing.T) {
	credentialTestHome(t)
	t.Setenv("SELLAPP_API_KEY", "")
	for _, args := range [][]string{{"--llms"}, {"--llms-full"}, {"stores", "create", "--schema"}, {"search", "createStore", "--output", "jsonl"}, {"workflow", "list", "--output", "json"}, {"workflow", "show", "exports", "--output", "jsonl"}} {
		out, err := execute(t, args...)
		if err != nil {
			t.Fatal(args, err)
		}
		decoder := json.NewDecoder(strings.NewReader(out))
		count := 0
		for {
			var value any
			err = decoder.Decode(&value)
			if err == io.EOF {
				break
			}
			if err != nil {
				t.Fatal(args, out, err)
			}
			count++
		}
		if count == 0 {
			t.Fatal("empty discovery", args)
		}
	}
}
func TestCompactIndexPreservesCoverageAndFullSchemaLookup(t *testing.T) {
	credentialTestHome(t)
	out, err := execute(t, "--llms", "--output", "json")
	if err != nil {
		t.Fatal(err)
	}
	if len(out) > 100*1024 {
		t.Fatalf("compact index exceeded 100 KiB: %d bytes", len(out))
	}
	var rows []map[string]any
	if err = json.Unmarshal([]byte(out), &rows); err != nil {
		t.Fatal(err)
	}
	if len(rows) != len(CommandCatalog) {
		t.Fatalf("index omitted commands: %d", len(rows))
	}
	for i, row := range rows {
		entry := CommandCatalog[i]
		command := strings.Join(entry.Path, " ")
		if row["command"] != command || row["operation_id"] != entry.OperationID || row["effect"] != entry.Effect || row["target"] != entry.Target || row["schema"] != "sellapp "+command+" --schema" {
			t.Fatalf("incorrect lookup: %v", row)
		}
		if _, ok := row["authentication"]; ok {
			t.Fatal("index duplicated authentication")
		}
		if _, ok := row["retry"]; ok {
			t.Fatal("index duplicated retry rules")
		}
	}
	full, err := execute(t, "--llms-full", "--output", "json")
	if err != nil {
		t.Fatal(err)
	}
	var fullRows []map[string]any
	if err = json.Unmarshal([]byte(full), &fullRows); err != nil {
		t.Fatal(err)
	}
	if len(fullRows) != len(rows) {
		t.Fatal("full catalog lost operations")
	}
	for _, row := range fullRows {
		if row["authentication"] == nil || row["retry"] == nil {
			t.Fatal("full catalog lost metadata")
		}
	}
	schema, err := execute(t, "products", "create", "--schema")
	if err != nil {
		t.Fatal(err)
	}
	var entry map[string]any
	if err = json.Unmarshal([]byte(schema), &entry); err != nil {
		t.Fatal(err)
	}
	if entry["authentication"] == nil || entry["retry"] == nil {
		t.Fatal("leaf schema lost metadata")
	}
}

type searchTestPage struct {
	Results []map[string]any `json:"results"`
	Total   int              `json:"total"`
	Limit   int              `json:"limit"`
	Offset  int              `json:"offset"`
	Next    *int             `json:"next_offset"`
}

func TestSearchPaginatesWithoutLosingMatches(t *testing.T) {
	credentialTestHome(t)
	seen := map[string]bool{}
	offset, total := 0, -1
	for {
		out, err := execute(t, "search", "products", "--offset", strconv.Itoa(offset), "--output", "jsonl")
		if err != nil {
			t.Fatal(err)
		}
		if len(out) > 12*1024 || strings.Count(out, "\n") != 1 {
			t.Fatalf("search did not produce a bounded JSONL envelope: %d bytes", len(out))
		}
		var page searchTestPage
		if err = json.Unmarshal([]byte(out), &page); err != nil {
			t.Fatal(err)
		}
		if total < 0 {
			total = page.Total
			if total <= 10 {
				t.Fatal("fixture needs more than one page")
			}
		}
		if page.Total != total || page.Limit != 10 || page.Offset != offset || len(page.Results) > 10 {
			t.Fatal("inconsistent pagination", out)
		}
		for _, row := range page.Results {
			operation := row["operation_id"].(string)
			if seen[operation] {
				t.Fatal("duplicate search result", operation)
			}
			seen[operation] = true
			if row["schema"] == nil || row["summary"] == nil || row["authentication"] != nil {
				t.Fatal("search needs summaries and schema lookups", row)
			}
		}
		if page.Next == nil {
			break
		}
		if *page.Next <= offset {
			t.Fatal("pagination made no progress")
		}
		offset = *page.Next
	}
	if len(seen) != total {
		t.Fatalf("lost search results: got %d of %d", len(seen), total)
	}
	out, err := execute(t, "search", "LISTPRODUCTS", "--limit", "1", "--output", "json")
	if err != nil {
		t.Fatal(err)
	}
	var page searchTestPage
	if err = json.Unmarshal([]byte(out), &page); err != nil {
		t.Fatal(err)
	}
	if len(page.Results) != 1 || page.Results[0]["operation_id"] != "listProducts" {
		t.Fatal("exact operation must rank first", out)
	}
}
func TestSearchEmptyPagesBoundsAndReadableOutput(t *testing.T) {
	credentialTestHome(t)
	for _, args := range [][]string{{"search", "no-such-operation-xyz"}, {"search", "products", "--offset", "2147483647"}} {
		out, err := execute(t, append(args, "--output", "json")...)
		if err != nil {
			t.Fatal(err)
		}
		var page searchTestPage
		if err = json.Unmarshal([]byte(out), &page); err != nil {
			t.Fatal(err)
		}
		if page.Results == nil || len(page.Results) != 0 || page.Next != nil {
			t.Fatal("empty page contract", out)
		}
	}
	for _, args := range [][]string{{"search", " "}, {"search", "products", "--limit", "0"}, {"search", "products", "--limit", "26"}, {"search", "products", "--offset", "-1"}} {
		if _, err := execute(t, args...); err == nil {
			t.Fatal("invalid search accepted", args)
		}
	}
	out, err := execute(t, "search", "products", "--limit", "1", "--output", "table")
	if err != nil || !strings.Contains(out, "Inspect: sellapp ") || !strings.Contains(out, "--offset 1") {
		t.Fatal("missing inspection or next page guidance", out, err)
	}
}
func TestSearchBoundsUnicodeSummaries(t *testing.T) {
	before := CommandCatalog
	defer func() { CommandCatalog = before }()
	CommandCatalog = []CatalogEntry{{Path: []string{"example", "read"}, OperationID: "readExample", Description: strings.Repeat("界", 300) + "\nprivate detail", Effect: "read"}}
	var out bytes.Buffer
	cfg := &Config{Output: "json", Stdout: &out, Stderr: &out}
	cmd := searchCommand(cfg)
	cmd.SetArgs([]string{"example"})
	if err := cmd.Execute(); err != nil {
		t.Fatal(err)
	}
	var page searchTestPage
	if err := json.Unmarshal(out.Bytes(), &page); err != nil {
		t.Fatal(err)
	}
	summary := page.Results[0]["summary"].(string)
	if len([]rune(summary)) != 160 || strings.Contains(summary, "�") || strings.Contains(summary, "private detail") {
		t.Fatal("summary not bounded at a character boundary", summary)
	}
}
