// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
	"time"
)

func setupOAuthFixture(t *testing.T, origin, store string) {
	t.Helper()
	credentialTestHome(t)
	t.Setenv("SELLAPP_API_KEY", "")
	t.Setenv("SELLAPP_STORE", "")
	t.Setenv("SELLAPP_ACCESS_TOKEN", "")
	t.Setenv("SELLAPP_PROFILE", "")
	old := credentialVaultRead
	t.Cleanup(func() { credentialVaultRead = old })
	credentialVaultRead = func(string) (string, error) {
		raw, _ := json.Marshal(oauthPair{AccessToken: "setup-parent", RefreshToken: "setup-refresh", ExpiresAt: time.Now().Add(time.Hour)})
		return string(raw), nil
	}
	doc, _ := loadProfiles()
	doc.Active = "setup"
	doc.Profiles["setup"] = profileRecord{Method: "oauth", Origin: origin, Store: store, VaultEntry: "fixture", ClientID: "official"}
	if err := saveProfiles(doc); err != nil {
		t.Fatal(err)
	}
}
func TestStoreCreateTargetsAccountAndSelectsOnlyWithUse(t *testing.T) {
	requests := 0
	failSave := false
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests++
		if r.Method != "POST" || r.URL.Path != "/api/v2/stores" || r.Header.Get("X-STORE") != "" || r.Header.Get("Idempotency-Key") == "" || r.Header.Get("Authorization") != "Bearer setup-parent" {
			t.Errorf("wrong account request: %s %s", r.Method, r.URL.Path)
		}
		if failSave {
			path, _ := profilePath()
			os.WriteFile(path, []byte("broken"), 0600)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(201)
		io.WriteString(w, `{"data":{"id":"1","name":"New Store","slug":"newstore","visibility":"PUBLIC","storefront_url":"https://newstore.sell.app","dashboard_url":"https://sell.app/dashboard"}}`)
	}))
	defer server.Close()
	setupOAuthFixture(t, server.URL, "previous")
	out, err := execute(t, "stores", "create", "--name", "New Store", "--slug", "newstore")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "newstore") {
		t.Fatal(out)
	}
	doc, _ := loadProfiles()
	if doc.Profiles["setup"].Store != "previous" {
		t.Fatal("creation changed selection without --use")
	}
	out, err = execute(t, "stores", "create", "--name", "New Store", "--slug", "newstore", "--use")
	if err != nil {
		t.Fatal(err)
	}
	doc, _ = loadProfiles()
	if doc.Profiles["setup"].Store != "newstore" {
		t.Fatal("explicit selection not saved")
	}
	failSave = true
	out, err = execute(t, "stores", "create", "--name", "New Store", "--slug", "newstore", "--use")
	if err == nil || !strings.Contains(out, "profile_selection_failed") || !strings.Contains(out, "newstore") {
		t.Fatalf("successful creation lost on profile failure: %s %v", out, err)
	}
	if requests != 3 {
		t.Fatalf("unexpected retry: %d", requests)
	}
}
func TestSetupZeroStoresRequiresExplicitCreationAndMakesOneBoundedRead(t *testing.T) {
	writes, reads := 0, 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch r.Method + " " + r.URL.Path {
		case "GET /api/v2/stores":
			io.WriteString(w, `{"data":[]}`)
		case "POST /api/v2/stores":
			writes++
			w.WriteHeader(201)
			io.WriteString(w, `{"data":{"id":"1","name":"New Store","slug":"newstore","visibility":"PUBLIC","storefront_url":"https://newstore.sell.app","dashboard_url":"https://sell.app/dashboard"}}`)
		case "GET /api/v2/products":
			reads++
			if r.Header.Get("X-STORE") != "newstore" || r.URL.Query().Get("limit") != "1" {
				t.Error("first read not bounded/targeted")
			}
			io.WriteString(w, `{"data":[]}`)
		default:
			t.Errorf("unexpected request %s %s", r.Method, r.URL.Path)
			w.WriteHeader(404)
		}
	}))
	defer server.Close()
	setupOAuthFixture(t, server.URL, "")
	if _, err := execute(t, "setup", "--no-interactive"); err == nil || !strings.Contains(err.Error(), "explicitly create") {
		t.Fatal(err)
	}
	if writes != 0 || reads != 0 {
		t.Fatal("missing choice caused side effects")
	}
	out, err := execute(t, "setup", "--create", "--name", "New Store", "--slug", "newstore", "--output", "jsonl")
	if err != nil {
		t.Fatal(err)
	}
	var result map[string]any
	if json.Unmarshal([]byte(out), &result) != nil || result["status"] != "ready" {
		t.Fatal(out)
	}
	if writes != 1 || reads != 1 {
		t.Fatalf("writes %d reads %d", writes, reads)
	}
}
func TestDiscoveryAndWorkflowCommandsNeedNoCredentials(t *testing.T) {
	credentialTestHome(t)
	t.Setenv("SELLAPP_API_KEY", "")
	for _, args := range [][]string{{"--llms"}, {"--llms-full"}, {"stores", "create", "--schema"}, {"search", "createStore", "--output", "jsonl"}, {"workflow", "list", "--output", "json"}, {"workflow", "show", "exports", "--output", "jsonl"}} {
		out, err := execute(t, args...)
		if err != nil {
			t.Fatal(args, err)
		}
		decoder := json.NewDecoder(strings.NewReader(out))
		count := 0
		for {
			var value any
			err = decoder.Decode(&value)
			if err == io.EOF {
				break
			}
			if err != nil {
				t.Fatal(args, out, err)
			}
			count++
		}
		if count == 0 {
			t.Fatal("empty discovery", args)
		}
	}
}
