// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"errors"
	"github.com/spf13/cobra"
	"strings"
)

func selectCreatedStore(cfg *Config, slug string) error {
	doc, err := loadProfiles()
	if err != nil {
		return err
	}
	name := cfg.Profile
	if name == "" {
		name = doc.Active
	}
	before, ok := doc.Profiles[name]
	if !ok {
		return errors.New("no selected profile")
	}
	return updateProfiles(func(doc *profileDocument) error {
		record, ok := doc.Profiles[name]
		if !ok || record.VaultEntry != before.VaultEntry {
			return errors.New("profile changed during store selection")
		}
		record.Store = slug
		doc.Profiles[name] = record
		return nil
	})
}
func storeSelectionFailure(cfg *Config, result any, slug string) error {
	object, err := workflowObject(result)
	if err != nil {
		return err
	}
	object["selection"] = map[string]any{"saved": false, "error_code": "profile_selection_failed", "recovery": "Store creation succeeded. Run sellapp stores use " + slug + " after fixing local profile storage; do not create it again."}
	if err = cfg.writeResult(object); err != nil {
		return err
	}
	return &UsageError{Message: "Store created, but local store selection could not be saved.", Suggestions: []string{"Run sellapp stores use " + slug + " after repairing profile storage."}}
}
func finishStoreCreation(cfg *Config, result any, use bool) error {
	if !use || cfg.DryRun {
		return cfg.writeResult(result)
	}
	data, err := workflowData(result)
	if err != nil {
		return err
	}
	slug, _ := data["slug"].(string)
	if slug == "" {
		return errors.New("created store response omitted its slug; inspect stores list before retrying")
	}
	resultObject, err := workflowObject(result)
	if err != nil {
		return err
	}
	if err = selectCreatedStore(cfg, slug); err != nil {
		return storeSelectionFailure(cfg, result, slug)
	}
	cfg.Store = slug
	resultObject["selection"] = map[string]any{"saved": true, "store": slug}
	return cfg.writeResult(resultObject)
}
func setupCommand(cfg *Config) *cobra.Command {
	var create bool
	var name, slug, visibility, clientID, idempotencyKey string
	cmd := &cobra.Command{Use: "setup", Short: "Connect, choose or create a store, and verify a first read", Args: cobra.NoArgs, RunE: func(cmd *cobra.Command, _ []string) error {
		if cfg.DryRun {
			return &UsageError{Message: "setup requires a live connection; use stores create --dry-run to preview creation."}
		}
		doc, err := loadProfiles()
		if err != nil {
			return err
		}
		profile := cfg.Profile
		if profile == "" {
			profile = doc.Active
		}
		if record, ok := doc.Profiles[profile]; !ok || record.Method != "oauth" {
			if !interactivePresentation(cmd, cfg) {
				return &UsageError{Message: "Connect before running setup.", MissingFields: []string{"oauth_profile"}, Suggestions: []string{"Run sellapp login, then sellapp setup --store SLUG or sellapp setup --create --name NAME --slug SLUG."}}
			}
			if profile == "" {
				profile = "default"
			}
			if err = oauthLogin(cmd, cfg, profile, "", clientID, defaultOAuthScopes); err != nil {
				return err
			}
			cfg.Profile = profile
		}
		candidate := *cfg
		candidate.APIKey = ""
		candidate.AccessToken = ""
		candidate.CustomerSession = ""
		candidate.BrowserSession = ""
		candidate.Store = ""
		candidate.oauthProfile = true
		if err = resolveProfileConfig(&candidate); err != nil {
			return err
		}
		stores, err := permittedOAuthStores(cmd.Context(), &candidate)
		if err != nil {
			return err
		}
		target := cfg.Store
		if create && target != "" {
			return &UsageError{Message: "Choose --create or --store, not both."}
		}
		if !create && target == "" {
			choices := append(append([]string{}, stores...), "Create a new store")
			if !interactivePresentation(cmd, cfg) {
				return &UsageError{Message: "Choose an existing store or explicitly create one.", MissingFields: []string{"store_or_create"}, Suggestions: append([]string{"Use --store SLUG, or --create --name NAME --slug SLUG."}, stores...)}
			}
			target, err = promptChoice(cmd, cfg, "Choose a store", choices, "")
			if err != nil {
				return err
			}
			if target == "Create a new store" {
				create = true
				target = ""
			}
		}
		if create {
			missing := []string{}
			if name == "" {
				missing = append(missing, "name")
			}
			if slug == "" {
				missing = append(missing, "slug")
			}
			if len(missing) > 0 && !interactivePresentation(cmd, cfg) {
				return &UsageError{Message: "Store creation requires a name and slug.", MissingFields: missing, Suggestions: []string{"Use --create --name NAME --slug SLUG."}}
			}
			if name == "" {
				name, err = promptLineContext(cmd.Context(), "Store name")
				if err != nil {
					return err
				}
			}
			if slug == "" {
				slug, err = promptLineContext(cmd.Context(), "Store slug")
				if err != nil {
					return err
				}
			}
			inv := workflowInvocation()
			inv.Body = map[string]json.RawMessage{}
			if idempotencyKey != "" {
				inv.Headers["Idempotency-Key"] = idempotencyKey
			}
			for field, value := range map[string]string{"name": name, "slug": slug, "visibility": visibility} {
				raw, _ := json.Marshal(value)
				inv.Body[field] = raw
			}
			value, err := runWorkflowOperation(cmd, &candidate, "createStore", inv, true)
			if err != nil {
				return err
			}
			data, err := workflowData(value)
			if err != nil {
				return err
			}
			target, _ = data["slug"].(string)
			if target == "" {
				return errors.New("creation returned no slug; inspect stores list before repeating")
			}
			if err = selectCreatedStore(&candidate, target); err != nil {
				return storeSelectionFailure(&candidate, value, target)
			}
		} else {
			found := false
			for _, available := range stores {
				if available == target {
					found = true
				}
			}
			if !found {
				return &UsageError{Message: "Store is not currently accessible.", Suggestions: append([]string{"Choose a store from sellapp stores list."}, stores...)}
			}
			if !cfg.DryRun {
				if err = selectCreatedStore(&candidate, target); err != nil {
					return err
				}
			}
		}
		candidate.Store = target
		inv := workflowInvocation()
		inv.Query["limit"] = "1"
		inv.MaxItems = 1
		inv.MaxPages = 1
		value, err := runWorkflowOperation(cmd, &candidate, "listProducts", inv, false)
		if err != nil {
			if outputErr := writeFormattedResult(cfg, map[string]any{"status": "store_selected", "store": target, "created": create, "verification": "failed", "recovery": "The store exists. Check your current permissions and run sellapp products list --store " + target + " --limit 1."}); outputErr != nil {
				return outputErr
			}
			return err
		}
		return writeFormattedResult(cfg, map[string]any{"status": "ready", "profile": candidate.Profile, "store": target, "created": create, "verification": value})
	}}
	cmd.Flags().BoolVar(&create, "create", false, "explicitly create a store")
	cmd.Flags().StringVar(&name, "name", "", "name for a new store")
	cmd.Flags().StringVar(&slug, "slug", "", "slug for a new store")
	cmd.Flags().StringVar(&visibility, "visibility", "PUBLIC", "PUBLIC, HIDDEN, or PRIVATE")
	cmd.Flags().StringVar(&idempotencyKey, "idempotency-key", "", "reuse the same key when retrying the same store creation")
	cmd.Flags().StringVar(&clientID, "client-id", "", "operator-supplied official CLI registration")
	cmd.Flags().Bool("no-browser", false, "print the login URL instead of opening a browser")
	return cmd
}
func commandManifest(cfg *Config, full bool) error {
	if full {
		return writeMetadataResult(cfg, CommandCatalog)
	}
	rows := []any{}
	for _, entry := range CommandCatalog {
		rows = append(rows, map[string]any{"command": strings.Join(entry.Path, " "), "operation_id": entry.OperationID, "effect": entry.Effect, "target": entry.Target, "retry": entry.Retry, "authentication": entry.Authentication, "paginated": entry.Paginated, "idempotency_key": entry.IdempotencyKey, "idempotency_key_required": entry.IdempotencyKeyRequired, "schema": "sellapp " + strings.Join(entry.Path, " ") + " --schema"})
	}
	return writeMetadataResult(cfg, rows)
}
