// Code generated by oagen. DO NOT EDIT.

//go:build !windows

package cli

import (
	"os"
	"os/exec"
)

// isTerminalFile asks the OS-backed shell terminal test, excluding devices such as /dev/null.
func isTerminalFile(file *os.File) bool {
	info, err := file.Stat()
	if err != nil || info.Mode()&os.ModeCharDevice == 0 {
		return false
	}
	probe := exec.Command("sh", "-c", "test -t 0")
	probe.Stdin = file
	return probe.Run() == nil
}
