// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"context"
	"crypto/rand"
	"encoding/csv"
	"encoding/json"
	"errors"
	"fmt"
	sdk "github.com/sellapp/sellapp-cli/internal/sdk"
	"github.com/spf13/cobra"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

func prepareInvocation(cmd *cobra.Command, cfg *Config, entry CatalogEntry, values map[string]*string, body *string, assignments *[]string, uploads []string) error {
	interactive := interactivePresentation(cmd, cfg)
	missing := []string{}
	suggestions := []string{}
	for _, p := range entry.Parameters {
		if !p.Required || cmd.Flags().Changed(p.Flag) {
			continue
		}
		if !interactive {
			missing = append(missing, p.Name)
			hint := "Supply --" + p.Flag
			if p.Positional {
				hint = "Supply the resource ID after " + strings.Join(entry.Path, " ")
			}
			suggestions = append(suggestions, hint)
			continue
		}
		value, err := promptLineContext(cmd.Context(), p.Description+" Enter "+p.Name)
		if err != nil {
			return err
		}
		if value == "" {
			return &UsageError{Message: "--" + p.Flag + " is required"}
		}
		*values[p.Name] = value
		_ = cmd.Flags().Set(p.Flag, value)
	}
	if entry.Body != nil && (entry.Body.Required || *body != "" || len(*assignments) > 0 || len(uploads) > 0) {
		parsed, err := readJSONObject(*body, *assignments, cmd.InOrStdin())
		if err != nil {
			return err
		}
		uploaded := map[string]bool{}
		for _, upload := range uploads {
			name, source, ok := strings.Cut(upload, "=")
			if !ok || source == "" {
				return &UsageError{Message: "--upload requires FIELD=PATH"}
			}
			var field *CatalogBodyField
			for i := range entry.Body.Fields {
				if entry.Body.Fields[i].Name == name {
					field = &entry.Body.Fields[i]
					break
				}
			}
			if field == nil || (!field.Binary && !field.BinaryArray) {
				return &UsageError{Message: "unknown upload field " + name}
			}
			if _, exists := parsed[name]; exists {
				return &UsageError{Message: "conflicting assignments for " + name}
			}
			if uploaded[name] && !field.BinaryArray {
				return &UsageError{Message: "conflicting uploads for " + name}
			}
			uploaded[name] = true
		}
		for _, f := range entry.Body.Fields {
			if !f.Required || f.Binary || f.BinaryArray {
				continue
			}
			if _, exists := parsed[f.Name]; exists {
				continue
			}
			if !interactive {
				missing = append(missing, f.Name)
				suggestions = append(suggestions, "Supply --"+f.Flag+" or include "+f.Name+" in --body.")
				continue
			}
			value, err := promptLineContext(cmd.Context(), f.Description+" Enter "+f.Name)
			if err != nil {
				return err
			}
			raw, err := bodyFlagJSON(f, value)
			if err != nil {
				return err
			}
			parsed[f.Name] = json.RawMessage(raw)
		}
		for _, f := range entry.Body.Fields {
			if !f.Required || (!f.Binary && !f.BinaryArray) {
				continue
			}
			present := false
			for _, upload := range uploads {
				parts := strings.SplitN(upload, "=", 2)
				if len(parts) == 2 && parts[0] == f.Name && parts[1] != "" {
					present = true
				}
			}
			if !present {
				missing = append(missing, f.Name)
				suggestions = append(suggestions, "Supply --upload "+f.Name+"=PATH.")
			}
		}
		for _, f := range entry.Body.Fields {
			if raw, exists := parsed[f.Name]; exists {
				var value any
				if json.Unmarshal(raw, &value) == nil {
					for _, path := range missingNestedInputs(f.Schema, value, f.Name) {
						missing = append(missing, path)
						suggestions = append(suggestions, "Include "+path+" in --body or --"+f.Flag+" JSON.")
					}
				}
			}
		}
		if entry.Body.Schema != nil {
			encoded, _ := json.Marshal(parsed)
			var value any
			if json.Unmarshal(encoded, &value) == nil {
				for _, path := range missingNestedInputs(entry.Body.Schema, value, "") {
					missing = append(missing, path)
					suggestions = append(suggestions, "Include "+path+" for the selected request variant in --body.")
				}
			}
		}
		encoded, err := json.Marshal(parsed)
		if err != nil {
			return err
		}
		*body = string(encoded)
		*assignments = nil
	}
	if len(missing) > 0 {
		return &UsageError{Message: "missing required inputs: " + strings.Join(missing, ", "), MissingFields: missing, Suggestions: suggestions}
	}
	return nil
}

func effectiveStore(cfg *Config) string {
	if cfg.Store != "" {
		return cfg.Store
	}
	if v := os.Getenv("SELLAPP_STORE"); v != "" {
		return v
	}
	return "(unset)"
}
func confirmWrite(cmd *cobra.Command, cfg *Config, entry CatalogEntry) error {
	if cfg.DryRun || entry.Effect == "read" || entry.Effect == "write" || entry.Method == "GET" || entry.Method == "HEAD" || entry.Method == "OPTIONS" {
		return nil
	}
	if cfg.Yes {
		return nil
	}
	if !interactivePresentation(cmd, cfg) {
		return &UsageError{Message: "write " + entry.OperationID + " to store " + effectiveStore(cfg) + " requires --yes in non-TTY mode"}
	}
	answer, err := promptLineContext(cmd.Context(), "Run "+entry.OperationID+" against store "+effectiveStore(cfg)+"? Type yes")
	if err != nil {
		return err
	}
	if strings.ToLower(answer) != "yes" {
		return context.Canceled
	}
	return nil
}
func invocationIdempotencyKey(entry CatalogEntry) (string, error) {
	if !entry.IdempotencyKey {
		return "", nil
	}
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("cannot generate idempotency key: %w", err)
	}
	b[6] = (b[6] & 15) | 64
	b[8] = (b[8] & 63) | 128
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[:4], b[4:6], b[6:8], b[8:10], b[10:]), nil
}
func validOutput(v string) bool {
	switch v {
	case "json", "jsonl", "yaml", "csv", "markdown", "table", "raw":
		return true
	}
	return false
}
func redactSensitive(value any) any {
	switch v := value.(type) {
	case map[string]any:
		for key, item := range v {
			normalized := strings.ToLower(strings.ReplaceAll(key, "-", "_"))
			switch normalized {
			case "access_token", "refresh_token", "client_secret", "code_verifier", "authorization", "cookie", "set_cookie", "api_key", "secret", "token", "code", "state", "download_url", "redemption_url", "signature", "location":
				v[key] = "[REDACTED]"
			default:
				v[key] = redactSensitive(item)
			}
		}
	case []any:
		for i, item := range v {
			v[i] = redactSensitive(item)
		}
	}
	return value
}
func selectAndFilter(value any, fields, filter string, metadata ...bool) (any, error) {
	data, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	var decoded any
	if err = json.Unmarshal(data, &decoded); err != nil {
		return nil, err
	}
	if len(metadata) == 0 || !metadata[0] {
		decoded = redactSensitive(decoded)
	}
	rows, isRows := decoded.([]any)
	if !isRows {
		rows = []any{decoded}
	}
	if filter != "" {
		key, want, ok := strings.Cut(filter, "=")
		if !ok || strings.TrimSpace(key) == "" {
			return nil, &UsageError{Message: "--filter requires FIELD=VALUE"}
		}
		kept := []any{}
		for _, item := range rows {
			if row, ok := item.(map[string]any); ok && fmt.Sprint(row[key]) == want {
				kept = append(kept, item)
			}
		}
		rows = kept
	}
	if fields != "" {
		names := strings.Split(fields, ",")
		for i, item := range rows {
			row, ok := item.(map[string]any)
			if !ok {
				return nil, &UsageError{Message: "--fields requires object results"}
			}
			next := map[string]any{}
			for _, name := range names {
				name = strings.TrimSpace(name)
				if v, ok := row[name]; ok {
					next[name] = v
				}
			}
			rows[i] = next
		}
	}
	if isRows {
		return rows, nil
	}
	if len(rows) == 0 {
		return nil, nil
	}
	return rows[0], nil
}
func writeMetadataResult(cfg *Config, value any) error {
	copy := *cfg
	copy.metadataOutput = true
	return writeFormattedResult(&copy, value)
}
func writeFormattedResult(cfg *Config, value any) error {
	value, err := selectAndFilter(value, cfg.Fields, cfg.Filter, cfg.metadataOutput)
	if err != nil {
		return err
	}
	if cfg.Template != "" {
		return writeTemplate(cfg.Stdout, value, cfg.Template)
	}
	if cfg.Output == "raw" {
		if data, ok := value.([]byte); ok {
			_, err = cfg.Stdout.Write(data)
			return err
		}
		data, err := json.Marshal(value)
		if err == nil {
			_, err = cfg.Stdout.Write(append(data, '\n'))
		}
		return err
	}
	if cfg.Output == "table" {
		return writeTable(cfg.Stdout, value)
	}
	if cfg.Output == "json" {
		data, err := json.MarshalIndent(value, "", "  ")
		if err == nil {
			_, err = cfg.Stdout.Write(append(data, '\n'))
		}
		return err
	}
	rows, ok := value.([]any)
	if !ok {
		rows = []any{value}
	}
	switch cfg.Output {
	case "jsonl":
		for _, row := range rows {
			data, e := json.Marshal(row)
			if e != nil {
				return e
			}
			if _, e = cfg.Stdout.Write(append(data, '\n')); e != nil {
				return e
			}
		}
		return nil
	case "csv":
		return writeDelimited(cfg.Stdout, rows, false)
	case "markdown":
		return writeDelimited(cfg.Stdout, rows, true)
	case "yaml":
		for i, row := range rows {
			if i > 0 {
				fmt.Fprintln(cfg.Stdout, "---")
			}
			writeYAML(cfg.Stdout, row, 0)
		}
		return nil
	}
	return &UsageError{Message: "unsupported output format"}
}
func objectRows(rows []any) ([]string, []map[string]any, error) {
	keys := []string{}
	seen := map[string]bool{}
	objects := []map[string]any{}
	for _, item := range rows {
		row, ok := item.(map[string]any)
		if !ok {
			return nil, nil, &UsageError{Message: "CSV/Markdown requires object rows"}
		}
		objects = append(objects, row)
		for k := range row {
			if !seen[k] {
				seen[k] = true
				keys = append(keys, k)
			}
		}
	}
	sort.Strings(keys)
	return keys, objects, nil
}
func writeDelimited(out io.Writer, rows []any, markdown bool) error {
	keys, objects, err := objectRows(rows)
	if err != nil {
		return err
	}
	if markdown {
		fmt.Fprintln(out, "| "+strings.Join(keys, " | ")+" |")
		fmt.Fprintln(out, "| "+strings.TrimSpace(strings.Repeat("--- | ", len(keys))))
		for _, row := range objects {
			values := []string{}
			for _, k := range keys {
				values = append(values, strings.ReplaceAll(fmt.Sprint(row[k]), "|", "\\|"))
			}
			fmt.Fprintln(out, "| "+strings.Join(values, " | ")+" |")
		}
		return nil
	}
	w := csv.NewWriter(out)
	_ = w.Write(keys)
	for _, row := range objects {
		values := []string{}
		for _, k := range keys {
			values = append(values, fmt.Sprint(row[k]))
		}
		_ = w.Write(values)
	}
	w.Flush()
	return w.Error()
}
func writeYAML(out io.Writer, value any, indent int) {
	prefix := strings.Repeat(" ", indent)
	switch item := value.(type) {
	case map[string]any:
		keys := []string{}
		for k := range item {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			data, _ := json.Marshal(item[k])
			fmt.Fprintf(out, "%s%s: %s\n", prefix, k, data)
		}
	case []any:
		for _, v := range item {
			data, _ := json.Marshal(v)
			fmt.Fprintf(out, "%s- %s\n", prefix, data)
		}
	default:
		data, _ := json.Marshal(item)
		fmt.Fprintln(out, prefix+string(data))
	}
}
func writeTemplate(out io.Writer, value any, format string) error {
	rows, ok := value.([]any)
	if !ok {
		rows = []any{value}
	}
	for _, item := range rows {
		row, ok := item.(map[string]any)
		if !ok {
			return &UsageError{Message: "--template requires object results"}
		}
		rendered := format
		for {
			start := strings.Index(rendered, "{{")
			if start < 0 {
				break
			}
			tail := rendered[start+2:]
			offset := strings.Index(tail, "}}")
			if offset < 0 {
				return &UsageError{Message: "unterminated template"}
			}
			end := start + 2 + offset
			key := strings.TrimSpace(rendered[start+2 : end])
			rendered = rendered[:start] + fmt.Sprint(row[key]) + rendered[end+2:]
		}
		fmt.Fprintln(out, rendered)
	}
	return nil
}

type auditEntry struct {
	Time       string `json:"time"`
	Operation  string `json:"operation"`
	Profile    string `json:"profile,omitempty"`
	Store      string `json:"store,omitempty"`
	DurationMS int64  `json:"duration_ms"`
	Status     int    `json:"status,omitempty"`
	ExitClass  int    `json:"exit_class"`
	RequestID  string `json:"request_id,omitempty"`
}

func requestIDFromError(err error) string {
	var api *sdk.APIError
	if errors.As(err, &api) {
		return api.RequestID
	}
	var auth *sdk.AuthenticationError
	if errors.As(err, &auth) {
		return auth.RequestID
	}
	var forbidden *sdk.AuthorizationError
	if errors.As(err, &forbidden) {
		return forbidden.RequestID
	}
	var notFound *sdk.NotFoundError
	if errors.As(err, &notFound) {
		return notFound.RequestID
	}
	var conflict *sdk.ConflictError
	if errors.As(err, &conflict) {
		return conflict.RequestID
	}
	var invalid *sdk.UnprocessableEntityError
	if errors.As(err, &invalid) {
		return invalid.RequestID
	}
	var limited *sdk.RateLimitExceededError
	if errors.As(err, &limited) {
		return limited.RequestID
	}
	var server *sdk.ServerError
	if errors.As(err, &server) {
		return server.RequestID
	}
	return ""
}
func apiDetailsFromError(err error) (int, string, string) {
	var api *sdk.APIError
	if errors.As(err, &api) {
		return api.Status, api.Type, api.Code
	}
	var auth *sdk.AuthenticationError
	if errors.As(err, &auth) {
		return auth.Status, auth.Type, auth.Code
	}
	var forbidden *sdk.AuthorizationError
	if errors.As(err, &forbidden) {
		return forbidden.Status, forbidden.Type, forbidden.Code
	}
	var notFound *sdk.NotFoundError
	if errors.As(err, &notFound) {
		return notFound.Status, notFound.Type, notFound.Code
	}
	var conflict *sdk.ConflictError
	if errors.As(err, &conflict) {
		return conflict.Status, conflict.Type, conflict.Code
	}
	var invalid *sdk.UnprocessableEntityError
	if errors.As(err, &invalid) {
		return invalid.Status, invalid.Type, invalid.Code
	}
	var limited *sdk.RateLimitExceededError
	if errors.As(err, &limited) {
		return limited.Status, limited.Type, limited.Code
	}
	var server *sdk.ServerError
	if errors.As(err, &server) {
		return server.Status, server.Type, server.Code
	}
	return 0, "", ""
}
func auditPath() (string, error) {
	root, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(root, "SellApp", "cli", "audit.jsonl"), nil
}
func writeAudit(cfg *Config, operation string, started time.Time, requestErr error) {
	if cfg.NoAudit || os.Getenv("SELLAPP_AUDIT_DISABLED") == "1" {
		return
	}
	path, err := auditPath()
	if err != nil {
		return
	}
	if _, err = credentialDir(); err != nil {
		return
	}
	if info, e := os.Stat(path); e == nil && info.Size() > 1<<20 {
		for i := 4; i >= 1; i-- {
			_ = os.Rename(path+"."+strconv.Itoa(i), path+"."+strconv.Itoa(i+1))
		}
		_ = os.Rename(path, path+".1")
	}
	status, _, _ := apiDetailsFromError(requestErr)
	if status == 0 {
		status = cfg.lastStatus
	}
	requestID := requestIDFromError(requestErr)
	if requestID == "" {
		requestID = cfg.lastRequestID
	}
	entry := auditEntry{Time: time.Now().UTC().Format(time.RFC3339), Operation: operation, Profile: cfg.Profile, Store: effectiveStore(cfg), DurationMS: time.Since(started).Milliseconds(), Status: status, ExitClass: ExitCode(requestErr), RequestID: requestID}
	data, _ := json.Marshal(entry)
	file, e := os.OpenFile(path, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0600)
	if e == nil {
		defer file.Close()
		_, _ = file.Write(append(data, '\n'))
		_ = file.Chmod(0600)
	}
}
