// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"fmt"
	"os"
	"testing"
	"time"
)

func TestWindowsCredentialVaultRoundTrip(t *testing.T) {
	if os.Getenv("SELLAPP_CLI_TEST_NATIVE_VAULT") != "1" {
		t.Skip("native vault test requires explicit opt-in")
	}
	entry := fmt.Sprintf("test-roundtrip-%d", time.Now().UnixNano())
	secret := "fixture-only-token"
	if err := vaultWrite(entry, secret); err != nil {
		t.Fatal(err)
	}
	defer func() {
		if err := vaultDelete(entry); err != nil {
			t.Error(err)
		}
	}()
	actual, err := vaultRead(entry)
	if err != nil {
		t.Fatal(err)
	}
	if actual != secret {
		t.Fatal("vault round trip changed content")
	}
}
