// Code generated by oagen. DO NOT EDIT.

package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	sdk "github.com/sellapp/sellapp-cli/internal/sdk"
	"github.com/spf13/cobra"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"time"
)

func addProductCommands(root *cobra.Command, cfg *Config) {
	addAuthCommands(root, cfg)
	for _, group := range root.Commands() {
		if group.Name() == "auth" {
			for _, command := range group.Commands() {
				if command.Name() == "logout" {
					topLogout := *command
					root.AddCommand(&topLogout)
				}
			}
		}
	}
	addStoreCommands(root, cfg)
	root.AddCommand(setupCommand(cfg), doctorCommand(cfg), workflowCommand(cfg), mcpCommand(cfg), agentCommand(cfg), skillsCommand(cfg))
}
func compatibleRead(words ...string) *CatalogEntry {
	if len(words) == 0 {
		words = []string{"listProducts"}
	}
	for i := range CommandCatalog {
		e := &CommandCatalog[i]
		if e.Method != "GET" || e.Body != nil {
			continue
		}
		required := false
		for _, p := range e.Parameters {
			if p.Required {
				required = true
			}
		}
		if required {
			continue
		}
		hay := strings.ToLower(e.OperationID + " " + strings.Join(e.Path, " "))
		matched := false
		for _, w := range words {
			if strings.Contains(hay, strings.ToLower(w)) {
				matched = true
			}
		}
		if matched {
			return e
		}
	}
	return nil
}
func runRead(ctx context.Context, cfg *Config, words ...string) (any, error) {
	if err := resolveProfileConfig(cfg); err != nil {
		return nil, err
	}
	entry := compatibleRead(words...)
	if entry == nil {
		return nil, &UsageError{Message: "no compatible read operation in this API contract"}
	}
	query := map[string]string{}
	if entry.OperationID == "listProducts" {
		query["limit"] = "1"
	}
	started := time.Now()
	result, err := sdk.ExecuteCLI(ctx, cfg.client(), entry.OperationKey, sdk.CLIInvocation{Path: map[string]string{}, Query: query, Headers: map[string]string{}, Cookies: map[string]string{}})
	writeAudit(cfg, entry.OperationID, started, err)
	return result, err
}
func doctorCommand(cfg *Config) *cobra.Command {
	return &cobra.Command{Use: "doctor", Short: "Check local setup and one harmless generated read", RunE: func(cmd *cobra.Command, _ []string) error {
		if err := resolveProfileConfig(cfg); err != nil {
			return err
		}
		checks := map[string]any{"version": cliVersion, "runtime": runtime.GOOS + "/" + runtime.GOARCH, "vault_available": vaultAvailable(), "credentials_configured": cfg.APIKey != "" || cfg.AccessToken != "", "store": effectiveStore(cfg), "completion": "sellapp completion <shell>", "checked": "configuration, vault, runtime, credentials, store and one harmless read"}
		if (cfg.APIKey == "" && cfg.AccessToken == "") || cfg.Store == "" {
			checks["read"] = "skipped: credentials and explicit store required"
			return cfg.writeResult(checks)
		}
		_, err := runRead(cmd.Context(), cfg)
		if err != nil {
			return err
		}
		checks["read"] = "ok"
		return cfg.writeResult(checks)
	}}
}
func catalogOperation(id string) (CatalogEntry, error) {
	for _, entry := range CommandCatalog {
		if entry.OperationID == id {
			return entry, nil
		}
	}
	return CatalogEntry{}, &UsageError{Message: "workflow operation is unavailable in this API contract: " + id}
}
func workflowInvocation() sdk.CLIInvocation {
	return sdk.CLIInvocation{Path: map[string]string{}, Query: map[string]string{}, Headers: map[string]string{}, Cookies: map[string]string{}, Body: map[string]json.RawMessage{}, Files: map[string][][]byte{}}
}
func workflowBody(values map[string]any) (map[string]json.RawMessage, error) {
	body := map[string]json.RawMessage{}
	for key, value := range values {
		data, err := json.Marshal(value)
		if err != nil {
			return nil, err
		}
		body[key] = data
	}
	return body, nil
}
func validateWorkflowInvocation(entry CatalogEntry, inv sdk.CLIInvocation) error {
	for _, p := range entry.Parameters {
		if !p.Required {
			continue
		}
		present := false
		switch p.Location {
		case "path":
			present = strings.TrimSpace(inv.Path[p.Name]) != ""
		case "query":
			present = strings.TrimSpace(inv.Query[p.Name]) != ""
		case "header":
			present = strings.TrimSpace(inv.Headers[p.Name]) != ""
		case "cookie":
			present = strings.TrimSpace(inv.Cookies[p.Name]) != ""
		}
		if !present {
			return &UsageError{Message: "missing required " + p.Location + " field " + p.Name + " for " + entry.OperationID}
		}
	}
	if entry.Body != nil {
		for _, f := range entry.Body.Fields {
			if !f.Required {
				continue
			}
			if f.Binary || f.BinaryArray {
				if len(inv.Files[f.Name]) == 0 {
					return &UsageError{Message: "missing required upload " + f.Name + " for " + entry.OperationID}
				}
			} else if _, ok := inv.Body[f.Name]; !ok {
				return &UsageError{Message: "missing required body field " + f.Name + " for " + entry.OperationID}
			}
		}
	}
	return nil
}
func runWorkflowOperation(cmd *cobra.Command, cfg *Config, id string, inv sdk.CLIInvocation, write bool) (any, error) {
	if err := resolveProfileConfig(cfg); err != nil {
		return nil, err
	}
	entry, err := catalogOperation(id)
	if err != nil {
		return nil, err
	}
	if err = validateWorkflowInvocation(entry, inv); err != nil {
		return nil, err
	}
	if write {
		if entry.Method == "GET" || entry.Method == "HEAD" {
			return nil, &UsageError{Message: "workflow expected a write operation: " + id}
		}
		if err := confirmWrite(cmd, cfg, entry); err != nil {
			return nil, err
		}
	} else if entry.Method != "GET" && entry.Method != "HEAD" {
		return nil, &UsageError{Message: "workflow expected a read operation: " + id}
	}
	cfg.dryRunResponse = entry.ResponseFixture
	cfg.dryRunAPIKey = entry.APIKeyOnly
	started := time.Now()
	key, err := invocationIdempotencyKey(entry)
	if err != nil {
		return nil, err
	}
	if supplied := inv.Headers["Idempotency-Key"]; supplied != "" {
		key = supplied
	}
	result, err := sdk.ExecuteCLI(cmd.Context(), cfg.client(), entry.OperationKey, inv, requestOptions(key)...)
	writeAudit(cfg, entry.OperationID, started, err)
	if err != nil {
		return nil, err
	}
	if cfg.DryRun {
		return map[string]any{"operation_id": entry.OperationID, "operation_key": entry.OperationKey, "request": cfg.capture.request, "contacted_network": false}, nil
	}
	return result, nil
}
func writeWorkflowResult(cfg *Config, value any) error { return writeFormattedResult(cfg, value) }
func readinessCommand(cfg *Config) *cobra.Command {
	return &cobra.Command{Use: "store-readiness", Short: "Check settings, payment methods, webhook channels, and custom domains", Args: cobra.NoArgs, RunE: func(cmd *cobra.Command, _ []string) error {
		ids := []string{"getStoreSettings", "listPaymentMethods", "listWebhookChannels", "listCustomDomains"}
		checks := map[string]any{}
		for _, id := range ids {
			value, err := runWorkflowOperation(cmd, cfg, id, workflowInvocation(), false)
			if err != nil {
				return err
			}
			checks[id] = value
		}
		return writeWorkflowResult(cfg, map[string]any{"workflow": "store-readiness", "checked": ids, "results": checks, "claims": "configuration state only; this does not discover permissions or guarantee readiness"})
	}}
}
func pollingCommand(cfg *Config, name, operation string) *cobra.Command {
	var maxPolls, limit int
	var interval time.Duration
	cmd := &cobra.Command{Use: name, Short: "Poll a generated list operation with explicit time and count bounds", Args: cobra.NoArgs, RunE: func(cmd *cobra.Command, _ []string) error {
		if maxPolls < 1 || maxPolls > 100 {
			return &UsageError{Message: "--max-polls must be between 1 and 100"}
		}
		if interval < 0 {
			return &UsageError{Message: "--interval cannot be negative"}
		}
		snapshots := make([]any, 0, maxPolls)
		for attempt := 0; attempt < maxPolls; attempt++ {
			inv := workflowInvocation()
			if limit > 0 {
				inv.Query["limit"] = fmt.Sprint(limit)
			}
			value, err := runWorkflowOperation(cmd, cfg, operation, inv, false)
			if err != nil {
				return err
			}
			snapshots = append(snapshots, map[string]any{"poll": attempt + 1, "result": value})
			if attempt+1 < maxPolls && interval > 0 {
				timer := time.NewTimer(interval)
				select {
				case <-cmd.Context().Done():
					timer.Stop()
					return cmd.Context().Err()
				case <-timer.C:
				}
			}
		}
		return writeWorkflowResult(cfg, map[string]any{"workflow": name, "operation_id": operation, "max_polls": maxPolls, "interval": interval.String(), "snapshots": snapshots})
	}}
	cmd.Flags().IntVar(&maxPolls, "max-polls", 5, "maximum polling requests (1-100)")
	cmd.Flags().DurationVar(&interval, "interval", 2*time.Second, "delay between polls")
	cmd.Flags().IntVar(&limit, "limit", 25, "items requested per poll")
	return cmd
}
func supportTriageCommand(cfg *Config) *cobra.Command {
	var ticket string
	var limit int
	cmd := &cobra.Command{Use: "support-triage", Short: "Read tickets, one selected ticket, and its messages", Args: cobra.NoArgs, RunE: func(cmd *cobra.Command, _ []string) error {
		if strings.TrimSpace(ticket) == "" {
			return &UsageError{Message: "--ticket is required for composed support triage"}
		}
		listInv := workflowInvocation()
		if limit > 0 {
			listInv.Query["limit"] = fmt.Sprint(limit)
		}
		listed, err := runWorkflowOperation(cmd, cfg, "v2ListTickets", listInv, false)
		if err != nil {
			return err
		}
		detailInv := workflowInvocation()
		detailInv.Path["ticket"] = ticket
		detail, err := runWorkflowOperation(cmd, cfg, "v2GetTicket", detailInv, false)
		if err != nil {
			return err
		}
		messagesInv := workflowInvocation()
		messagesInv.Path["ticket"] = ticket
		if limit > 0 {
			messagesInv.Query["limit"] = fmt.Sprint(limit)
		}
		messages, err := runWorkflowOperation(cmd, cfg, "v2ListTicketMessages", messagesInv, false)
		if err != nil {
			return err
		}
		return writeWorkflowResult(cfg, map[string]any{"workflow": "support-triage", "checked": []string{"v2ListTickets", "v2GetTicket", "v2ListTicketMessages"}, "ticket": ticket, "tickets": listed, "detail": detail, "messages": messages})
	}}
	cmd.Flags().StringVar(&ticket, "ticket", "", "ticket ID to inspect")
	cmd.Flags().IntVar(&limit, "limit", 25, "ticket/message page size")
	return cmd
}
func readWorkflowFile(path string) ([]byte, error) {
	if path == "-" {
		return io.ReadAll(os.Stdin)
	}
	return os.ReadFile(path)
}
func draftProductCommand(cfg *Config) *cobra.Command {
	var title, description, visibility, product, variant, deliverable, inventory, parsingMode string
	cmd := &cobra.Command{Use: "product-draft", Short: "Create a draft product and optionally upload a deliverable or serial inventory", Args: cobra.NoArgs, RunE: func(cmd *cobra.Command, _ []string) error {
		if title == "" || description == "" {
			return &UsageError{Message: "--title and --description are required"}
		}
		uploading := deliverable != "" || inventory != ""
		if uploading && (product == "" || variant == "") {
			return &UsageError{Message: "--product and --variant are required when an upload is requested"}
		}
		if deliverable == "-" && inventory == "-" {
			return &UsageError{Message: "stdin can supply only one workflow upload"}
		}
		var deliverableData, inventoryData []byte
		var err error
		if deliverable != "" {
			deliverableData, err = readWorkflowFile(deliverable)
			if err != nil {
				return err
			}
		}
		if inventory != "" {
			inventoryData, err = readWorkflowFile(inventory)
			if err != nil {
				return err
			}
		}
		body, err := workflowBody(map[string]any{"title": title, "description": description, "visibility": visibility})
		if err != nil {
			return err
		}
		createInv := workflowInvocation()
		createInv.Body = body
		created, err := runWorkflowOperation(cmd, cfg, "createProduct", createInv, true)
		if err != nil {
			return err
		}
		steps := []any{map[string]any{"operation_id": "createProduct", "result": created}}
		if !uploading {
			return writeWorkflowResult(cfg, map[string]any{"workflow": "product-draft", "steps": steps, "note": "No upload requested; pass --product and --variant with --deliverable or --inventory."})
		}
		if deliverable != "" {
			inv := workflowInvocation()
			inv.Path["product"] = product
			inv.Path["variant"] = variant
			inv.Files["file"] = [][]byte{deliverableData}
			value, err := runWorkflowOperation(cmd, cfg, "uploadVariantDeliverableFile", inv, true)
			if err != nil {
				return err
			}
			steps = append(steps, map[string]any{"operation_id": "uploadVariantDeliverableFile", "result": value})
		}
		if inventory != "" {
			inv := workflowInvocation()
			inv.Path["product"] = product
			inv.Path["variant"] = variant
			inv.Files["file"] = [][]byte{inventoryData}
			inv.Body, err = workflowBody(map[string]any{"parsing_mode": parsingMode})
			if err != nil {
				return err
			}
			value, err := runWorkflowOperation(cmd, cfg, "queueVariantSerialImport", inv, true)
			if err != nil {
				return err
			}
			steps = append(steps, map[string]any{"operation_id": "queueVariantSerialImport", "result": value})
		}
		return writeWorkflowResult(cfg, map[string]any{"workflow": "product-draft", "steps": steps})
	}}
	cmd.Flags().StringVar(&title, "title", "", "draft product title")
	cmd.Flags().StringVar(&description, "description", "", "draft product description")
	cmd.Flags().StringVar(&visibility, "visibility", "PRIVATE", "draft visibility")
	cmd.Flags().StringVar(&product, "product", "", "created/existing product ID for uploads")
	cmd.Flags().StringVar(&variant, "variant", "", "variant ID for uploads")
	cmd.Flags().StringVar(&deliverable, "deliverable", "", "deliverable file path or - for stdin")
	cmd.Flags().StringVar(&inventory, "inventory", "", "serial inventory file path or - for stdin")
	cmd.Flags().StringVar(&parsingMode, "parsing-mode", "LINE", "serial import parsing mode")
	return cmd
}
func webhookTestCommand(cfg *Config) *cobra.Command {
	var channel, event string
	cmd := &cobra.Command{Use: "webhook-test", Short: "Read a webhook channel and invoke its existing test operation", Args: cobra.NoArgs, RunE: func(cmd *cobra.Command, _ []string) error {
		if channel == "" || event == "" {
			return &UsageError{Message: "--channel and --event are required"}
		}
		readInv := workflowInvocation()
		readInv.Path["webhookChannel"] = channel
		before, err := runWorkflowOperation(cmd, cfg, "getWebhookChannel", readInv, false)
		if err != nil {
			return err
		}
		testInv := workflowInvocation()
		testInv.Path["webhookChannel"] = channel
		testInv.Body, err = workflowBody(map[string]any{"event": event})
		if err != nil {
			return err
		}
		sent, err := runWorkflowOperation(cmd, cfg, "sendTestWebhook", testInv, true)
		if err != nil {
			return err
		}
		return writeWorkflowResult(cfg, map[string]any{"workflow": "webhook-test", "checked": []string{"getWebhookChannel", "sendTestWebhook"}, "channel": before, "test": sent, "limitations": "This sends a test event. Inspect and replay real deliveries with the generated webhook delivery commands."})
	}}
	cmd.Flags().StringVar(&channel, "channel", "", "webhook channel ID")
	cmd.Flags().StringVar(&event, "event", "", "existing test-event value")
	return cmd
}

type catalogPlan struct {
	Changes []catalogChange `json:"changes"`
}
type catalogChange struct {
	ReadOperation  string                     `json:"read_operation"`
	WriteOperation string                     `json:"write_operation"`
	Path           map[string]string          `json:"path"`
	Query          map[string]string          `json:"query,omitempty"`
	Expected       json.RawMessage            `json:"expected"`
	Body           map[string]json.RawMessage `json:"body"`
}

func (plan *catalogPlan) UnmarshalJSON(data []byte) error {
	type plain catalogPlan
	var decoded plain
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	for _, change := range decoded.Changes {
		readEntry, err := catalogOperation(change.ReadOperation)
		if err != nil {
			return err
		}
		writeEntry, err := catalogOperation(change.WriteOperation)
		if err != nil {
			return err
		}
		if readEntry.Method != "GET" && readEntry.Method != "HEAD" {
			return &UsageError{Message: "read_operation must be GET or HEAD: " + change.ReadOperation}
		}
		if writeEntry.Method == "GET" || writeEntry.Method == "HEAD" {
			return &UsageError{Message: "write_operation must mutate: " + change.WriteOperation}
		}
		readInv := workflowInvocation()
		readInv.Path = change.Path
		readInv.Query = change.Query
		if err = validateWorkflowInvocation(readEntry, readInv); err != nil {
			return err
		}
		writeInv := workflowInvocation()
		writeInv.Path = change.Path
		writeInv.Query = change.Query
		writeInv.Body = change.Body
		if err = validateWorkflowInvocation(writeEntry, writeInv); err != nil {
			return err
		}
		var expected any
		if len(change.Expected) == 0 || json.Unmarshal(change.Expected, &expected) != nil {
			return &UsageError{Message: "invalid expected snapshot for " + change.ReadOperation}
		}
	}
	*plan = catalogPlan(decoded)
	return nil
}
func canonicalJSON(value any) ([]byte, error) {
	data, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	var normalized any
	if err = json.Unmarshal(data, &normalized); err != nil {
		return nil, err
	}
	return json.Marshal(normalized)
}
func catalogApplyCommand(cfg *Config) *cobra.Command {
	return &cobra.Command{Use: "apply FILE", Short: "Reread every target, refuse mismatches, then apply a non-atomic catalog plan", Args: cobra.ExactArgs(1), RunE: func(cmd *cobra.Command, args []string) error {
		data, err := readWorkflowFile(args[0])
		if err != nil {
			return err
		}
		var plan catalogPlan
		if err = json.Unmarshal(data, &plan); err != nil {
			return &UsageError{Message: "invalid catalog plan: " + err.Error()}
		}
		if len(plan.Changes) == 0 {
			return &UsageError{Message: "catalog plan has no changes"}
		}
		reads := make([]any, len(plan.Changes))
		for index, change := range plan.Changes {
			readEntry, err := catalogOperation(change.ReadOperation)
			if err != nil {
				return err
			}
			writeEntry, err := catalogOperation(change.WriteOperation)
			if err != nil {
				return err
			}
			if readEntry.Method != "GET" && readEntry.Method != "HEAD" {
				return &UsageError{Message: "read_operation must be GET or HEAD: " + change.ReadOperation}
			}
			if writeEntry.Method == "GET" || writeEntry.Method == "HEAD" {
				return &UsageError{Message: "write_operation must mutate: " + change.WriteOperation}
			}
			inv := workflowInvocation()
			inv.Path = change.Path
			inv.Query = change.Query
			current, err := runWorkflowOperation(cmd, cfg, change.ReadOperation, inv, false)
			if err != nil {
				return err
			}
			reads[index] = current
			if !cfg.DryRun {
				actual, err := canonicalJSON(current)
				if err != nil {
					return err
				}
				var expected any
				if err = json.Unmarshal(change.Expected, &expected); err != nil {
					return &UsageError{Message: "invalid expected snapshot for " + change.ReadOperation}
				}
				wanted, err := canonicalJSON(expected)
				if err != nil {
					return err
				}
				if !bytes.Equal(actual, wanted) {
					return &UsageError{Message: "catalog apply refused: reread mismatch for " + change.ReadOperation + "; no mutations were sent"}
				}
			}
		}
		results := make([]any, 0, len(plan.Changes))
		for index, change := range plan.Changes {
			inv := workflowInvocation()
			inv.Path = change.Path
			inv.Query = change.Query
			inv.Body = change.Body
			value, err := runWorkflowOperation(cmd, cfg, change.WriteOperation, inv, true)
			if err != nil {
				return err
			}
			results = append(results, map[string]any{"change": index + 1, "result": value})
		}
		return writeWorkflowResult(cfg, map[string]any{"workflow": "catalog-apply", "reread": reads, "results": results, "atomic": false, "warning": "This local plan is not atomic. Include each operation's documented concurrency fields; rereads alone cannot prevent races."})
	}}
}
func workflowListCommand(cfg *Config) *cobra.Command {
	return &cobra.Command{Use: "list", Short: "List focused commerce guides", Args: cobra.NoArgs, RunE: func(_ *cobra.Command, _ []string) error {
		index := []map[string]any{}
		for _, guide := range workflowGuides() {
			index = append(index, map[string]any{"id": guide["id"], "title": guide["title"], "purpose": guide["purpose"]})
		}
		return writeMetadataResult(cfg, index)
	}}
}
func workflowShowCommand(cfg *Config) *cobra.Command {
	return &cobra.Command{Use: "show ID", Short: "Read one commerce guide", Args: cobra.ExactArgs(1), RunE: func(_ *cobra.Command, args []string) error {
		for _, guide := range workflowGuides() {
			if guide["id"] == args[0] {
				return writeMetadataResult(cfg, guide)
			}
		}
		return &UsageError{Message: "Unknown workflow: " + args[0], Suggestions: []string{"Run sellapp workflow list."}}
	}}
}
func workflowCommand(cfg *Config) *cobra.Command {
	root := &cobra.Command{Use: "workflow", Short: "Commerce workflows over generated SDK adapters"}
	root.AddCommand(workflowListCommand(cfg), workflowShowCommand(cfg), eventsPollCommand(cfg), exportWorkflowCommand(cfg), webhookInspectCommand(cfg), readinessCommand(cfg), pollingCommand(cfg, "orders-poll", "listOrders"), pollingCommand(cfg, "support-poll", "v2ListTickets"), supportTriageCommand(cfg), draftProductCommand(cfg), webhookTestCommand(cfg))
	catalog := &cobra.Command{Use: "catalog", Short: "Compare the command catalog and apply individual catalog changes"}
	catalog.AddCommand(&cobra.Command{Use: "export", RunE: func(_ *cobra.Command, _ []string) error { return writeWorkflowResult(cfg, CommandCatalog) }})
	catalog.AddCommand(&cobra.Command{Use: "diff FILE", Args: cobra.ExactArgs(1), RunE: func(_ *cobra.Command, args []string) error {
		data, err := os.ReadFile(args[0])
		if err != nil {
			return err
		}
		var previous []CatalogEntry
		if err = json.Unmarshal(data, &previous); err != nil {
			return err
		}
		before := map[string]bool{}
		after := map[string]bool{}
		for _, e := range previous {
			before[e.OperationKey] = true
		}
		for _, e := range CommandCatalog {
			after[e.OperationKey] = true
		}
		added, removed := []string{}, []string{}
		for k := range after {
			if !before[k] {
				added = append(added, k)
			}
		}
		for k := range before {
			if !after[k] {
				removed = append(removed, k)
			}
		}
		sort.Strings(added)
		sort.Strings(removed)
		return writeWorkflowResult(cfg, map[string]any{"added": added, "removed": removed, "atomic": false, "note": "This compares the local command catalog only."})
	}})
	catalog.AddCommand(catalogApplyCommand(cfg))
	root.AddCommand(catalog)
	return root
}

type rpcRequest struct {
	JSONRPC string         `json:"jsonrpc"`
	ID      any            `json:"id"`
	Method  string         `json:"method"`
	Params  map[string]any `json:"params"`
}

func agentCommand(cfg *Config) *cobra.Command {
	root := &cobra.Command{Use: "agent", Short: "Print or install the common SellApp guidance"}
	root.AddCommand(&cobra.Command{Use: "print", Args: cobra.NoArgs, RunE: func(_ *cobra.Command, _ []string) error {
		_, err := io.WriteString(cfg.Stdout, embeddedAgentGuide)
		return err
	}})
	var force bool
	install := &cobra.Command{Use: "install DIRECTORY", Args: cobra.ExactArgs(1), RunE: func(_ *cobra.Command, args []string) error {
		target, err := filepath.Abs(args[0])
		if err != nil {
			return err
		}
		if cfg.DryRun {
			return writeFormattedResult(cfg, map[string]any{"directory": target, "saved": false})
		}
		return installSkillTree(target, map[string]string{"SELLAPP_AGENT.md": embeddedAgentGuide}, force)
	}}
	install.Flags().BoolVar(&force, "force", false, "replace locally modified generated guidance")
	root.AddCommand(install)
	return root
}
