// Code generated by oagen. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"

	"github.com/sellapp/sellapp-cli/internal/cli"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()
	root := cli.NewRootCommand(os.Stdout, os.Stderr)
	if err := root.ExecuteContext(ctx); err != nil {
		fmt.Fprintln(os.Stderr, cli.FormatError(err))
		os.Exit(cli.ExitCode(err))
	}
}
